import {getDefaultFrameClock,type FrameClock} from '@/lib/animation-clock';
import * as T from 'three';
import {constrainToFloor,type FloorBounds} from './placement';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {LandscapeRenderer} from '../LandscapeRenderer';
export type WorldSettings={hour:number;weather:string;paused:boolean;exposure:number;auto:boolean};
export type WorldBundle={lighting?:{ambient:number;sun:number;sunColor:string;skyColor:string;groundColor:string;sunPosition:[number,number,number];environment?:number;shadowRadius?:number};walkBounds?:{minX:number;maxX:number;eyeHeight:number};interactive?:boolean;interior?:boolean;dispose?:()=>void;group:T.Group;camera:[number,number,number];target:[number,number,number];background:string;fog?:number;tick?:(time:number,settings:WorldSettings)=>void;update?:(settings:WorldSettings)=>void;movables?:T.Object3D[];ground?:number;bounds?:number;floorBounds?:FloorBounds;progress?:(n:number)=>void;name:string};
export function createWorldEngine(host:HTMLDivElement,onFallback:(v:boolean)=>void,onSelect:(o:T.Object3D|null)=>void,onPhoto:(data:string)=>void,clock:FrameClock=getDefaultFrameClock()){
 const {requestFrame,cancelFrame}=clock;
 let dirty=true;
 let renderer:T.WebGLRenderer|LandscapeRenderer;
 try{renderer=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true,powerPreference:'high-performance'})}catch{renderer=new LandscapeRenderer()}
 const simple=renderer instanceof LandscapeRenderer;onFallback(simple);renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1;renderer.outputColorSpace=T.SRGBColorSpace;
 if(!simple){const gl=renderer as T.WebGLRenderer;gl.shadowMap.enabled=true;gl.shadowMap.type=T.PCFSoftShadowMap}
 const canvas=renderer.domElement;canvas.setAttribute('aria-label','可旋转、缩放的三维世界');canvas.tabIndex=0;host.appendChild(canvas);
 const scene=new T.Scene(),camera=new T.PerspectiveCamera(40,1,.1,1500),controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.dampingFactor=.09;controls.maxPolarAngle=Math.PI*.485;controls.minDistance=5;controls.maxDistance=350;controls.autoRotateSpeed=.35;
 const sky=new T.HemisphereLight('#dce9f2','#64563d',2.5);scene.add(sky);const sun=new T.DirectionalLight('#fff0d0',3.5);sun.position.set(-25,55,25);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-65,right:65,top:65,bottom:-65,near:.5,far:250});sun.shadow.bias=-.001;scene.add(sun);
 let bundle:WorldBundle|null=null,settings:WorldSettings={hour:16,weather:'clear',paused:false,exposure:1,auto:false},selected:T.Object3D|null=null,arrange=false,inspect=false,dragging=false,dragMoved=false,elapsed=0,raf=0,last=0,lastDirty=0,walk=false;
 let roomEnvironment:T.WebGLRenderTarget|null=null;
 const layouts=new Map<string,ReturnType<typeof snapshot>>();let inspectStart:{object:T.Object3D;x:number;y:number}|null=null;
 const raycaster=new T.Raycaster(),pointer=new T.Vector2(),plane=new T.Plane(new T.Vector3(0,1,0),0),point=new T.Vector3(),offset=new T.Vector3(),keys=new Set<string>();
 const helper=new T.BoxHelper(new T.Object3D(),0xe2bd72);helper.visible=false;scene.add(helper);
 function invalidate(){dirty=true;if(simple)(renderer as LandscapeRenderer).invalidate()}
 function disposeGroup(g:T.Object3D){g.traverse(o=>{if(o instanceof T.Mesh||o instanceof T.Points||o instanceof T.Line){o.geometry.dispose();(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>m.dispose())}})}
 function load(next:WorldBundle){const keepView=bundle?.name===next.name;if(bundle){layouts.set(bundle.name,snapshot());scene.remove(bundle.group);disposeGroup(bundle.group);bundle.dispose?.()}bundle=next;const saved=layouts.get(next.name);if(saved)for(const o of next.movables||[]){const p=saved.find(p=>p.id===o.userData.id);if(p){o.position.x=p.x;o.position.z=p.z;o.rotation.y=p.rotation}}renderer.setPixelRatio(next.name==='云朵镇'?.85:Math.min(devicePixelRatio,1.6));resize();if((next.interior||next.lighting?.environment)&&!simple){if(!roomEnvironment){const environment=new RoomEnvironment(),pmrem=new T.PMREMGenerator(renderer as T.WebGLRenderer);roomEnvironment=pmrem.fromScene(environment,.04);environment.dispose();pmrem.dispose()}scene.environment=roomEnvironment.texture;scene.environmentIntensity=.55}else scene.environment=null;const shadowSize=(next.interior||next.lighting)&&window.innerWidth>=760?2048:1024;if(sun.shadow.mapSize.x!==shadowSize){sun.shadow.mapSize.set(shadowSize,shadowSize);sun.shadow.map?.dispose();sun.shadow.map=null}const radius=next.lighting?.shadowRadius??(next.interior?12:65);Object.assign(sun.shadow.camera,{left:-radius,right:radius,top:radius,bottom:-radius,near:.5,far:250});sun.shadow.camera.updateProjectionMatrix();sun.shadow.normalBias=next.interior?.025:0;scene.add(next.group);selected=null;helper.visible=false;onSelect(null);if(!keepView){camera.position.set(...next.camera);controls.target.set(...next.target);}controls.maxPolarAngle=next.name==='马特洪峰'?Math.PI*.68:Math.PI*.485;controls.minDistance=next.name==='马特洪峰'?12:next.name==='尘路'?.2:5;controls.maxDistance=next.name==='马特洪峰'?450:180;scene.background=new T.Color(next.background);controls.update();update(settings);invalidate()}
 function update(next:WorldSettings){settings=next;controls.autoRotate=next.auto&&!next.paused&&!walk;const daylight=Math.max(.13,Math.sin((next.hour-5)/15*Math.PI)),gold=next.hour>17&&next.hour<21;const overcast=next.weather==='cloud'||next.weather==='rain'||next.weather==='snow';sun.intensity=daylight*(overcast?1.4:3.4);sun.color.set(gold?'#ffc084':'#fff5df');sun.position.set(Math.cos((next.hour-6)/13*Math.PI)*50,12+daylight*70,30);sky.intensity=.38+daylight*2.3;sky.color.set('#dce9f2');sky.groundColor.set('#64563d');renderer.toneMappingExposure=next.exposure*(simple?.40+daylight*.68:1);if(bundle?.interior){sky.intensity=.28+daylight*.48;sun.intensity=.15+daylight*2.4;sun.position.set(-8,8+daylight*8,4);sun.color.set(gold?'#ffcb96':'#fff0d7');scene.environmentIntensity=.3+daylight*.4}if(bundle){const bg=new T.Color(bundle.background);bg.lerp(new T.Color('#101b34'),1-daylight);if(overcast)bg.lerp(new T.Color('#83969b'),.35);if(next.weather==='fog')bg.lerp(new T.Color('#b3c0bc'),.55);scene.background=bg;scene.fog=new T.FogExp2(bg,bundle.interior?0:next.weather==='fog'?.016:next.weather==='rain'?.0055:bundle.fog||.001);bundle.update?.(next);if(bundle.lighting){const l=bundle.lighting;sky.intensity=l.ambient;sky.color.set(l.skyColor);sky.groundColor.set(l.groundColor);sun.intensity=l.sun;sun.color.set(l.sunColor);sun.position.set(...l.sunPosition);scene.environmentIntensity=l.environment||0;scene.background=new T.Color(bundle.background);scene.fog=new T.FogExp2(bundle.background,bundle.fog||.01)}}invalidate()}
 let lookDrag:{x:number;y:number}|null=null;
 function walkingView(){return walk&&!!bundle?.walkBounds}
 function moveCamera(delta:T.Vector3){const old=camera.position.clone();camera.position.add(delta);if(walkingView()&&bundle?.walkBounds){camera.position.x=T.MathUtils.clamp(camera.position.x,bundle.walkBounds.minX,bundle.walkBounds.maxX);camera.position.y=bundle.walkBounds.eyeHeight}controls.target.add(camera.position.clone().sub(old))}
 function lookDown(e:PointerEvent){if(!walkingView()||e.button!==0)return;lookDrag={x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);canvas.focus()}
 function lookMove(e:PointerEvent){if(!lookDrag||!walkingView())return;const direction=controls.target.clone().sub(camera.position),spherical=new T.Spherical().setFromVector3(direction);spherical.theta-=(e.clientX-lookDrag.x)*.003;spherical.phi=T.MathUtils.clamp(spherical.phi+(e.clientY-lookDrag.y)*.003,.48,2.55);controls.target.copy(camera.position).add(new T.Vector3().setFromSpherical(spherical));camera.lookAt(controls.target);lookDrag={x:e.clientX,y:e.clientY}}
 function lookUp(){lookDrag=null}
 canvas.addEventListener('pointerdown',lookDown);canvas.addEventListener('pointermove',lookMove);canvas.addEventListener('pointerup',lookUp);canvas.addEventListener('pointercancel',lookUp);
 function aim(cameraPos:[number,number,number],target:[number,number,number]){camera.position.set(...cameraPos);controls.target.set(...target);controls.update();invalidate()}
 function eventRay(e:PointerEvent){const r=canvas.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);raycaster.setFromCamera(pointer,camera)}
 function select(o:T.Object3D|null){invalidate();selected=o;onSelect(o);helper.visible=!!o;if(o)helper.setFromObject(o)}
 function down(e:PointerEvent){if((!arrange&&!inspect)||!bundle||e.button!==0)return;eventRay(e);const hits=raycaster.intersectObjects(bundle.movables||[],true);let o:T.Object3D|null=hits[0]?.object||null;while(o&&!bundle.movables?.includes(o))o=o.parent;if(o){if(inspect&&!arrange){inspectStart={object:o,x:e.clientX,y:e.clientY};return}select(o);plane.constant=-(bundle.ground||0);if(raycaster.ray.intersectPlane(plane,point)){offset.copy(o.position).sub(point);dragging=true;dragMoved=false;controls.enabled=false;canvas.setPointerCapture(e.pointerId)}}else select(null)}
 function move(e:PointerEvent){if(inspectStart&&Math.hypot(e.clientX-inspectStart.x,e.clientY-inspectStart.y)>6)inspectStart=null;if(!dragging||!selected||!bundle)return;eventRay(e);if(raycaster.ray.intersectPlane(plane,point)){const b=bundle.bounds||10;if(bundle.floorBounds){selected.position.x=point.x+offset.x;selected.position.z=point.z+offset.z;constrainToFloor(selected,bundle.floorBounds)}else{selected.position.x=T.MathUtils.clamp(point.x+offset.x,-b,b);selected.position.z=T.MathUtils.clamp(point.z+offset.z,-b,b);}dragMoved=true;helper.setFromObject(selected);invalidate()}}
 function up(e?:PointerEvent){if(e?.type==='pointercancel')inspectStart=null;if(inspectStart){const o=inspectStart.object;inspectStart=null;o.userData.open=!o.userData.open;const door=o.getObjectByName('door');if(door){door.rotation.y=o.userData.open?-Math.PI*.55:0;door.position.x=o.userData.open?-.25:0}select(o);invalidate()}if(dragging){dragging=false;controls.enabled=true;if(dragMoved&&selected)onSelect(selected)}}
 function keydown(e:KeyboardEvent){if(['INPUT','TEXTAREA','SELECT','BUTTON'].includes((e.target as HTMLElement).tagName))return;keys.add(e.key.toLowerCase());if(e.key.toLowerCase()==='r'&&selected&&arrange){e.preventDefault();rotate()}if(walk&&['w','a','s','d'].includes(e.key.toLowerCase()))e.preventDefault()}
 function keyup(e:KeyboardEvent){keys.delete(e.key.toLowerCase())}
 function clearKeys(){keys.clear()}
 canvas.addEventListener('blur',clearKeys);document.addEventListener('visibilitychange',clearKeys);
 canvas.addEventListener('pointerdown',down,true);canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',up);canvas.addEventListener('pointercancel',up);host.addEventListener('keydown',keydown);host.addEventListener('keyup',keyup);
 const resize=()=>{if(!host.clientWidth||!host.clientHeight)return;renderer.setSize(host.clientWidth,host.clientHeight);camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();invalidate()};const observer=new ResizeObserver(resize);observer.observe(host);resize();const reduced=matchMedia('(prefers-reduced-motion: reduce)');
 function frame(now:number){raf=requestFrame(frame);const dt=Math.min(.05,(now-last)/1000||0);last=now;if(document.hidden||host.clientWidth===0)return;if(!settings.paused&&(!reduced.matches||bundle?.interactive)){elapsed+=dt;bundle?.tick?.(elapsed,settings);if(simple&&bundle?.tick&&now-lastDirty>180){invalidate();lastDirty=now}}if(walk&&!settings.paused&&keys.size){const forward=new T.Vector3().subVectors(controls.target,camera.position);forward.y=0;forward.normalize();const side=new T.Vector3().crossVectors(forward,new T.Vector3(0,1,0));const delta=new T.Vector3();if(keys.has('w'))delta.add(forward);if(keys.has('s'))delta.sub(forward);if(keys.has('d'))delta.add(side);if(keys.has('a'))delta.sub(side);delta.normalize().multiplyScalar(dt*(walkingView()?2.4:5));moveCamera(delta)}if(walkingView()){camera.lookAt(controls.target);dirty=true}else if(controls.update())dirty=true;if(bundle?.tick&&!settings.paused)dirty=true;if(selected&&helper.visible)helper.setFromObject(selected);if(dirty){renderer.render(scene,camera);dirty=false}}raf=requestFrame(frame);
 function snapshot(){return (bundle?.movables||[]).map(o=>({id:o.userData.id,x:o.position.x,z:o.position.z,rotation:o.rotation.y}))}
 function rotate(){if(selected){selected.rotation.y+=Math.PI/4;if(bundle?.floorBounds)constrainToFloor(selected,bundle.floorBounds);helper.setFromObject(selected);onSelect(selected);invalidate()}}
 function photograph(){renderer.render(scene,camera);onPhoto(canvas.toDataURL('image/jpeg',.92))}
 return {simple,load,update,aim,rotate,photograph,invalidate,getView(){return {position:camera.position.clone(),target:controls.target.clone()}},step(forward:number,side=0){if(settings.paused)return;const direction=controls.target.clone().sub(camera.position);direction.y=0;direction.normalize();const sideways=new T.Vector3().crossVectors(direction,new T.Vector3(0,1,0));const delta=direction.multiplyScalar(forward).add(sideways.multiplyScalar(side));moveCamera(delta)},progress(n:number){bundle?.progress?.(n);invalidate()},snapshot,setInspect(v:boolean){inspect=v},setArrange(v:boolean){invalidate();arrange=v;helper.visible=v&&!!selected;if(!v)up()},setWalk(v:boolean){if(walk===v)return;invalidate();walk=v;keys.clear();controls.autoRotate=false;controls.enabled=!(v&&bundle?.walkBounds);lookDrag=null;if(v){if(bundle?.walkBounds){camera.position.set(...bundle.camera);controls.target.set(...bundle.target)}else{camera.position.set(1,3.2,9);controls.target.set(0,3,-2)}controls.maxPolarAngle=Math.PI*.68}else if(bundle){camera.position.set(...bundle.camera);controls.target.set(...bundle.target);controls.maxPolarAngle=Math.PI*.485}},resetView(){if(bundle)aim(bundle.camera,bundle.target)},orbit(delta:number){const v=camera.position.clone().sub(controls.target).applyAxisAngle(new T.Vector3(0,1,0),delta);camera.position.copy(controls.target).add(v);invalidate()},dispose(){cancelFrame(raf);canvas.removeEventListener('pointerdown',lookDown);canvas.removeEventListener('pointermove',lookMove);canvas.removeEventListener('pointerup',lookUp);canvas.removeEventListener('pointercancel',lookUp);observer.disconnect();controls.dispose();canvas.removeEventListener('pointerdown',down,true);canvas.removeEventListener('pointermove',move);canvas.removeEventListener('pointerup',up);canvas.removeEventListener('pointercancel',up);host.removeEventListener('keydown',keydown);host.removeEventListener('keyup',keyup);canvas.removeEventListener('blur',clearKeys);document.removeEventListener('visibilitychange',clearKeys);disposeGroup(scene);bundle?.dispose?.();roomEnvironment?.dispose();renderer.dispose();canvas.remove()}};
}
