'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Camera,Pause,Play,RotateCcw,RotateCw,Home,Move,ArrowLeft,X,Download,Check,MapPin,Package,CarFront,Palette} from 'lucide-react';
import {useWorld} from './useWorld';
import {createTown,createDust,townPlots,buildingNames,destinations,type TownBuilding} from './focus-scenes';
import {formatTime} from '../MusicContext';
const phases=['选择这一轮的建筑','打好地基','立起支撑','砌筑墙体','搭建梁架','封好屋顶','装上门窗','刷上外墙','布置街景','点亮新家'];
export default function FocusWorld({road=false}:{road?:boolean}){
 const [minutes,setMinutes]=useState(25),[demo,setDemo]=useState(false),[remaining,setRemaining]=useState(1500),[running,setRunning]=useState(false),[started,setStarted]=useState(false),[done,setDone]=useState(false),[kind,setKind]=useState(2),[color,setColor]=useState('#738f98'),[buildings,setBuildings]=useState<TownBuilding[]>([]),[focusSeconds,setFocusSeconds]=useState(0),[previewCount,setPreviewCount]=useState(0),[arrange,setArrange]=useState(false),[night,setNight]=useState(road),[stop,setStop]=useState(0),[materials,setMaterials]=useState(0),[decor,setDecor]=useState<string[]>([]),[paint,setPaint]=useState('#b49a57'),[trailer,setTrailer]=useState(false),[workshop,setWorkshop]=useState(false),[view,setView]=useState(2),[distance,setDistance]=useState(0),[message,setMessage]=useState('');
 const total=demo?30:minutes*60,progress=started?1-remaining/total:0,deadline=useRef(0),finishRef=useRef<()=>void>(()=>{}),remainingRef=useRef(remaining);remainingRef.current=remaining;
 const settings=useMemo(()=>({hour:night?22:16,weather:'clear',paused:road?!running:false,exposure:1,auto:false}),[night,road,running]);
 const sceneKey=road?`road-${stop}-${paint}-${trailer}-${decor.join('-')}`:`town-${kind}-${color}-${buildings.length}`;
 const world=useWorld(()=>road?createDust(stop,decor,paint,trailer):createTown(buildings,kind,color),sceneKey,settings);
 function finish(){setRunning(false);setDone(true);setRemaining(0);if(demo)setPreviewCount(n=>n+1);else setFocusSeconds(n=>n+total);if(road){setDistance(d=>d+destinations[stop%3].distance);setMaterials(n=>n+12);setMessage('到站了。找到 12 份材料，可以给房车添点东西。')}else{const moved=world.engine.current?.snapshot()||[];setBuildings(old=>{const [x,z]=townPlots[old.length%townPlots.length];return [...old.map(b=>({...b,...moved.find(m=>m.id===b.id)})),{id:Date.now(),kind,color,x,z,rotation:0}]});setMessage('新建筑已经落成。试试拖动它，给小镇排个新布局。')}}finishRef.current=finish;
 useEffect(()=>{if(!running)return;deadline.current=Date.now()+remainingRef.current*1000;const tick=()=>{const left=Math.max(0,(deadline.current-Date.now())/1000);setRemaining(left);if(left===0)finishRef.current()};const timer=setInterval(tick,200);return()=>clearInterval(timer)},[running]);
 useEffect(()=>{if(!road)world.engine.current?.progress(done?0:progress)},[progress,done,road,sceneKey]);
 useEffect(()=>{world.engine.current?.setArrange(arrange)},[arrange,sceneKey]);
 useEffect(()=>{if(!road)return;const api=world.engine.current;if(view===0)api?.aim([2.37,1.87,-.74],[1.25,1.7,.12]);else if(view===1)api?.aim([1.6,1.78,.55],[1.35,1.6,-24]);else api?.aim([8.6,3.45,-8.3],[1.7,1.13,.2])},[view,road,sceneKey]);
 function chooseTime(n:number,isDemo=false){if(running)return;setMinutes(n);setDemo(isDemo);setRemaining(isDemo?30:n*60);setStarted(false);setDone(false);setMessage('')}
 function startPause(){if(done){setDone(false);setStarted(false);setRemaining(total);if(road)setStop(s=>(s+1)%3);setMessage('');return}if(running){setRemaining(Math.max(0,(deadline.current-Date.now())/1000));setRunning(false)}else{setStarted(true);setRunning(true)}}
 function cancel(){setRunning(false);setStarted(false);setDone(false);setRemaining(total);setMessage('这一轮已放下，随时可以重新开始。')}
 function buy(name:string,cost:number){if(decor.includes(name))return;if(materials<cost){setMessage('材料还差一点，到下一站再收集。');return}setMaterials(n=>n-cost);setDecor(d=>[...d,name]);setMessage(`已把${name}放进房车。`)}
 return <div className={`focus-world ${road?'dust-focus':'town-focus'}`}><div ref={world.host} className="focus-scene"/>{world.error&&<div className="world-error" role="alert">{world.error}</div>}<header className="focus-header"><div className="focus-wordmark">{road?<><b>DUST <em>ROAD</em></b><small>尘路 · 一起出发</small></>:<><b>云朵镇</b><small>把时间种进生活。</small></>}</div><div className="focus-stats">{road?<><span>{(distance+(!done?destinations[stop%3].distance*progress:0)).toFixed(1)} km</span><span><Package size={13}/>{materials}</span></>:<><span>{buildings.length+4} 栋</span><span>{buildings.length*2+8} 居民</span></>}<span>{Math.floor(focusSeconds/60)} 分钟{previewCount>0?` · ${previewCount} 次演示`:''}</span></div><div className="focus-tools"><button title="拍照" aria-label="拍照" onClick={()=>world.engine.current?.photograph()}><Camera size={17}/></button><button title="日夜切换" onClick={()=>setNight(n=>!n)}>{night?'日':'夜'}</button>{road&&<button onClick={()=>setWorkshop(w=>!w)}><CarFront size={16}/>房车</button>}</div></header>
 {world.fallback&&<small className="world-compat">简化渲染</small>}
 {road?<><nav className="road-views">{['看她','看路','车外'].map((n,i)=><button key={n} className={view===i?'chosen':''} onClick={()=>setView(i)}>{n}</button>)}</nav><div className="road-subtitle"><span>阿野</span>{done?'到啦，去看看这里有什么。':running?'慢慢开吧，你的那件事也慢慢来。':'要去哪里？挑一段时间，我陪你。'}</div></>:<aside className="town-build-options"><span>下一栋</span><div>{buildingNames.map((n,i)=><button key={n} disabled={started&&!done} className={kind===i?'chosen':''} onClick={()=>setKind(i)}>{n}</button>)}</div><label>外墙<input type="color" aria-label="建筑外墙颜色" disabled={started&&!done} value={color} onChange={e=>setColor(e.target.value)}/></label></aside>}
 <div className="focus-timer-card"><div className="focus-presets"><span>{road?`驶向 ${destinations[stop%3].name}`:`这一轮盖 ${buildingNames[kind]}`}</span><div>{[15,25,50].map(m=><button key={m} className={!demo&&minutes===m?'chosen':''} disabled={running} onClick={()=>chooseTime(m)}>{m}</button>)}<button className={demo?'chosen':''} disabled={running} onClick={()=>chooseTime(25,true)}>30秒体验</button></div></div><div className="focus-clock-row"><strong>{formatTime(remaining)}</strong><div><span>{demo?'演示模式 · 不计专注时长':done?'这一程完成':running?'专注进行中':started?'已暂停':'准备好了就出发'}</span><small>{road?`还剩 ${(destinations[stop%3].distance*(1-progress)).toFixed(1)} km`:done?'完成':phases[Math.min(9,Math.ceil(progress*9))]}</small></div></div><div className="focus-progress"><i style={{width:`${progress*100}%`}}/></div><div className="focus-actions"><button className="focus-start" onClick={startPause}>{done?<><Check size={17}/>{road?'准备下一站':'再造一栋'}</>:running?<><Pause size={17}/>暂停</>:<><Play size={17}/>{started?'继续':'开始专注'}</>}</button>{started&&!done&&<button onClick={cancel}>放下这一轮</button>}</div></div>
 <div className="world-orbit-tools"><button aria-label="向左旋转视角" onClick={()=>world.engine.current?.orbit(-Math.PI/4)}><RotateCcw size={16}/></button><button aria-label="向右旋转视角" onClick={()=>world.engine.current?.orbit(Math.PI/4)}><RotateCw size={16}/></button><button aria-label="恢复视角" onClick={()=>world.engine.current?.resetView()}><Home size={16}/></button>{!road&&<button className={arrange?'chosen':''} onClick={()=>setArrange(v=>!v)}><Move size={16}/>{arrange?'完成布局':'整理小镇'}</button>}</div>
 {arrange&&!road&&<div className="world-hint">拖动已有建筑 · R 旋转{world.selected&&<button onClick={()=>world.engine.current?.rotate()}>旋转 {world.selected.userData.name}</button>}</div>}
 {workshop&&road&&<aside className="road-workshop"><header><b>路上的小家</b><button aria-label="关闭房车设置" onClick={()=>setWorkshop(false)}><X size={17}/></button></header><p>{materials} 份材料</p><label>车身颜色<input type="color" value={paint} onChange={e=>setPaint(e.target.value)}/></label><button onClick={()=>setTrailer(t=>!t)}>{trailer?'卸下拖挂':'挂上拖挂'}</button>{[['绿植',4],['灯串',6],['地毯',8]].map(([n,c])=><button key={n} disabled={decor.includes(String(n))} onClick={()=>buy(String(n),Number(c))}>{n}<span>{decor.includes(String(n))?'已装饰':`${c} 材料`}</span></button>)}<small>跑完 30 秒体验，也能到站收集。</small></aside>}
 {message&&<div className="world-toast" role="status">{message}<button aria-label="关闭提示" onClick={()=>setMessage('')}>×</button></div>}
 <div className="focus-session-note">体验进度保留在当前窗口</div>{world.photo&&<div className="world-photo-modal" role="dialog" aria-label="场景照片"><button aria-label="关闭照片" onClick={()=>world.setPhoto(null)}><X/></button><img src={world.photo} alt={road?'尘路旅行照片':'云朵镇照片'}/><a href={world.photo} download={road?'CTY-Dust-Road.jpg':'CTY-Focus-Town.jpg'}><Download size={16}/>保存照片</a></div>}</div>;
}
