import * as T from 'three';
import {RoundedBoxGeometry} from 'three/addons/geometries/RoundedBoxGeometry.js';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
export function solid(parent:T.Object3D,geometry:T.BufferGeometry,material:T.Material,x=0,y=0,z=0){const mesh=new T.Mesh(geometry,material);mesh.position.set(x,y,z);mesh.castShadow=!(material instanceof T.MeshStandardMaterial&&material.transparent&&material.opacity<.5);mesh.receiveShadow=true;parent.add(mesh);return mesh}
export function block(parent:T.Object3D,w:number,h:number,d:number,material:T.Material,x=0,y=0,z=0,r=0){return solid(parent,r?new RoundedBoxGeometry(w,h,d,2,r):new T.BoxGeometry(w,h,d),material,x,y,z)}
export function sphere(parent:T.Object3D,r:number,material:T.Material,x=0,y=0,z=0){return solid(parent,new T.SphereGeometry(r,20,14),material,x,y,z)}
export function rod(parent:T.Object3D,a:T.Vector3,b:T.Vector3,r:number,mat:T.Material,r2=r){const d=b.clone().sub(a),m=solid(parent,new T.CylinderGeometry(r2,r,d.length(),10),mat);m.position.copy(a).add(b).multiplyScalar(.5);m.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),d.normalize());return m}
export function pbr(name:string,color:string,repeat:[number,number]=[1,1],roughness=.8){const textures:T.Texture[]=[],loader=new T.TextureLoader();const take=(suffix:string)=>{const t=loader.load(`/works/worlds/materials/${name}_${suffix}`);t.wrapS=t.wrapT=T.RepeatWrapping;t.repeat.set(...repeat);t.anisotropy=8;textures.push(t);return t};const map=take('color_512.jpg');map.colorSpace=T.SRGBColorSpace;const mat=new T.MeshStandardMaterial({color,map,normalMap:take('normal_gl_512.png'),roughnessMap:take('roughness_512.jpg'),roughness,normalScale:new T.Vector2(.6,.6)});return {mat,dispose(){textures.forEach(t=>t.dispose())}}}
export function glowTexture(){const canvas=document.createElement('canvas');canvas.width=canvas.height=128;const ctx=canvas.getContext('2d')!,gradient=ctx.createRadialGradient(64,64,1,64,64,64);gradient.addColorStop(0,'rgba(255,255,255,1)');gradient.addColorStop(.1,'rgba(255,245,211,.8)');gradient.addColorStop(.28,'rgba(255,229,181,.16)');gradient.addColorStop(1,'rgba(255,229,181,0)');ctx.fillStyle=gradient;ctx.fillRect(0,0,128,128);return new T.CanvasTexture(canvas)}
export function glow(parent:T.Object3D,texture:T.Texture,x:number,y:number,z:number,size:number,color='#ffdda0',opacity=.55){const s=new T.Sprite(new T.SpriteMaterial({map:texture,color,transparent:true,opacity,depthWrite:false,blending:T.AdditiveBlending}));s.position.set(x,y,z);s.scale.setScalar(size);parent.add(s);return s}
export function sign(parent:T.Object3D,text:string,w:number,h:number,bg:string,fg:string,x:number,y:number,z:number){const c=document.createElement('canvas');c.width=1024;c.height=Math.round(1024*h/w);const ctx=c.getContext('2d')!;ctx.fillStyle=bg;ctx.fillRect(0,0,c.width,c.height);ctx.strokeStyle=fg;ctx.lineWidth=2;ctx.strokeRect(12,12,c.width-24,c.height-24);ctx.fillStyle=fg;ctx.font=`${Math.min(c.height*.52,80)}px Georgia,serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,512,c.height*.52,950);const texture=new T.CanvasTexture(c);texture.colorSpace=T.SRGBColorSpace;const mesh=solid(parent,new T.PlaneGeometry(w,h),new T.MeshStandardMaterial({map:texture,roughness:.65,emissive:fg,emissiveIntensity:.13,emissiveMap:texture}),x,y,z);return {mesh,texture}}
/** Bake static detail by material: richly furnished scenes without thousands of draw calls. */
export function batchStatic(root:T.Group){root.updateMatrixWorld(true);const inverse=root.matrixWorld.clone().invert(),batches=new Map<T.Material,T.BufferGeometry[]>(),remove:T.Mesh[]=[];root.traverse(o=>{if(o instanceof T.Mesh&&!Array.isArray(o.material)&&!o.userData.dynamic){let p:T.Object3D|null=o;while(p&&p!==root){if(p.userData.dynamic)return;p=p.parent}const geometry=o.geometry.clone().applyMatrix4(new T.Matrix4().multiplyMatrices(inverse,o.matrixWorld));const bucket=batches.get(o.material)||[];bucket.push(geometry.index?geometry.toNonIndexed():geometry);batches.set(o.material,bucket);remove.push(o)}});for(const m of remove){m.removeFromParent();m.geometry.dispose()}for(const [mat,geometries] of batches){const geometry=mergeGeometries(geometries,false);geometries.forEach(g=>g.dispose());if(geometry)solid(root,geometry,mat)} }
