'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Camera,Download,X,Settings2,RotateCw,Home,Move,Eye,Volume2,VolumeX,Play,Pause,Footprints} from 'lucide-react';
import {createMountain,createRoom,createMicro,mountainViews,roomNames,roomNotes,microNames,microPlaces} from './exhibit-scenes';
import {useWorld} from './useWorld';
import {useMusic} from '../MusicContext';
export default function WorldExhibit({kind}:{kind:'mountain'|'room'|'micro'}){
 const [index,setIndex]=useState(0),[hour,setHour]=useState(kind==='mountain'?9.5:16.5),[weather,setWeather]=useState(kind==='micro'?'snow':'clear'),[exposure,setExposure]=useState(1),[snow,setSnow]=useState(.65),[cloud,setCloud]=useState(.25),[auto,setAuto]=useState(false),[paused,setPaused]=useState(false),[panel,setPanel]=useState(false),[hidden,setHidden]=useState(false),[labels,setLabels]=useState(true),[arrange,setArrange]=useState(false),[walk,setWalk]=useState(false),[variant,setVariant]=useState(0),[notice,setNotice]=useState('');const music=useMusic();
 const settings=useMemo(()=>({hour,weather,paused,exposure,auto}),[hour,weather,paused,exposure,auto]);
 const key=kind==='mountain'?`mountain-${snow}-${cloud}`:`${kind}-${index}-${variant}`;
 const world=useWorld(simple=>kind==='mountain'?createMountain(simple,snow,cloud):kind==='room'?createRoom(index):createMicro(index),key,settings);
 const name=kind==='mountain'?'马特洪峰':kind==='room'?roomNames[index]:microNames[index];
 useEffect(()=>{if(kind==='mountain'){const v=mountainViews[index];world.engine.current?.aim([...v.camera],[...v.target])}},[index,kind]);
 useEffect(()=>{world.engine.current?.setArrange(arrange);world.engine.current?.setInspect(kind==='micro');world.engine.current?.setWalk(walk)},[arrange,walk,key,kind]);
 function select(i:number){setIndex(i);setArrange(false);setWalk(false);if(kind==='mountain')setHour(mountainViews[i].hour);if(kind==='micro'){setWeather(i===0||i===4?'snow':'clear');setHour(i===0?16.5:15)}setNotice('')}
 function reset(){setWalk(false);setArrange(false);world.engine.current?.resetView()}
 function sound(){if(music.playing)music.pause();else music.select(kind==='room'?'harbor':'moon')}
 return <div className={`world-exhibit exhibit-${kind} world-weather-${weather} ${hidden?'world-ui-hidden':''} ${paused?'world-paused':''}`} tabIndex={0} onKeyDown={e=>{if((e.target as HTMLElement).closest('input,select,button'))return;const k=e.key.toLowerCase();if(k==='h')setHidden(v=>!v);if(k==='r'&&!arrange)reset();if(e.code==='Space'){e.preventDefault();setPaused(v=>!v)}if(kind==='room'&&/^[1-5]$/.test(k))select(Number(k)-1)}}>
 <div ref={world.host} className="exhibit-scene"/>{weather==='rain'&&<div className="world-rain" aria-hidden="true"/>}{weather==='snow'&&<div className="world-snow" aria-hidden="true">{Array.from({length:55},(_,i)=><i key={i} style={{left:`${i*29.3%100}%`,animationDelay:`${-i*.37}s`,animationDuration:`${6+i%5}s`}}/>)}</div>}
 {world.error&&<div className="world-error" role="alert">{world.error}</div>}
 <header className="exhibit-header"><div>{kind==='mountain'?<><small>THE ALPINE COLLECTION</small><h2>Matterhorn <span>马特洪峰</span></h2><p>4,478 m · 瑞士 / 意大利</p></>:kind==='room'?<><b className="still-wordmark">STILLROOM <span>隅间</span></b><small>FIVE ROOMS, FIVE LIVES.</small></>:<><small>SMALL WORLDS / CTY STUDIO</small><h2>三寸人间<span>六景</span></h2></>}</div><div className="exhibit-actions"><button aria-label="保存场景照片" onClick={()=>world.engine.current?.photograph()}><Camera size={16}/></button><button aria-label="显示设置" onClick={()=>setPanel(p=>!p)}><Settings2 size={16}/></button><button aria-label="恢复视角" onClick={reset}><Home size={16}/></button>{kind==='room'&&<button className={walk?'chosen':''} onClick={()=>{setWalk(v=>!v);setArrange(false)}}><Footprints size={16}/>{walk?'环绕视角':'走进房间'}</button>}<button aria-label={music.playing?'暂停氛围音乐':'播放氛围音乐'} onClick={sound}>{music.playing?<Volume2 size={16}/>:<VolumeX size={16}/>}</button><button onClick={()=>setHidden(true)}><Eye size={16}/>隐藏</button></div></header>
 {world.fallback&&<small className="world-compat">简化渲染 · 可旋转与拍照</small>}
 {kind==='mountain'&&labels&&<div className="mountain-caption"><span>▲</span> MATTERHORN <small>4,478 m</small></div>}
 {panel&&<aside className="exhibit-settings"><header><b>{kind==='room'?'房间光线':'光线与天气'}</b><button aria-label="收起设置" onClick={()=>setPanel(false)}><X size={15}/></button></header><label>当地时刻 <span>{String(Math.floor(hour)).padStart(2,'0')}:{String(Math.floor(hour%1*60)).padStart(2,'0')}</span><input aria-label="当地时刻" type="range" min="0" max="24" step=".1" value={hour} onChange={e=>setHour(+e.target.value)}/></label><div className="exhibit-time-presets">{[[7,'清晨'],[12,'正午'],[18.5,'日落'],[22,'深夜']].map(([h,n])=><button key={n} onClick={()=>setHour(Number(h))}>{n}</button>)}</div>{kind!=='room'&&<label>天气<select value={weather} onChange={e=>setWeather(e.target.value)}><option value="clear">晴天</option><option value="cloud">阴天</option><option value="rain">下雨</option><option value="snow">落雪</option><option value="fog">薄雾</option></select></label>}{kind==='mountain'&&<><label>积雪量<input aria-label="积雪量" type="range" min="0" max="1" step=".05" value={snow} onChange={e=>setSnow(+e.target.value)}/></label><label>山间云量<input aria-label="云量" type="range" min="0" max="1" step=".05" value={cloud} onChange={e=>setCloud(+e.target.value)}/></label><label className="world-checkbox"><input type="checkbox" checked={labels} onChange={e=>setLabels(e.target.checked)}/>山峰标记</label></>}<label>{kind==='room'?'光线亮度':'曝光'} <span>{exposure.toFixed(1)}</span><input aria-label="曝光" type="range" min=".4" max="1.6" step=".05" value={exposure} onChange={e=>setExposure(+e.target.value)}/></label><button className={auto?'chosen':''} onClick={()=>setAuto(a=>!a)}><RotateCw size={14}/>自动环绕</button><button onClick={()=>setPaused(p=>!p)}>{paused?<Play size={14}/>:<Pause size={14}/>} {paused?'继续世界':'暂停世界'}</button>{kind==='mountain'&&<small>程序化山体意向，非测绘模型。</small>}</aside>}
 <footer className="exhibit-footer"><div className="exhibit-scene-copy"><small>{kind==='room'?`ROOM / 0${index+1}`:kind==='micro'?microPlaces[index]:'CHOOSE YOUR PERSPECTIVE'}</small><h3>{kind==='mountain'?mountainViews[index].name:name}</h3>{kind==='room'&&<p>{roomNotes[index]}</p>}{kind==='micro'&&<p>{index===0?'点一下店铺，可以开关店门。':'调整天气与时间，看小人走过街道。'}</p>}</div><nav className="exhibit-scene-tabs">{(kind==='mountain'?mountainViews.map(v=>v.name):kind==='room'?roomNames:microNames).map((n,i)=><button key={n} className={index===i?'chosen':''} onClick={()=>select(i)}><small>0{i+1}</small>{n}</button>)}</nav><div className="exhibit-footer-tools">{kind==='room'?<><button className={arrange?'chosen':''} onClick={()=>{setArrange(a=>!a);setWalk(false)}}><Move size={16}/>{arrange?'完成布置':'布置房间'}</button>{arrange&&<button onClick={()=>world.engine.current?.rotate()} disabled={!world.selected}>旋转摆件</button>}</>:<button onClick={()=>setPaused(p=>!p)}>{paused?<Play size={16}/>:<Pause size={16}/>}</button>}<small>{walk?'W A S D 移动 · 拖动看向别处':arrange?'拖动床、桌椅或摆件 · R 旋转':kind==='micro'?'拖动旋转 · 滚轮缩放 · H 隐藏 · 空格暂停':'拖动旋转 · 右键平移 · 滚轮缩放'}</small></div></footer>
 {kind==='room'&&arrange&&world.selected&&<div className="world-selection">正在移动：{world.selected.userData.name}</div>}{kind==='micro'&&world.selected&&<div className="world-selection">{world.selected.userData.name} · {world.selected.userData.open?'门开了，欢迎进来坐坐。':'店门轻轻合上。'}</div>}
 {hidden&&<button className="show-world-ui" onClick={()=>setHidden(false)}><Eye size={15}/>显示界面 · H</button>}
 {world.photo&&<div className="world-photo-modal" role="dialog" aria-label="场景照片"><button aria-label="关闭照片" onClick={()=>world.setPhoto(null)}><X/></button><img src={world.photo} alt={name+' 场景照片'}/><a href={world.photo} download={`CTY-${kind}.jpg`}><Download size={16}/>保存照片</a></div>}</div>;
}
