'use client';
import {searchApps} from '@/lib/app-search';
import {useEffect,useRef,useState} from 'react';
import {Search,CornerDownLeft,ChevronLeft,ChevronRight,Moon} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {apps,AppId} from '@/lib/desktop-apps';
import Icon from './DesktopIcon';
export function QuickSearch({shown,onChange,open,displayName}:{shown:boolean;onChange:(shown:boolean)=>void;open:(id:AppId)=>void;displayName:(id:AppId)=>string}){
 const [query,setQuery]=useState(''),[selected,setSelected]=useState(0);const list=useRef<HTMLDivElement>(null);
 const popular:AppId[]=['works','zp-rooms','zp-focus','zp-gallery','music','minecraft','zp-arcade','terminal'];
 const hits=(query.trim()?searchApps(query,apps,displayName):popular.map(id=>apps.find(a=>a.id===id)!)).slice(0,16);
 useEffect(()=>{if(shown){setQuery('');setSelected(0)}},[shown]);useEffect(()=>{list.current?.querySelector('[aria-selected="true"]')?.scrollIntoView({block:'nearest'})},[selected]);
 function choose(id:AppId){onChange(false);open(id)}
 return <Dialog open={shown} onOpenChange={onChange}><DialogContent className="quick-search-dialog" showCloseButton={false}><DialogTitle className="sr-only">搜索桌面作品</DialogTitle><DialogDescription className="sr-only">搜索作品集中的应用，使用上下键选择，回车打开。</DialogDescription><label className="quick-search-field"><Search size={21}/><input autoFocus value={query} onChange={e=>{setQuery(e.target.value);setSelected(0)}} onKeyDown={e=>{if(e.key==='ArrowDown'){e.preventDefault();setSelected(s=>Math.max(0,Math.min(hits.length-1,s+1)))}if(e.key==='ArrowUp'){e.preventDefault();setSelected(s=>Math.max(0,s-1))}if(e.key==='Enter'&&hits[selected]){e.preventDefault();choose(hits[selected].id)}}} aria-label="搜索桌面作品" aria-controls="quick-search-results" aria-activedescendant={hits[selected]?'result-'+hits[selected].id:undefined} placeholder="找作品、房间、游戏…"/><button onClick={()=>onChange(false)}>ESC</button></label><div className="quick-search-heading">{query?'搜索结果':'常用入口'}<span>{hits.length} 项</span></div><div className="quick-search-results" ref={list} role="listbox" id="quick-search-results" aria-label="搜索结果">{hits.map((a,i)=><button id={'result-'+a.id} role="option" aria-selected={selected===i} key={a.id} onMouseEnter={()=>setSelected(i)} onClick={()=>choose(a.id)}><Icon n={a.icon} small/><span><b>{displayName(a.id)}</b><small>{a.category}</small></span><CornerDownLeft size={16}/></button>)}{!hits.length&&<p className="quick-search-empty">没有找到。可以试试“音乐”“专注”或“3D”。</p>}</div><footer>↑ ↓ 选择 <span>Enter 打开</span><span>Ctrl / ⌘ K 搜索</span></footer></DialogContent></Dialog>
}
export function BootSequence(){const [show,setShow]=useState(false);useEffect(()=>{try{if(sessionStorage.getItem('db-os-boot-v4')||window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;sessionStorage.setItem('db-os-boot-v4','1')}catch{}setShow(true);const timer=setTimeout(()=>setShow(false),1500);return()=>clearTimeout(timer)},[]);if(!show)return null;return <button className="desktop-boot" onClick={()=>setShow(false)} aria-label="跳过开机动画"><div><Icon n={0}/><b>CTY—OS</b><span>CTY STUDIO · 5.0</span><div className="boot-meter"><i/></div><small>作品就绪，欢迎回来。</small><em>点击跳过</em></div></button>}
export function Calendar({onClose}:{onClose:()=>void}){const now=new Date(),[offset,setOffset]=useState(0),root=useRef<HTMLDivElement>(null),date=new Date(now.getFullYear(),now.getMonth()+offset,1),first=(date.getDay()+6)%7,days=new Date(date.getFullYear(),date.getMonth()+1,0).getDate();useEffect(()=>{const outside=(e:PointerEvent)=>{if(!root.current?.contains(e.target as Node)&&!(e.target as Element).closest?.('[data-calendar-toggle]'))onClose()};document.addEventListener('pointerdown',outside);return()=>document.removeEventListener('pointerdown',outside)},[onClose]);return <div ref={root} className="desktop-calendar" role="dialog" aria-label="日历"><header><div><Moon size={20}/><span>{now.toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'})}</span></div><p>慢慢来，也记得留一点时间给自己。</p></header><div className="calendar-month"><button aria-label="上个月" onClick={()=>setOffset(o=>o-1)}><ChevronLeft size={17}/></button><b>{date.getFullYear()} 年 {date.getMonth()+1} 月</b><button aria-label="下个月" onClick={()=>setOffset(o=>o+1)}><ChevronRight size={17}/></button></div><div className="calendar-grid">{['一','二','三','四','五','六','日'].map(w=><small key={w}>{w}</small>)}{Array.from({length:first},(_,i)=><span key={'empty'+i}/>)}{Array.from({length:days},(_,i)=><span key={i} className={offset===0&&i+1===now.getDate()?'today':''}>{i+1}</span>)}</div><button className="calendar-today" onClick={()=>setOffset(0)}>回到今天</button></div>}
export function DesktopStars(){return <div className="desktop-stars" aria-hidden="true">{Array.from({length:22},(_,i)=><i key={i} style={{left:`${9+(i*31)%86}%`,top:`${4+(i*17)%71}%`,animationDelay:`${-(i%8)}s`,animationDuration:`${5+i%5}s`}}/>)}</div>}
