'use client';
import {useEffect,useRef,useState} from 'react';
import {Camera,SlidersHorizontal,RotateCw,Download,X,ChevronLeft,ChevronRight} from 'lucide-react';
import {buildFaroe,faroeViews,type FaroeOptions} from './faroe-scene';
export default function Faroe(){const host=useRef<HTMLDivElement>(null),labels=useRef<HTMLDivElement>(null),api=useRef<ReturnType<typeof buildFaroe>|null>(null),[fallback,setFallback]=useState(false),[error,setError]=useState(''),[panel,setPanel]=useState(true),[view,setView]=useState('mulafossur'),[flash,setFlash]=useState(false),[photos,setPhotos]=useState<string[]>([]),[photo,setPhoto]=useState<string|null>(null),[options,setOptions]=useState<FaroeOptions>({hour:16,season:'summer',weather:'clear',sea:.45,exposure:1,film:'portra',auto:false,labels:true});
 useEffect(()=>{if(!host.current||!labels.current)return;try{api.current=buildFaroe(host.current,labels.current,setFallback)}catch(e){setError('场景未能初始化，请关闭其他大型 3D 页面后再试。')}return()=>{api.current?.dispose();api.current=null}},[]);
 useEffect(()=>{api.current?.update(options)},[options]);useEffect(()=>{api.current?.view(view)},[view]);
 function update<K extends keyof FaroeOptions>(key:K,value:FaroeOptions[K]){setOptions(o=>({...o,[key]:value}))}
 function shoot(){try{const src=api.current?.capture();if(src){setPhotos(old=>[src,...old].slice(0,8));setFlash(true);setTimeout(()=>setFlash(false),160)}}catch{setError('这次快门没有保存成功，请再试一次。')}}
 return <div className="faroe-app"><div ref={host} className="faroe-scene"/><div ref={labels} className="faroe-labels"/><header className="faroe-title"><span>THE NORTH ATLANTIC COLLECTION</span><h2>Føroyar<span>法罗群岛</span></h2><p>岛屿、风，和海的声音。</p></header><div className="faroe-top-controls"><button onClick={()=>setPanel(v=>!v)} aria-expanded={panel}><SlidersHorizontal size={16}/>摄影设置</button><button className={options.auto?'chosen':''} onClick={()=>update('auto',!options.auto)}><RotateCw size={16}/>环绕</button></div>{fallback&&<div className="faroe-render-note">简化渲染 · 仍可旋转与拍照</div>}{error&&<div className="faroe-error" role="alert">{error}<button onClick={()=>setError('')}>×</button></div>}
 {panel&&<aside className="faroe-settings"><header><b>光线与天气</b><button onClick={()=>setPanel(false)} aria-label="收起摄影设置">×</button></header><label>当地时刻 <span>{String(Math.floor(options.hour)).padStart(2,'0')}:{String(Math.floor(options.hour%1*60)).padStart(2,'0')}</span><input type="range" min="5" max="23" step=".1" value={options.hour} onChange={e=>update('hour',+e.target.value)}/></label><div className="faroe-chips">{[[7,'清晨'],[12,'正午'],[18.8,'黄金'],[22,'午夜蓝']].map(([hour,title])=><button key={title} onClick={()=>update('hour',+hour)}>{title}</button>)}</div><label>季节<select value={options.season} onChange={e=>update('season',e.target.value)}><option value="summer">仲夏 · 草木深绿</option><option value="autumn">深秋 · 荒草金黄</option><option value="winter">隆冬 · 山头覆雪</option></select></label><label>天气<select value={options.weather} onChange={e=>update('weather',e.target.value)}><option value="clear">晴天</option><option value="typical">典型海岛天气</option><option value="lowcloud">低云</option><option value="fog">海雾</option></select></label><label>海况 <span>{options.sea<.3?'平静':options.sea>.75?'起风':'微波'}</span><input type="range" min="0" max="1" step=".01" value={options.sea} onChange={e=>update('sea',+e.target.value)}/></label><hr/><label>胶片<select value={options.film} onChange={e=>update('film',e.target.value)}><option value="portra">暖调胶片</option><option value="chrome">鲜明正片</option><option value="mono">银盐黑白</option></select></label><label>曝光 <span>{options.exposure.toFixed(1)}</span><input type="range" min=".55" max="1.6" step=".05" value={options.exposure} onChange={e=>update('exposure',+e.target.value)}/></label><label className="faroe-checkbox"><input type="checkbox" checked={options.labels} onChange={e=>update('labels',e.target.checked)}/>显示地名</label><small>地理意向的程序化场景，非测绘模型。</small></aside>}
 {photos.length>0&&<aside className="faroe-filmstrip"><span>本次底片 / {photos.length}</span>{photos.map((src,i)=><button key={src.slice(-80)+i} onClick={()=>setPhoto(src)} aria-label={`查看底片 ${i+1}`}><img src={src} alt={`法罗底片 ${i+1}`}/></button>)}</aside>}
 <footer className="faroe-viewfinder"><div><span>CHOOSE YOUR PERSPECTIVE</span><nav>{faroeViews.map((v,i)=><button className={view===v.id?'chosen':''} key={v.id} onClick={()=>setView(v.id)}><small>0{i+1}</small><b>{v.name}</b><span>{v.sub}</span></button>)}</nav><small>拖动旋转 · 右键平移 · 滚轮 / 双指缩放</small></div><button className="faroe-shutter" aria-label="拍一张胶片" onClick={shoot}><Camera size={24}/></button></footer>{flash&&<div className="faroe-flash"/>}{photo&&<div className="faroe-photo-modal" role="dialog" aria-label="胶片预览"><button className="faroe-photo-close" onClick={()=>setPhoto(null)} aria-label="关闭胶片预览"><X/></button><img src={photo} alt="法罗群岛胶片"/><a download="CTY-Faroe.jpg" href={photo}><Download size={16}/>保存底片</a></div>}</div>;
}
