import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {LandscapeRenderer} from './LandscapeRenderer';
export type FaroeOptions={hour:number;season:string;weather:string;sea:number;exposure:number;film:string;auto:boolean;labels:boolean};
export const faroeViews=[{id:'mulafossur',name:'Múlafossur',sub:'瀑布与村庄',camera:[62,74,121],target:[-36,20,3]},{id:'drangarnir',name:'Drangarnir',sub:'海上的石门',camera:[117,34,89],target:[67,10,17]},{id:'tindholmur',name:'Tindhólmur',sub:'五座尖峰',camera:[169,61,3],target:[113,25,-62]},{id:'islands',name:'Føroyar',sub:'群岛全景',camera:[146,155,200],target:[10,12,-25]}];
const smooth=(a:number,b:number,x:number)=>{const t=Math.max(0,Math.min(1,(x-a)/(b-a)));return t*t*(3-2*t)};
export function buildFaroe(host:HTMLDivElement,labelHost:HTMLDivElement,onFallback:(fallback:boolean)=>void){
 let renderer:THREE.WebGLRenderer|LandscapeRenderer;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,preserveDrawingBuffer:true,powerPreference:'high-performance'})}catch{renderer=new LandscapeRenderer()}const fallback=renderer instanceof LandscapeRenderer;onFallback(fallback);renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;host.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-label','法罗群岛三维场景，可拖动旋转、滚轮缩放');
 const scene=new THREE.Scene();scene.background=new THREE.Color('#a8bfca');scene.fog=new THREE.FogExp2('#afc4c9',.0027);const camera=new THREE.PerspectiveCamera(42,1,.5,1700);camera.position.set(62,74,121);const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(-36,20,3);controls.enableDamping=true;controls.dampingFactor=.065;controls.minDistance=32;controls.maxDistance=590;controls.maxPolarAngle=Math.PI*.487;controls.minPolarAngle=.18;controls.autoRotateSpeed=.25;const ambient=new THREE.HemisphereLight('#d5e6ed','#686e52',2.5);scene.add(ambient);const sun=new THREE.DirectionalLight('#ffefd1',3);sun.position.set(-90,140,70);scene.add(sun);
 let seed=71;const rand=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};
 const grass=new THREE.Color('#78875a'),rock=new THREE.Color('#465357'),terrains:{geo:THREE.BufferGeometry;slopes:number[];heights:number[]}[]=[];const mats:THREE.Material[]=[];
 function material(color:string,extra:THREE.MeshStandardMaterialParameters={}){const m=new THREE.MeshStandardMaterial({color,roughness:.93,...extra});mats.push(m);return m}
 function terrain(cx:number,cz:number,rx:number,rz:number,kind:number){const height=(x:number,z:number)=>{const xx=(x-cx)/rx,zz=(z-cz)/rz,a=Math.atan2(zz,xx),r=Math.sqrt(xx*xx+zz*zz)/(1+.06*Math.sin(a*5)+.024*Math.cos(a*9));let peaks=kind===1?Math.max(0,1-Math.abs(zz)*1.3)*(31+29*Math.pow(Math.max(0,Math.cos(xx*14)),3)):(42*Math.exp(-((xx+.25)**2/.17+(zz+.25)**2/.16))+35*Math.exp(-((xx-.4)**2/.10+(zz+.38)**2/.10)));const ridge=(3*Math.sin(x*.16+z*.14)+2*Math.cos(x*.23-z*.12));return (19+peaks+ridge)*(1-smooth(.91,1.035,r))-5};const n=fallback?42:85,m=fallback?28:55,geo=new THREE.PlaneGeometry(rx*2.14,rz*2.14,n,m);geo.rotateX(-Math.PI/2);const pos=geo.getAttribute('position');const colors=new Float32Array(pos.count*3),slopes:number[]=[],heights:number[]=[];for(let i=0;i<pos.count;i++){const x=pos.getX(i)+cx,z=pos.getZ(i)+cz,y=height(x,z);pos.setXYZ(i,x,y,z);const dx=(height(x+1,z)-height(x-1,z))/2,dz=(height(x,z+1)-height(x,z-1))/2,slope=Math.hypot(dx,dz);slopes.push(slope);heights.push(y);const c=(slope>1.2||y<4?rock:grass).clone();c.multiplyScalar(.8+rand()*.3+Math.sin(y*1.5)*.08);c.toArray(colors,i*3)}geo.setAttribute('color',new THREE.BufferAttribute(colors,3));geo.computeVertexNormals();const mesh=new THREE.Mesh(geo,material('#ffffff',{vertexColors:true,flatShading:fallback}));scene.add(mesh);terrains.push({geo,slopes,heights});return height}
 const ground=terrain(-45,-10,80,49,0);terrain(113,-66,49,18,1);terrain(-150,-100,62,30,0);terrain(45,-180,83,27,0);terrain(206,-153,57,26,1);
 const seaGeo=new THREE.PlaneGeometry(1500,1500,fallback?28:100,fallback?28:100);seaGeo.rotateX(-Math.PI/2);const seaMat=material('#294d59',{roughness:.27,metalness:.20});const sea=new THREE.Mesh(seaGeo,seaMat);sea.position.y=-.4;scene.add(sea);
 const archMat=material('#424c4b',{flatShading:true});const arch=new THREE.Mesh(new THREE.TorusGeometry(12,4.6,7,22,Math.PI),archMat);arch.position.set(70,4,18);arch.rotation.y=-.4;scene.add(arch);for(const x of [-1,1]){const foot=new THREE.Mesh(new THREE.ConeGeometry(6.3,16,7),archMat);foot.position.set(70+x*11,6,18+x*4);foot.rotation.z=x*.1;scene.add(foot)}
 const wallMats=['#e5e3cf','#b95d46','#283c43','#bfbd9b'].map(c=>material(c));const roofMat=material('#28362f');const windowMat=material('#c1d7c9',{emissive:'#efc783',emissiveIntensity:.16});
 function house(x:number,z:number,i:number){const y=ground(x,z);if(y<11)return;const group=new THREE.Group();const w=3+rand()*2,d=3+rand()*1.5,h=2.4+rand();const walls=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),wallMats[i%4]);walls.position.y=h/2;group.add(walls);const verts=new Float32Array([-w*.57,0,-d*.57,w*.57,0,-d*.57,0,h*.6,-d*.57,-w*.57,0,d*.57,w*.57,0,d*.57,0,h*.6,d*.57]);const roof=new THREE.BufferGeometry();roof.setAttribute('position',new THREE.BufferAttribute(verts,3));roof.setIndex([0,2,1,3,4,5,0,3,5,0,5,2,1,2,5,1,5,4,0,1,4,0,4,3]);roof.computeVertexNormals();const mesh=new THREE.Mesh(roof,roofMat);mesh.position.y=h;group.add(mesh);for(let j=-1;j<=1;j+=2){const win=new THREE.Mesh(new THREE.PlaneGeometry(.65,.82),windowMat);win.position.set(j*w*.25,h*.58,d*.501);group.add(win)}group.position.set(x,y-.1,z);group.rotation.y=(i%3-1)*.13;scene.add(group)}
 for(let i=0;i<22;i++){const x=-68+(i%7)*7+rand()*2,z=3+Math.floor(i/7)*6;house(x,z,i)}
 // Small roads follow the plateau rather than slicing through the hills.
 function ribbon(points:THREE.Vector3[],width:number,mat:THREE.Material){const curve=new THREE.CatmullRomCurve3(points),pts=curve.getPoints(70),positions:number[]=[],indices:number[]=[];pts.forEach((p,i)=>{positions.push(p.x-width/2,p.y,p.z,p.x+width/2,p.y,p.z);if(i<pts.length-1){const a=i*2;indices.push(a,a+1,a+2,a+1,a+3,a+2)}});const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));geo.setIndex(indices);geo.computeVertexNormals();const mesh=new THREE.Mesh(geo,mat);scene.add(mesh);return mesh}
 const roadMat=material('#aeaf99',{side:THREE.DoubleSide});const roadpoints=[];for(let z=-24;z<26;z+=2)roadpoints.push(new THREE.Vector3(-57+Math.sin(z*.07)*3,ground(-57+Math.sin(z*.07)*3,z)+.13,z));ribbon(roadpoints,1.2,roadMat);
 const waterMat=material('#bfdad7',{roughness:.21,metalness:.05,transparent:true,opacity:.83,side:THREE.DoubleSide,emissive:'#426f78',emissiveIntensity:.16});const stream=[];for(let z=13;z<=34;z+=3)stream.push(new THREE.Vector3(-23+Math.sin(z*.22)*.5,ground(-23,z)+.28,z));stream.push(new THREE.Vector3(-23,17,37),new THREE.Vector3(-22.5,7,38),new THREE.Vector3(-22,0,40));ribbon(stream,1.8,waterMat);
 const foam=new THREE.Mesh(new THREE.CircleGeometry(5.8,30),material('#d2dfd8',{transparent:true,opacity:.35,depthWrite:false,side:THREE.DoubleSide}));foam.rotation.x=-Math.PI/2;foam.position.set(-22,.12,40);scene.add(foam);
 const mistGeo=new THREE.BufferGeometry(),mistPos=new Float32Array(240*3);for(let i=0;i<240;i++){mistPos[i*3]=-22+(rand()-.5)*8;mistPos[i*3+1]=rand()*5;mistPos[i*3+2]=40+(rand()-.5)*7}mistGeo.setAttribute('position',new THREE.BufferAttribute(mistPos,3));const mist=new THREE.Points(mistGeo,new THREE.PointsMaterial({color:'#e1ede2',size:.35,transparent:true,opacity:.38,depthWrite:false}));scene.add(mist);
 const sheepMat=material('#eee7cb');for(let i=0;i<16;i++){const x=-80+rand()*50,z=-15+rand()*34,y=ground(x,z);const sheep=new THREE.Mesh(new THREE.SphereGeometry(.45,5,4),sheepMat);sheep.scale.set(1.3,.7,.75);sheep.position.set(x,y+.38,z);scene.add(sheep)}
 const clouds=new THREE.Group();const cloudMat=material('#d6d8d1',{transparent:true,opacity:.16,depthWrite:false});for(let i=0;i<13;i++){const cloud=new THREE.Mesh(new THREE.SphereGeometry(1,7,5),cloudMat);cloud.position.set(-220+rand()*440,65+rand()*75,-190+rand()*130);cloud.scale.set(28+rand()*45,3+rand()*6,12+rand()*18);clouds.add(cloud)}scene.add(clouds);
 const birds:THREE.Line[]=[];for(let i=0;i<12;i++){const geo=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(-.9,.18,0),new THREE.Vector3(0,0,0),new THREE.Vector3(.9,.18,0)]);const bird=new THREE.Line(geo,new THREE.LineBasicMaterial({color:'#d8e1d7'}));scene.add(bird);birds.push(bird)}
 const labels=[['GÁSADALUR',new THREE.Vector3(-48,ground(-48,14)+7,14)],['MÚLAFOSSUR',new THREE.Vector3(-22,15,43)],['DRANGARNIR',new THREE.Vector3(70,23,18)],['TINDHÓLMUR',new THREE.Vector3(113,64,-66)]] as const;const labelEls=labels.map(([text])=>{const el=document.createElement('span');el.textContent=text;labelHost.appendChild(el);return el});
 let options:FaroeOptions={hour:16,season:'summer',weather:'clear',sea:.45,exposure:1,film:'portra',auto:false,labels:true},targetCamera:THREE.Vector3|null=null,targetLook:THREE.Vector3|null=null;
 function update(next:FaroeOptions){const seasonChanged=next.season!==options.season;options=next;const day=Math.max(.1,Math.sin((next.hour-5)/15*Math.PI)),gold=next.hour>=17&&next.hour<21;scene.background=new THREE.Color(day<.2?'#1d2a43':gold?'#bcc0b8':'#9cb9c9');const fogColor=day<.2?'#24354b':gold?'#bac0b6':'#aac0c7';const density=next.weather==='fog'?.010:next.weather==='lowcloud'?.0058:next.weather==='typical'?.0038:.0025;scene.fog=new THREE.FogExp2(fogColor,density);sun.color.set(gold?'#ffbc7b':'#e9f0e5');sun.intensity=day*3.2;sun.position.set(Math.cos((next.hour-6)/12*Math.PI)*140,20+day*160,70);ambient.intensity=.65+day*1.9;clouds.visible=next.weather!=='clear';cloudMat.opacity=next.weather==='fog'?.23:.16;windowMat.emissiveIntensity=1-day;seaMat.color.set(day<.2?'#1b3547':gold?'#43595d':'#2a5963');renderer.toneMappingExposure=next.exposure*(fallback?.35+day*.7:1.13);controls.autoRotate=next.auto;
 if(seasonChanged){grass.set(next.season==='winter'?'#b1b8a4':next.season==='autumn'?'#938053':'#78875a');for(const t of terrains){const col=t.geo.getAttribute('color');for(let i=0;i<col.count;i++){const c=(t.slopes[i]>1.2||t.heights[i]<4?rock:grass).clone().multiplyScalar(.87+Math.sin(i*3.31)*.10);if(next.season==='winter'&&t.heights[i]>42&&t.slopes[i]<1.9)c.lerp(new THREE.Color('#e2e5d8'),.78);col.setXYZ(i,c.r,c.g,c.b)}col.needsUpdate=true}}
 if(fallback)(renderer as LandscapeRenderer).invalidate();labelHost.style.display=next.labels?'block':'none';renderer.domElement.style.filter=next.film==='mono'?'grayscale(1) contrast(1.08)':next.film==='chrome'?'saturate(1.3) contrast(1.04)':'saturate(.86) sepia(.06)';}
 function view(id:string){const v=faroeViews.find(x=>x.id===id)||faroeViews[0];targetCamera=new THREE.Vector3(...v.camera as [number,number,number]);targetLook=new THREE.Vector3(...v.target as [number,number,number])}controls.addEventListener('start',()=>{targetCamera=null;targetLook=null});
 const resize=()=>{const w=host.clientWidth,h=host.clientHeight;if(!w||!h)return;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix()};const ro=new ResizeObserver(resize);ro.observe(host);resize();let raf=0,last=performance.now(),elapsed=0;const motion=matchMedia('(prefers-reduced-motion: reduce)');
 function tick(now:number){raf=requestAnimationFrame(tick);if(document.hidden||host.clientWidth===0)return;const dt=Math.min(.04,(now-last)/1000);last=now;elapsed+=dt;if(targetCamera&&targetLook){camera.position.lerp(targetCamera,.07);controls.target.lerp(targetLook,.07);if(camera.position.distanceTo(targetCamera)<.2){targetCamera=null;targetLook=null}}controls.update();if(!motion.matches){if(!fallback){const pos=seaGeo.getAttribute('position');for(let i=0;i<pos.count;i++){const x=pos.getX(i),z=pos.getZ(i);pos.setY(i,(Math.sin(x*.085+elapsed*.65)+Math.sin(z*.073+elapsed*.5+x*.035))*.22*options.sea)}pos.needsUpdate=true;for(let i=0;i<240;i++)mistPos[i*3+1]=(mistPos[i*3+1]+dt*.8)%5;mistGeo.getAttribute('position').needsUpdate=true;clouds.position.x=Math.sin(elapsed*.02)*8}birds.forEach((b,i)=>{b.position.set(-50+Math.sin(elapsed*.1+i)*70,32+i*2+Math.sin(elapsed*.3+i)*2,50+Math.cos(elapsed*.1+i)*32);b.rotation.y=-elapsed*.1-i});foam.scale.setScalar(1+Math.sin(elapsed)*.05)}labels.forEach(([,pos],i)=>{const v=pos.clone().project(camera),el=labelEls[i];el.style.display=v.z<1&&Math.abs(v.x)<1&&Math.abs(v.y)<1?'block':'none';el.style.left=`${(v.x*.5+.5)*100}%`;el.style.top=`${(-v.y*.5+.5)*100}%`});renderer.render(scene,camera)}update(options);raf=requestAnimationFrame(tick);
 function capture(){renderer.render(scene,camera);const out=document.createElement('canvas');out.width=renderer.domElement.width;out.height=renderer.domElement.height;const ctx=out.getContext('2d')!;ctx.filter=renderer.domElement.style.filter;ctx.drawImage(renderer.domElement,0,0);ctx.filter='none';ctx.fillStyle='#0b1119bb';ctx.fillRect(0,out.height-44,out.width,44);ctx.fillStyle='#ead7a9';ctx.font=`${Math.max(12,out.width/80)}px Georgia`;ctx.fillText('FØROYAR  /  CTY STUDIO',20,out.height-18);return out.toDataURL('image/jpeg',.92)}
 return {update,view,capture,dispose(){cancelAnimationFrame(raf);ro.disconnect();controls.dispose();scene.traverse(o=>{if(o instanceof THREE.Mesh||o instanceof THREE.Points||o instanceof THREE.Line){o.geometry.dispose();const ms=Array.isArray(o.material)?o.material:[o.material];ms.forEach(m=>m.dispose())}});renderer.dispose();renderer.domElement.remove();labelEls.forEach(el=>el.remove())}};
}
