'use client';
import {useState,useEffect,useRef} from 'react';
import {ArrowUpRight,ChevronLeft,ChevronRight,Download} from 'lucide-react';
import {albumPhotos as photos} from '@/lib/album-photos';
import houses from './house-data.json';
export function HomeGallery(){const [scheme,setScheme]=useState(0),[room,setRoom]=useState('living');const home=houses[scheme],current=home.rooms.find(r=>r.id===room)!,index=home.rooms.indexOf(current);function step(n:number){setRoom(home.rooms[(index+n+8)%8].id)}return <div className="house-gallery"><div className="scheme-picker" aria-label="房屋方案">{houses.map((s,i)=><button key={s.id} className={scheme===i?'chosen':''} onClick={()=>setScheme(i)}><small>{String(i+1).padStart(2,'0')}</small>{s.title}</button>)}</div><div className="house-main"><div className="house-photo"><img src={`/works/home/${home.id}-${room}.webp`} alt={`${home.title} · ${current.name}原方案`}/><button className="photo-prev" aria-label="上一空间" onClick={()=>step(-1)}><ChevronLeft/></button><button className="photo-next" aria-label="下一空间" onClick={()=>step(1)}><ChevronRight/></button><span className="photo-counter">{String(index+1).padStart(2,'0')} / 08</span></div><aside className="house-note"><span className="paper-eyebrow">TINGJIAN · MY HOME</span><h2>{home.title}</h2><p className="materials">{home.materials}</p><hr/><small>{current.area}</small><h3>{current.name}</h3><p>{current.note}</p><div className="house-cat"><span className="cat-form cat-real"/><span>脏脏包的<br/>未来日常</span></div><a className="paper-button" href="https://tingjian-space-lab.jackchen911006.chatgpt.site" target="_blank" rel="noreferrer">完整设计工作台 <ArrowUpRight size={15}/></a><small className="fine-print">原项目方案 · 概念效果参考</small></aside></div><div className="room-filmstrip">{home.rooms.map(r=><button key={r.id} className={room===r.id?'chosen':''} onClick={()=>setRoom(r.id)}><img src={`/works/home/${home.id}-${r.id}.webp`} alt="" loading="lazy"/><span>{r.name}</span></button>)}</div></div>}
export function PhotoAlbum(){
 const [i,setI]=useState(0),touch=useRef<{x:number;y:number}|null>(null),film=useRef<HTMLDivElement>(null);const current=photos[i];const step=(delta:number)=>setI(n=>(n+delta+photos.length)%photos.length);
 useEffect(()=>{film.current?.querySelector('[aria-current="true"]')?.scrollIntoView({block:'nearest',inline:'nearest'});for(const j of [(i+1)%photos.length,(i+photos.length-1)%photos.length]){const image=new Image();image.src=photos[j].src}},[i]);
 return <div className="photo-album q-album" tabIndex={0} onKeyDown={e=>{if(e.target instanceof HTMLInputElement)return;if(e.key==='ArrowLeft'){e.preventDefault();step(-1)}if(e.key==='ArrowRight'){e.preventDefault();step(1)}}}><div className="album-picture" onTouchStart={e=>{touch.current=e.touches.length===1?{x:e.touches[0].clientX,y:e.touches[0].clientY}:null}} onTouchEnd={e=>{const start=touch.current;touch.current=null;const end=e.changedTouches[0];if(start&&end){const dx=end.clientX-start.x,dy=end.clientY-start.y;if(Math.abs(dx)>45&&Math.abs(dx)>Math.abs(dy)*1.4)step(dx<0?1:-1)}}} onTouchCancel={()=>touch.current=null}><button aria-label="上一张照片" onClick={()=>step(-1)}><ChevronLeft/></button><img src={current.src} alt={current.title+' · 用户提供的Q版照片'} decoding="async" draggable={false}/><button aria-label="下一张照片" onClick={()=>step(1)}><ChevronRight/></button></div><div className="album-caption" aria-live="polite"><span>AI Q版相册 / {String(i+1).padStart(2,'0')} — {String(photos.length).padStart(2,'0')}</span><h2>{current.title}</h2><p>{current.caption}</p><a href={current.src} download={`${current.title}.webp`}><Download size={14}/>保存照片</a></div><div className="album-thumbnails" ref={film} aria-label="全部相册照片">{photos.map((p,n)=><button key={p.src} aria-current={n===i} aria-label={`查看第${n+1}张：${p.title}`} className={n===i?'chosen':''} onClick={()=>setI(n)}><img src={p.thumb} alt="" loading="lazy"/><span>{p.title}</span></button>)}</div></div>
}
const expressions=['风中优雅','趴窝睡觉','鄙视','玩手机','谢谢','点赞','我先躺了','哈哈，没事','暗中吃瓜','没听见','桌下躲起','坏笑','紧张冒汗','疑惑','快来喂我','吐舌'];
// Display the supplied contact sheet as a sprite; the original drawing pixels stay untouched.
function Sticker({i}:{i:number}){const col=i%5,row=Math.floor(i/5);return <span className="original-sticker" role="img" aria-label={expressions[i]} style={{backgroundPosition:`${-13-col*132}px ${-14-row*168}px`}}/>}
export function StickerAlbum(){const [tab,setTab]=useState<'original'|'forms'>('original'),[chosen,setChosen]=useState(5),[form,setForm]=useState(2);const names=['写实脏脏包','方块工程师','像素桌面猫','贴纸脏脏包'];return <div className="sticker-collection"><div className="sticker-collection-toolbar"><div className="example-tabs"><button className={tab==='original'?'chosen':''} onClick={()=>setTab('original')}>日常表情 · 16</button><button className={tab==='forms'?'chosen':''} onClick={()=>setTab('forms')}>角色形象 · 4</button></div><span>脏脏包的表情抽屉</span></div>{tab==='original'?<div className="sticker-drawer"><aside className="sticker-feature"><div className="sticker-enlarged"><Sticker i={chosen}/></div><h2>{expressions[chosen]}</h2><p>今天，也做一只有态度的猫。</p><a href="/works/sticker-collection.png" download="脏脏包表情合集.png">保存原表情合集 <Download size={14}/></a></aside><div className="sticker-grid">{expressions.map((name,i)=><button key={name} className={chosen===i?'chosen':''} onClick={()=>setChosen(i)}><Sticker i={i}/><span>{name}</span></button>)}</div></div>:<div className="sticker-album"><div className="sticker-art"><span className="cat-form" style={{backgroundPosition:`${form*100/3}% 0`}}/><h2>{names[form]}</h2></div><div className="sticker-tabs">{names.map((name,i)=><button key={name} className={form===i?'chosen':''} onClick={()=>setForm(i)}><span className="cat-form" style={{backgroundPosition:`${i*100/3}% 0`}}/>{name}</button>)}</div><a className="gold-button" href="/assets/cat-avatars.webp" download="脏脏包的四种形象.webp">保存角色图集</a></div>}</div>}
