import * as THREE from 'three';
type Face={v:number[];n:THREE.Vector3;c:THREE.Color;center:THREE.Vector3;alpha:number;double:boolean};
/** Draw the same terrain triangles on Canvas when WebGL is unavailable. */
export class LandscapeRenderer{
 domElement:HTMLCanvasElement;private ctx:CanvasRenderingContext2D;private faces:Face[]=[];private dirty=true;private width=1;private height=1;private last=0;outputColorSpace:unknown;toneMapping:unknown;toneMappingExposure=1;shadowMap={enabled:false,type:null as unknown};
 constructor(){this.domElement=document.createElement('canvas');this.ctx=this.domElement.getContext('2d',{alpha:false})!}
 setSize(w:number,h:number){this.width=Math.max(1,w);this.height=Math.max(1,h);this.domElement.width=this.width;this.domElement.height=this.height}
 setPixelRatio(_:number){} invalidate(){this.dirty=true} dispose(){this.faces=[]}
 private prepare(scene:THREE.Scene){this.faces=[];scene.updateMatrixWorld(true);const sun=new THREE.Vector3(-.55,.8,.4).normalize();scene.traverseVisible(o=>{if(!(o instanceof THREE.Mesh)||!o.visible)return;const geo=o.geometry,pos=geo.getAttribute('position');if(!pos)return;const materials=Array.isArray(o.material)?o.material:[o.material],mat=materials[0] as THREE.MeshStandardMaterial,colors=geo.getAttribute('color'),index=geo.index,count=index?index.count:pos.count;if(mat instanceof THREE.ShaderMaterial)return;const add=(matrix:THREE.Matrix4,base:THREE.Color)=>{for(let i=0;i<count;i+=3){const ids=[0,1,2].map(n=>index?index.getX(i+n):i+n);const pts=ids.map(k=>new THREE.Vector3(pos.getX(k),pos.getY(k),pos.getZ(k)).applyMatrix4(matrix));const center=pts[0].clone().add(pts[1]).add(pts[2]).multiplyScalar(1/3),n=pts[1].clone().sub(pts[0]).cross(pts[2].clone().sub(pts[0])).normalize();let c=base.clone();if(colors)c=new THREE.Color().setRGB((colors.getX(ids[0])+colors.getX(ids[1])+colors.getX(ids[2]))/3,(colors.getY(ids[0])+colors.getY(ids[1])+colors.getY(ids[2]))/3,(colors.getZ(ids[0])+colors.getZ(ids[1])+colors.getZ(ids[2]))/3);c.multiplyScalar(.48+Math.max(0,n.dot(sun))*.72);this.faces.push({v:pts.flatMap(v=>v.toArray()),center,n,c,alpha:mat.opacity??1,double:mat.side===THREE.DoubleSide})}};
 if(o instanceof THREE.InstancedMesh){const m=new THREE.Matrix4(),c=new THREE.Color();for(let i=0;i<o.count;i++){o.getMatrixAt(i,m);m.premultiply(o.matrixWorld);if(o.instanceColor)o.getColorAt(i,c);else c.copy(mat.color||new THREE.Color('#8da397'));add(m,c)}}else add(o.matrixWorld,mat.color||new THREE.Color('#67898e'))});this.dirty=false}
 render(scene:THREE.Scene,camera:THREE.Camera){const now=performance.now();if(now-this.last<70)return;this.last=now;if(this.dirty)this.prepare(scene);camera.updateMatrixWorld();const vp=new THREE.Matrix4().multiplyMatrices(camera.projectionMatrix,camera.matrixWorldInverse).elements,view=camera.matrixWorldInverse.elements,cp=new THREE.Vector3().setFromMatrixPosition(camera.matrixWorld),ctx=this.ctx,w=this.width,h=this.height;const sky=scene.background instanceof THREE.Color?scene.background:new THREE.Color('#a6c4cb');ctx.fillStyle='#'+sky.getHexString();ctx.fillRect(0,0,w,h);const bg=ctx.createLinearGradient(0,0,0,h);bg.addColorStop(0,'#ffffff00');bg.addColorStop(1,'#bbc6b433');ctx.fillStyle=bg;ctx.fillRect(0,0,w,h);const fog=scene.fog instanceof THREE.FogExp2?scene.fog:null;
 const sorted=this.faces.filter(f=>f.double||f.n.dot(cp.clone().sub(f.center))>0).map(f=>({f,z:view[2]*f.center.x+view[6]*f.center.y+view[10]*f.center.z+view[14]})).sort((a,b)=>a.z-b.z);
 for(const {f,z} of sorted){const xy:number[]=[];let valid=true;for(let i=0;i<9;i+=3){const x=f.v[i],y=f.v[i+1],zz=f.v[i+2],cw=vp[3]*x+vp[7]*y+vp[11]*zz+vp[15];if(cw<.5){valid=false;break}xy.push(((vp[0]*x+vp[4]*y+vp[8]*zz+vp[12])/cw*.5+.5)*w,(-(vp[1]*x+vp[5]*y+vp[9]*zz+vp[13])/cw*.5+.5)*h)}if(!valid||Math.max(xy[0],xy[2],xy[4])<0||Math.min(xy[0],xy[2],xy[4])>w||Math.max(xy[1],xy[3],xy[5])<0||Math.min(xy[1],xy[3],xy[5])>h)continue;const c=f.c.clone().multiplyScalar(this.toneMappingExposure);if(fog)c.lerp(fog.color,1-Math.exp(-fog.density*fog.density*z*z));c.convertLinearToSRGB();ctx.fillStyle=`rgb(${Math.min(255,c.r*255)|0},${Math.min(255,c.g*255)|0},${Math.min(255,c.b*255)|0})`;ctx.globalAlpha=f.alpha;ctx.beginPath();ctx.moveTo(xy[0],xy[1]);ctx.lineTo(xy[2],xy[3]);ctx.lineTo(xy[4],xy[5]);ctx.closePath();ctx.fill()}
 ctx.globalAlpha=1;
 }
}
