'use client';
import type {ReactNode} from 'react';
import {Search,SlidersHorizontal,ArrowUpRight,Play,Pause,House,Volume2,VolumeX} from 'lucide-react';
import {type AppId,getApp} from '@/lib/desktop-apps';
import {wallpapers,type WallpaperId} from '@/lib/desktop-scenery';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import MoonCorner from './MoonCorner';
import Icon from './DesktopIcon';
import {useMusic} from './MusicContext';
import thumbnails from './catalogue-thumbnails.json';
const optimized=thumbnails as Record<string,{thumb:string;preview:string}>;
export function MobileBar({clock,onMenu,onSearch,sound,onSound}:{clock:string;onMenu:()=>void;onSearch:()=>void;sound:boolean;onSound:()=>void}){return <header className="mobile-topbar"><time>{clock||'--:--'}</time><button data-start-toggle onClick={onMenu}>CTY—OS <span>⌄</span></button><div><button aria-label="搜索作品" onClick={onSearch}><Search size={19}/></button><button aria-label={sound?'关闭操作音':'开启操作音'} onClick={onSound}>{sound?<Volume2 size={18}/>:<VolumeX size={18}/>}</button></div></header>}
export default function MobileHome({onMoonEnter,clock,phase,onPhase,open,onActions,children,running,name}:{onMoonEnter:()=>void;clock:string;phase:number;onPhase:(n:number)=>void;open:(id:AppId)=>void;onActions:()=>void;children:ReactNode;running:AppId[];name:(id:AppId)=>string}){
 const greeting=Number(clock.split(':')[0])<11?'上午好':Number(clock.split(':')[0])<18?'下午好':'晚上好';
 const music=useMusic(),featured:AppId[]=['zp-benchmark','zp-dust-road','zp-pixel-focus'];const image=(id:AppId)=>{const a=getApp(id);return a?.image?optimized[a.image]?.thumb||a.image:undefined};
 return <div className="mobile-home" data-mobile-home><section className="mobile-clock"><div><p>{greeting}</p><h1>{clock||'--:--'}</h1><time suppressHydrationWarning>{new Date().toLocaleDateString('zh-CN',{year:'numeric',month:'long',day:'numeric',weekday:'long'})}</time><span>CTY AI STUDIO</span></div><MoonCorner phase={phase} onChange={onPhase} width={390} height={760} compact onEnter={onMoonEnter}/></section>
 <section className="mobile-assistant-card"><button className="mobile-cat-portrait" onClick={()=>open('cat')} aria-label="和AI小脏聊天"><img src="/images/cat-portrait-grin-v27.webp" alt="脏脏包"/></button><div className="mobile-cat-copy"><p>喵～我是 AI 小脏。<br/>今天想看哪件作品？</p></div><div className="mobile-cat-actions"><button onClick={()=>open('cat')}>问问小脏</button><button onClick={()=>open('works')}>看看作品</button><button onClick={()=>open('music')}>听首歌</button></div></section>
 <div className="mobile-feature-pair"><button className="mobile-video-card" onClick={()=>open('zp-benchmark')}><img src={image('zp-benchmark')} alt=""/><span className="mobile-card-tag">AI 创作</span><span className="mobile-play-disc"><Play size={18} fill="currentColor"/></span><div><h2>创作实验室</h2><span>鹈鹕骑车 · AI 创作实测</span></div></button><section className="mobile-music-card"><button className="mobile-record-link" aria-label="打开月光唱片机" onClick={()=>open('music')}><img className="mobile-track-art" src={music.track.cover||'/assets/mosaic-vinyl.webp'} alt=""/><span className="mobile-card-tag">月光唱机</span><div><small>MOONLIGHT FM</small><h2>{music.track.title||'听一首老歌'}</h2></div></button><button className="mobile-music-toggle" aria-label={music.playing?'暂停音乐':'播放音乐'} onClick={music.toggle}>{music.playing?<Pause size={17}/>:<Play size={17}/>}</button></section></div>
 <section className="mobile-featured"><header><h2>精选作品</h2><button onClick={()=>open('works')}>作品集 <ArrowUpRight size={16}/></button></header><div className="mobile-featured-grid">{featured.map(id=><button key={id} onClick={()=>open(id)}><img src={image(id)} alt="" loading="lazy"/><strong>{getApp(id).name}</strong></button>)}</div></section>
 {running.length>0&&<section className="mobile-recent"><span>正在运行</span><div>{running.map(id=><button key={id} onClick={()=>open(id)}><Icon n={getApp(id).icon} small/>{name(id)}</button>)}</div></section>}
 <section className="mobile-app-section"><h2 className="sr-only">桌面应用</h2>{children}<div className="mobile-hold-hint"><span>长按图标管理应用</span><button onClick={onActions}><SlidersHorizontal size={14}/>桌面与壁纸</button></div></section><footer className="mobile-home-signature">CTY STUDIO <span>代码、猫咪，和一些温暖的记忆。</span></footer></div>
}
export function MobileDock({open,home,active}:{open:(id:AppId)=>void;home:()=>void;active?:AppId}){return <footer className="taskbar mobile-dock"><button aria-label="返回桌面" className={!active?'active':''} onClick={home}><House size={23}/><span>桌面</span></button>{(['works','cat','music'] as AppId[]).map(id=><button key={id} onClick={()=>open(id)} className={active===id?'active':''}><Icon n={getApp(id).icon} small/><span>{id==='cat'?'AI 小脏':id==='music'?'音乐':'作品'}</span></button>)}</footer>}
export function MobileActions({shown,onChange,title,isApp,onAction,wallpaper,setWallpaper,auto,setAuto,moveTarget,appChoices,onSwap}:{shown:boolean;onChange:(b:boolean)=>void;title:string;isApp:boolean;onAction:(action:string)=>void;wallpaper:WallpaperId;setWallpaper:(id:WallpaperId)=>void;auto:boolean;setAuto:(b:boolean)=>void;moveTarget:AppId|null;appChoices:{id:AppId;name:string}[];onSwap:(id:AppId)=>void}){const action=(key:string)=>{onChange(false);onAction(key)};return <Dialog open={shown} onOpenChange={onChange}><DialogContent className="mobile-actions-sheet"><DialogHeader><DialogTitle>{moveTarget?'选择要交换的图标':title}</DialogTitle><DialogDescription>{moveTarget?'两个图标互换位置，始终保持整齐排列。':isApp?'选择应用操作':'桌面整理与月光壁纸'}</DialogDescription></DialogHeader>{moveTarget?<div className="mobile-swap-grid">{appChoices.filter(a=>a.id!==moveTarget).map(a=><button key={a.id} onClick={()=>onSwap(a.id)}><Icon n={getApp(a.id).icon} small/>{a.name}</button>)}</div>:<><div className="mobile-wallpapers"><h3>修改壁纸 · 今晚的窗外</h3><div>{wallpapers.map(w=><button key={w.id} aria-pressed={wallpaper===w.id} onClick={()=>setWallpaper(w.id)}><span className={'wallpaper-swatch swatch-'+w.id}/>{w.name}</button>)}</div><label><input type="checkbox" checked={auto} onChange={e=>setAuto(e.target.checked)}/>每 10 分钟自动切换</label></div><div className="mobile-action-grid">{(isApp?[['open','打开应用'],['rename','重命名'],['swap','交换位置'],['properties','属性'],['protected','删除']]:[['name','按名称排列'],['type','按类型排列'],['arrange','整理桌面'],['terminal','打开终端']]).map(([key,label])=><button key={key} onClick={()=>action(key)}>{label}</button>)}</div></>}</DialogContent></Dialog>}
