'use client';
import {useEffect,useRef,useState,type CSSProperties} from 'react';
import {Disc3,Droplets,TrainFront,Radio,Gamepad2,Library,ArrowLeft,Moon,Sun,CloudRain,SkipForward,SkipBack,Play,Pause} from 'lucide-react';
import {useMusic,formatTime} from './MusicContext';
import {MusicImports,Transport,RecordDisc} from './MusicPlayer';
import PixelRoom from './PixelMusicRoom';
const rooms=[{id:'vinyl',name:'唱片行',en:'THE RECORD STORE',icon:Disc3},{id:'ink',name:'墨',en:'SOUND IN INK',icon:Droplets},{id:'train',name:'末班电车',en:'THE LAST TRAIN',icon:TrainFront},{id:'live',name:'Live House',en:'ONE MORE SONG',icon:Radio},{id:'pixel',name:'像素关卡',en:'EVERY SONG A LEVEL',icon:Gamepad2}];
function VinylRoom(){const p=useMusic(),state=useRef(p),vu=useRef<HTMLDivElement>(null);state.current=p;useEffect(()=>{let raf=0;const draw=()=>{if(vu.current)vu.current.style.setProperty('--level',String(state.current.playing?.18+Math.sin(performance.now()*.009)*.12+state.current.energy():0));raf=requestAnimationFrame(draw)};draw();return()=>cancelAnimationFrame(raf)},[]);return <div className="vinyl-room"><div className="wood-player"><RecordDisc wood/><div className="analog-console"><div ref={vu} className="vu-meter"><small>VU</small><i/><span>−20　−10　0　+3</span></div><div className="console-readout"><span>STEREO · 33⅓</span><b>{p.track.title}</b><small>{formatTime(p.position)} / {formatTime(p.duration)}</small></div><button onClick={p.toggle}>{p.playing?<Pause/>:<Play/>}</button></div></div><aside className="record-crate"><span>NOW SPINNING</span><h2>{p.track.title}</h2><p>{p.track.artist}</p><div className="crate-sleeves">{p.tracks.slice(0,12).map((t,i)=><button key={t.id} className={t.id===p.track.id?'chosen':''} style={{'--record-index':i} as CSSProperties} onClick={()=>p.select(t.id)}><img src={t.cover||'/assets/mosaic-vinyl.webp'} alt=""/><span>{t.title}</span></button>)}</div><small>翻一张唱片，拖动唱臂调进度。</small></aside></div>}
function InkRoom(){const p=useMusic(),canvas=useRef<HTMLCanvasElement>(null),state=useRef(p),[night,setNight]=useState(false),[colored,setColored]=useState(false);state.current=p;
 useEffect(()=>{const c=canvas.current;if(!c)return;const ctx=c.getContext('2d')!;let w=1,h=1,raf=0,t=0;const drops:{x:number;y:number;vx:number;vy:number;r:number;age:number;hue:number}[]=[];
 const resize=()=>{w=c.clientWidth;h=c.clientHeight;c.width=Math.max(1,w);c.height=Math.max(1,h)};const ro=new ResizeObserver(resize);ro.observe(c);resize();
 function drop(x:number,y:number,count=35){for(let i=0;i<count;i++){const a=Math.random()*Math.PI*2;drops.push({x,y,vx:Math.cos(a)*(.2+Math.random()),vy:Math.sin(a)*(.2+Math.random()),r:2+Math.random()*9,age:0,hue:180+Math.random()*110})}if(drops.length>1100)drops.splice(0,drops.length-1100)}
 const point=(e:PointerEvent)=>{const b=c.getBoundingClientRect();if(e.buttons||e.type==='pointerdown')drop(e.clientX-b.left,e.clientY-b.top,12)};c.addEventListener('pointerdown',point);c.addEventListener('pointermove',point);
 const draw=()=>{t++;ctx.clearRect(0,0,w,h);const r=Math.min(w*.32,h*.39),cx=w*.45,cy=h*.5;ctx.strokeStyle=night?'#c8c0a129':'#6059471b';ctx.lineWidth=11;ctx.beginPath();ctx.arc(cx,cy,r,.3,Math.PI*2-.2);ctx.stroke();ctx.lineWidth=2;ctx.strokeStyle=night?'#ddc49b':'#9c4538';ctx.beginPath();ctx.arc(cx,cy,r,-Math.PI/2,-Math.PI/2+Math.PI*2*state.current.position/Math.max(1,state.current.duration));ctx.stroke();
 if(state.current.playing&&t%8===0){const a=t*.019;drop(cx+Math.cos(a)*r*.7,cy+Math.sin(a*.8)*r*.65,3+Math.round(state.current.energy()*14))}
 for(let i=drops.length-1;i>=0;i--){const d=drops[i];d.age++;d.x+=d.vx+Math.sin(d.y*.02+t*.004)*.12;d.y+=d.vy;d.vx*=.992;d.vy*=.992;d.r+=.035;const a=Math.max(0,1-d.age/450)*.13;const gradient=ctx.createRadialGradient(d.x,d.y,0,d.x,d.y,d.r);gradient.addColorStop(0,colored?`hsla(${d.hue},42%,${night?65:30}%,${a})`:night?`rgba(225,211,180,${a})`:`rgba(25,34,30,${a})`);gradient.addColorStop(1,'transparent');ctx.fillStyle=gradient;ctx.fillRect(d.x-d.r,d.y-d.r,d.r*2,d.r*2);if(d.age>450)drops.splice(i,1)}raf=requestAnimationFrame(draw)};drop(w*.45,h*.5,80);draw();return()=>{cancelAnimationFrame(raf);ro.disconnect();c.removeEventListener('pointerdown',point);c.removeEventListener('pointermove',point)};
 },[night,colored]);
 return <div className={'ink-room '+(night?'ink-night':'')}><canvas ref={canvas} aria-label="点下滴墨，拖动搅动墨水"/><div className="ink-title"><small>听 / 一 / 段 / 留 / 白</small><h2>{p.track.title}</h2><span>{p.track.demo?'氛围演示':p.track.artist}</span></div><div className="ink-center"><span>{formatTime(p.position)}</span><p>声在水中，心在此间。</p></div><div className="ink-stamps"><button onClick={p.toggle}>{p.playing?'停':'播'}</button><button onClick={()=>p.next(-1)}>前</button><button onClick={()=>p.next()}>后</button><button onClick={()=>setNight(v=>!v)}>{night?'昼':'夜'}</button><button onClick={()=>setColored(v=>!v)}>{colored?'墨':'彩'}</button></div><label className="ink-seek">卷 <input type="range" min="0" max={p.duration} step=".1" value={p.position} onChange={e=>p.seek(+e.target.value)} aria-label="墨：播放进度"/></label><small className="ink-hint">点下滴墨 · 拖动搅水</small></div>
}
function TrainRoom(){const p=useMusic(),[weather,setWeather]=useState('dusk');return <div className={`train-room weather-${weather}`}><div className="train-line"><small>末班线<br/><span>LAST TRAIN</span></small><div>{p.tracks.map((t,i)=><button key={t.id} className={t.id===p.track.id?'chosen':''} onClick={()=>p.select(t.id)}><i/><span>{t.title}</span><small>MP{String(i+1).padStart(2,'0')}</small></button>)}</div></div><div className="train-window"><div className="train-scenery" style={{animationPlayState:p.playing?'running':'paused'}}/><div className="train-rain"/><div className="train-window-posts"><i/><i/><i/></div><div className="train-handles">{[0,1,2,3,4].map(i=><span key={i}/>)}</div></div><div className="train-dashboard"><div className="train-ticket"><small>末班电车　LAST TRAIN</small><b>{p.track.title}</b><span>音乐陪你回家。</span><div>{formatTime(p.position)} / {formatTime(p.duration)} <em>ONE WAY</em></div></div><div className="train-arrival"><small>现在到站 / NOW ARRIVING</small><p>把城市的灯，留在车窗外。</p><div><button aria-label="上一站" onClick={()=>p.next(-1)}><SkipBack size={16}/></button><span>下一站，是你的下一首歌。</span><button aria-label="下一站" onClick={()=>p.next()}><SkipForward size={16}/></button></div></div><div className="train-weather"><button className={weather==='dusk'?'chosen':''} onClick={()=>setWeather('dusk')}><Sun size={16}/>黄昏</button><button className={weather==='rain'?'chosen':''} onClick={()=>setWeather('rain')}><CloudRain size={16}/>雨夜</button><button className={weather==='night'?'chosen':''} onClick={()=>setWeather('night')}><Moon size={16}/>夜行</button></div></div></div>}
function LiveRoom(){const p=useMusic(),state=useRef(p),canvas=useRef<HTMLCanvasElement>(null),[view,setView]=useState(0),[color,setColor]=useState('#ee9fdf'),[laser,setLaser]=useState(true),[haze,setHaze]=useState(true),[confetti,setConfetti]=useState(0),[blackout,setBlackout]=useState(false);state.current=p;
 useEffect(()=>{const c=canvas.current;if(!c)return;const ctx=c.getContext('2d')!;let w=1,h=1,raf=0,t=0;const ro=new ResizeObserver(()=>{w=c.width=c.clientWidth;h=c.height=c.clientHeight});ro.observe(c);const draw=()=>{t+=.016;const beat=state.current.energy(),active=state.current.playing;ctx.fillStyle=blackout?'#020206':'#070613';ctx.fillRect(0,0,w,h);const cx=w/2,cy=h*(view===1?.34:.40),stageW=w*(view===1?.54:.73);if(!blackout){const glow=ctx.createRadialGradient(cx,cy,0,cx,cy,w*.7);glow.addColorStop(0,color+'48');glow.addColorStop(1,'#03020b');ctx.fillStyle=glow;ctx.fillRect(0,0,w,h);ctx.fillStyle='#0b0b16';ctx.fillRect(cx-stageW/2,cy-h*.22,stageW,h*.4);ctx.strokeStyle=color;ctx.lineWidth=2;ctx.strokeRect(cx-stageW/2,cy-h*.22,stageW,h*.4);for(let i=0;i<40;i++){const bar=(.12+(active?Math.abs(Math.sin(t*4+i*.7))*.3+beat:.04))*h;ctx.fillStyle=i%3===0?'#dcd6fd':color;ctx.globalAlpha=.55;ctx.fillRect(cx-stageW*.42+i*stageW*.021,cy+h*.12-bar,stageW*.01,bar)}ctx.globalAlpha=1;if(laser)for(let i=0;i<7;i++){const source=cx-stageW*.46+i*stageW*.153,x=cx+Math.sin(t*(active?.45:.08)+i)*w*.9;const gradient=ctx.createLinearGradient(source,cy-h*.22,x,h);gradient.addColorStop(0,color+'bc');gradient.addColorStop(1,color+'00');ctx.fillStyle=gradient;ctx.beginPath();ctx.moveTo(source-2,cy-h*.22);ctx.lineTo(x-35,h);ctx.lineTo(x+35,h);ctx.lineTo(source+2,cy-h*.22);ctx.fill()}if(haze){ctx.fillStyle='#c3c5ff0a';for(let j=0;j<5;j++){ctx.beginPath();ctx.ellipse(cx+Math.sin(t*.2+j)*w*.3,h*.68+j*7,w*.7,17+j*5,0,0,Math.PI*2);ctx.fill()}}}
 for(let row=0;row<4;row++){for(let i=0;i<32;i++){const depth=row/4,r=5+depth*9,x=(i+.5)*(w/32)+Math.sin(row*4+i)*8,y=h*.67+row*h*.085+(active?Math.sin(t*3+i)*3:0);ctx.fillStyle='#030409';ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();ctx.fillRect(x-r*.8,y+r*.6,r*1.6,r*3);if(i%3===0&&!blackout){const tilt=Math.sin(t*2+i)*11;ctx.strokeStyle=color;ctx.lineWidth=3;ctx.shadowBlur=8;ctx.shadowColor=color;ctx.beginPath();ctx.moveTo(x+r,y+5);ctx.lineTo(x+r+tilt,y-24-depth*8);ctx.stroke();ctx.shadowBlur=0}}}
 if(confetti&&!blackout){const elapsed=(performance.now()-confetti)/1000;if(elapsed<6)for(let i=0;i<120;i++){const y=(elapsed*85+(i*137)%h)%h;ctx.fillStyle=['#e4cf88',color,'#b4d1ec'][i%3];ctx.save();ctx.translate((i*83+w+Math.sin(elapsed+i)*35)%w,y);ctx.rotate(elapsed+i);ctx.fillRect(0,0,3,8);ctx.restore()}}raf=requestAnimationFrame(draw)};draw();return()=>{cancelAnimationFrame(raf);ro.disconnect()};},[view,color,laser,haze,blackout,confetti]);
 return <div className="live-room"><canvas ref={canvas} aria-label="随音乐变化的舞台、激光与观众应援" onClick={()=>setConfetti(performance.now())}/><header><small>CTY LIVE / TONIGHT ONLY</small><h2>{p.track.title}</h2></header><div className="live-toggles"><button className={laser?'chosen':''} onClick={()=>setLaser(v=>!v)}>激光</button><button className={haze?'chosen':''} onClick={()=>setHaze(v=>!v)}>薄雾</button><button onClick={()=>setConfetti(performance.now())}>撒彩带</button><button className={blackout?'chosen':''} onClick={()=>setBlackout(v=>!v)}>黑场</button><button onClick={()=>setView(v=>(v+1)%2)}>切换视角</button><label>应援色 <input type="color" value={color} onChange={e=>setColor(e.target.value)} aria-label="应援棒颜色"/></label></div></div>
}
export function MoonPlayer(){const p=useMusic(),[phase,setPhase]=useState(2);return <div className={'moon-player moon-phase-'+phase}><header><small>MOON PHASES / CTY STUDIO</small><h2>月相唱机</h2></header><div className="moon-record"><RecordDisc/></div><div className="moon-track"><h3>{p.track.title}</h3><p>{p.track.artist}</p></div><nav>{['新月','上弦','满月','下弦'].map((n,i)=><button key={n} className={phase===i?'chosen':''} onClick={()=>setPhase(i)}>{n}</button>)}</nav><Transport/><MusicImports/>{p.error&&<p className="music-note" role="alert">{p.error}</p>}</div>}
export default function MusicRooms({initialRoom='vinyl'}:{initialRoom?:string}){const p=useMusic(),[room,setRoom]=useState(initialRoom),[library,setLibrary]=useState(false);const current=rooms.find(r=>r.id===room)||rooms[0];return <div className={'music-rooms room-'+room}><nav className="rooms-nav"><div>{rooms.map(r=><button key={r.id} className={room===r.id?'chosen':''} onClick={()=>setRoom(r.id)}><r.icon size={16}/><span>{r.name}</span></button>)}</div><button className={library?'chosen':''} onClick={()=>setLibrary(v=>!v)}><Library size={16}/>曲库</button></nav><div className="rooms-stage">{room==='vinyl'?<VinylRoom/>:room==='ink'?<InkRoom/>:room==='train'?<TrainRoom/>:room==='live'?<LiveRoom/>:<PixelRoom/>}{library&&<aside className="room-library"><header><span>所有房间，共用一份歌单。</span><button onClick={()=>setLibrary(false)} aria-label="关闭曲库">×</button></header><div className="cty-track-list">{p.tracks.map(t=><button key={t.id} className={t.id===p.track.id?'chosen':''} onClick={()=>p.select(t.id)}><img src={t.cover||'/assets/mosaic-vinyl.webp'} alt=""/><span><b>{t.title}</b><small>{t.artist}</small></span></button>)}</div><MusicImports/></aside>}</div><footer className="rooms-player"><div className="rooms-now"><span>{current.en}</span><b>{p.track.title}</b><small>{p.track.demo?'氛围演示':p.track.artist}</small></div><Transport/><button className="room-loop" onClick={()=>p.setLoop(!p.loop)}>{p.loop?'单曲循环':'顺序播放'}</button></footer>{p.error&&<p className="music-note" role="alert">{p.error}</p>}</div>}
