'use client';
import {createContext,useContext,useEffect,useRef,useState,type ReactNode} from 'react';
export type Track={id:string;title:string;artist:string;src:string;cover?:string;demo?:boolean;duration?:number};
const names=[['harbor','午后唱片行'],['ink','纸上听雨'],['train','最后一班电车'],['live','星光现场'],['pixel','猫咪的第八关'],['moon','月亮慢慢走']];
const demoTracks:Track[]=names.map(([id,title])=>({id,title,artist:'CTY STUDIO · 氛围演示',src:`/audio/${id}.mp3`,demo:true}));
const includedTracks:Track[]=[{id:'falling-stars',title:'Falling Like The Stars',artist:'James Arthur',src:'/audio/james-arthur-falling-like-the-stars.mp3',cover:'/audio/covers/james-arthur-falling-like-the-stars-cover.jpg',duration:255.138},{id:'autumn-sea',title:'秋天的海',artist:'蘇慧倫',src:'/audio/tarcy-su-qiu-tian-de-hai.mp3',cover:'/audio/covers/tarcy-su-label-cover.jpg',duration:243.096},...demoTracks];
type Player={tracks:Track[];track:Track;playing:boolean;position:number;duration:number;volume:number;error:string;select:(id:string,play?:boolean)=>void;toggle:()=>void;pause:()=>void;next:(delta?:number)=>void;seek:(time:number)=>void;setVolume:(n:number)=>void;importFiles:(files:FileList|File[])=>void;setCover:(file:File)=>void;energy:()=>number;loop:boolean;setLoop:(v:boolean)=>void};
const Context=createContext<Player|null>(null);
export function useMusic(){const value=useContext(Context);if(!value)throw Error('Music provider missing');return value}
export function MusicProvider({children}:{children:ReactNode}){
 const [tracks,setTracks]=useState<Track[]>(includedTracks),[id,setId]=useState('falling-stars'),[playing,setPlaying]=useState(false),[position,setPosition]=useState(0),[duration,setDuration]=useState(255.138),[volume,setVol]=useState(.55),[error,setError]=useState(''),[loop,setLoop]=useState(false);
 const seekTarget=useRef<number|null>(null),gain=useRef<GainNode|null>(null),volumeRef=useRef(volume),volumeReady=useRef(false);volumeRef.current=volume;
 const audio=useRef<HTMLAudioElement>(null),urls=useRef<string[]>([]),pending=useRef(false),context=useRef<AudioContext|null>(null),analyser=useRef<AnalyserNode|null>(null),data=useRef<Uint8Array<ArrayBuffer>|null>(null),track=tracks.find(t=>t.id===id)||tracks[0];
 function attachAnalyser(){try{if(!context.current&&audio.current){const ctx=new AudioContext(),source=ctx.createMediaElementSource(audio.current),node=ctx.createAnalyser();node.fftSize=128;source.connect(node);const output=ctx.createGain();output.gain.value=volumeRef.current;node.connect(output);output.connect(ctx.destination);gain.current=output;audio.current.volume=1;context.current=ctx;analyser.current=node;data.current=new Uint8Array(node.frequencyBinCount)}void context.current?.resume()}catch{}}
 async function play(){if(!audio.current)return;attachAnalyser();setError('');try{await audio.current.play()}catch{setError('无法播放这个文件。请使用普通 MP3、M4A 或 WAV，加密会员文件无法直接读取。')}}
 function pause(){pending.current=false;audio.current?.pause()}
 function toggle(){if(audio.current?.paused)void play();else pause()}
 function select(value:string,start=true){if(value===id){if(start)void play();return}pending.current=start;seekTarget.current=null;audio.current?.pause();setId(value);setPosition(0);setDuration(tracks.find(t=>t.id===value)?.duration||0);setError('')}
 function next(delta=1){const i=tracks.findIndex(t=>t.id===id);select(tracks[(i+delta+tracks.length)%tracks.length].id,true)}
 function applySeek(){const a=audio.current;if(!a||a.readyState<1||seekTarget.current===null)return;const target=Math.max(0,Math.min(Number.isFinite(a.duration)?a.duration:duration,seekTarget.current));try{a.currentTime=target;setPosition(target);if(!a.seeking)seekTarget.current=null}catch{setError('正在等待音频缓冲，准备好后会跳到选中的位置。')}}
 function seek(n:number){if(!Number.isFinite(n))return;const length=Number.isFinite(audio.current?.duration)?audio.current!.duration:duration;seekTarget.current=Math.max(0,Math.min(length||n,n));setPosition(seekTarget.current);applySeek()}
 function setVolume(n:number){if(!Number.isFinite(n))return;setVol(Math.max(0,Math.min(1,n)))}
 useEffect(()=>{try{const stored=localStorage.getItem('cty-music-volume');if(stored!==null&&Number.isFinite(Number(stored)))setVolume(Number(stored))}catch{}volumeReady.current=true},[]);
 useEffect(()=>{if(gain.current)gain.current.gain.value=volume;else if(audio.current)audio.current.volume=volume;if(volumeReady.current)try{localStorage.setItem('cty-music-volume',String(volume))}catch{}},[volume]);
 useEffect(()=>{if(!audio.current)return;audio.current.load();if(pending.current){pending.current=false;void play()}},[track.src]);
 useEffect(()=>()=>{urls.current.forEach(URL.revokeObjectURL);void context.current?.close()},[]);
 function importFiles(files:FileList|File[]){const items:Track[]=[];let encrypted=false;for(const file of Array.from(files)){if(/\.(ncm|qmc\w*|kgm\w*|kwm|mflac|mgg)$/i.test(file.name)){encrypted=true;continue}if(!file.type.startsWith('audio/')&&!/\.(mp3|m4a|wav|ogg|flac|aac)$/i.test(file.name))continue;const src=URL.createObjectURL(file);urls.current.push(src);const name=file.name.replace(/\.[^.]+$/,'');const parts=name.split(' - ');items.push({id:crypto.randomUUID(),title:parts.length>1?parts.slice(1).join(' - '):name,artist:parts.length>1?parts[0]:'本机音乐',src})}if(items.length){setTracks(old=>[...old,...items]);pending.current=false;audio.current?.pause();seekTarget.current=null;setId(items[0].id);setPosition(0);setDuration(0)}setError(encrypted?'检测到加密会员文件。请换成可在普通播放器中打开的 MP3 / M4A。':items.length?'':'没有找到支持的音频文件。')}
 function setCover(file:File){if(!file.type.startsWith('image/')){setError('请选择 JPG、PNG 或 WebP 封面。');return}if(file.size>15*1024*1024){setError('封面请小于 15 MB。');return}const cover=URL.createObjectURL(file);urls.current.push(cover);setTracks(old=>old.map(t=>t.id===id?{...t,cover}:t));setError('')}
 function energy(){if(!analyser.current||!data.current||!playing)return 0;analyser.current.getByteFrequencyData(data.current);return data.current.reduce((a,b)=>a+b,0)/data.current.length/255}
 return <Context.Provider value={{tracks,track,playing,position,duration,volume,error,select,toggle,pause,next,seek,setVolume,importFiles,setCover,energy,loop,setLoop}}>{children}<audio ref={audio} src={track.src} preload="auto" onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onTimeUpdate={e=>{if(seekTarget.current===null)setPosition(e.currentTarget.currentTime)}} onSeeked={e=>{const actual=e.currentTarget.currentTime;if(seekTarget.current!==null&&Math.abs(actual-seekTarget.current)>.35){applySeek();return}seekTarget.current=null;setPosition(actual)}} onCanPlay={applySeek} onLoadedMetadata={e=>{if(Number.isFinite(e.currentTarget.duration))setDuration(e.currentTarget.duration);applySeek()}} onEnded={()=>{if(loop){seek(0);void play()}else next()}} onError={()=>{setPlaying(false);setError('音频无法读取。请导入普通 MP3、M4A 或 WAV 文件。')}}/></Context.Provider>;
}
export const formatTime=(n:number)=>`${Math.floor((Number.isFinite(n)?n:0)/60)}:${String(Math.floor((Number.isFinite(n)?n:0)%60)).padStart(2,'0')}`;
