"use client";
import {useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import AppLoading from './AppLoading';
import {SoftwareRenderer} from './SoftwareRenderer';
import {createActorLayer,type CodeActor} from '@/lib/minecraft/showcase-actors';
const examples=[['shanghai','上海中心'],['palace','太和殿'],['cat','巨型脏脏包'],['hokage','火影大楼'],['dragon','召唤方块龙'],['pain','佩恩与卡卡西']];

type Voxel=[number,number,number,number,number?];
const dyes=['#e9e8dd','#df8e3e','#bc65ba','#73b4cf','#edca48','#87b840','#e2a0b3','#555b5c','#a6aaa0','#419ca2','#8c58b2','#4c63b4','#79583b','#607a38','#b65447','#282d32'];
const palette:Record<number,string>={1:'#929c99',2:'#79a846',3:'#8e6747',4:'#7f8a85',5:'#c39a60',9:'#58abc3',10:'#f46a26',12:'#e4cd92',17:'#745135',18:'#4b873e',20:'#b5dce5',24:'#d9bf81',41:'#f2c75b',42:'#dde0d9',45:'#bd6751',49:'#343044',57:'#69d9d1',79:'#a8ddec',80:'#eff7ff',89:'#f3bc65',98:'#929e9e',155:'#ece6d8',174:'#70bedc',201:'#b88fbd',209:'#3c465e'};
const materialColor=(id:number,data=0)=>id===35||id===95?dyes[data]||dyes[0]:id===5?['#c39a60','#785734','#dfd1a1','#b98561','#c27944','#493725'][data]||'#c39a60':palette[id]||'#969a96';

function VoxelCanvas({blocks,entities,example}:{blocks:Voxel[];entities:CodeActor[];example:string}){
 const [actorStatus,setActorStatus]=useState('');const host=useRef<HTMLDivElement>(null);const sceneRef=useRef<{scene:THREE.Scene;actors:ReturnType<typeof createActorLayer>;renderer:THREE.WebGLRenderer|SoftwareRenderer;mesh?:THREE.InstancedMesh;geometry:THREE.BoxGeometry;material:THREE.MeshStandardMaterial}|null>(null);
 useEffect(()=>{const el=host.current;if(!el)return;let renderer:THREE.WebGLRenderer|SoftwareRenderer;try{renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});}catch{renderer=new SoftwareRenderer();}
 const scene=new THREE.Scene();scene.background=new THREE.Color('#081525');renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.35;el.appendChild(renderer.domElement);
 const camera=new THREE.PerspectiveCamera(38,1,.1,1500);const view=example==='shanghai'?[148,117,185,55]:example==='palace'?[143,115,178,11]:example==='cat'?[48,43,85,25]:example==='hokage'?[85,65,110,17]:example==='dragon'?[24,18,29,3]:[10,7.5,15,2.8];camera.position.set(view[0],view[1],view[2]);const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,view[3],0);controls.enableDamping=true;controls.enablePan=true;controls.minDistance=3;controls.maxDistance=450;controls.maxPolarAngle=Math.PI*.49;
 scene.add(new THREE.HemisphereLight(0xe4efff,0x6e6858,2.5));const sun=new THREE.DirectionalLight(0xffdfac,3.2);sun.position.set(-60,160,80);scene.add(sun);const fill=new THREE.DirectionalLight(0x6cb5dd,1);fill.position.set(70,35,-70);scene.add(fill);
 const geometry=new THREE.BoxGeometry(1,1,1),material=new THREE.MeshStandardMaterial({roughness:.86});const actors=createActorLayer(scene,setActorStatus);sceneRef.current={scene,actors,renderer,geometry,material};
 const resize=()=>{const w=el.clientWidth,h=el.clientHeight;if(w<1||h<1)return;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();};const observer=new ResizeObserver(resize);observer.observe(el);resize();let raf=0,last=performance.now();const tick=()=>{raf=requestAnimationFrame(tick);const now=performance.now(),dt=Math.min(.06,(now-last)/1000);last=now;if(document.hidden)return;actors.tick(dt,now/1000);controls.update();renderer.render(scene,camera);};tick();
 return()=>{cancelAnimationFrame(raf);actors.dispose();observer.disconnect();controls.dispose();geometry.dispose();material.dispose();sceneRef.current?.mesh?.dispose();renderer.dispose();sceneRef.current=null;renderer.domElement.remove();};
 },[example]);
 useEffect(()=>{const s=sceneRef.current;if(!s)return;if(s.mesh){s.scene.remove(s.mesh);s.mesh.dispose();}const active=blocks.filter(b=>b[3]!==0);const occupied=new Set(active.map(v=>`${v[0]},${v[1]},${v[2]}`));
 const surface=active.filter(([x,y,z])=>!occupied.has(`${x+1},${y},${z}`)||!occupied.has(`${x-1},${y},${z}`)||!occupied.has(`${x},${y+1},${z}`)||!occupied.has(`${x},${y-1},${z}`)||!occupied.has(`${x},${y},${z+1}`)||!occupied.has(`${x},${y},${z-1}`)).sort((a,b)=>a[1]-b[1]||a[2]-b[2]||a[0]-b[0]);
 const rows:{x:number;y:number;z:number;w:number;c:string}[]=[];for(const [x,y,z,id,data] of surface){const c=materialColor(id,data),p=rows[rows.length-1];if(p&&p.y===y&&p.z===z&&p.c===c&&p.x+p.w===x)p.w++;else rows.push({x,y,z,w:1,c});}
 const mesh=new THREE.InstancedMesh(s.geometry,s.material,Math.max(1,rows.length));const o=new THREE.Object3D(),color=new THREE.Color();rows.forEach((v,i)=>{o.position.set(v.x+(v.w-1)/2,v.y,v.z);o.scale.set(v.w,.985,.985);o.updateMatrix();mesh.setMatrixAt(i,o.matrix);mesh.setColorAt(i,color.set(v.c));});mesh.count=rows.length;mesh.instanceMatrix.needsUpdate=true;if(mesh.instanceColor)mesh.instanceColor.needsUpdate=true;mesh.frustumCulled=false;s.scene.add(mesh);s.mesh=mesh;if(s.renderer instanceof SoftwareRenderer)s.renderer.invalidate();
 },[blocks,example]);
 useEffect(()=>{const s=sceneRef.current;if(!s)return;if(s.renderer instanceof SoftwareRenderer&&entities.length){setActorStatus('角色展示需要浏览器启用 WebGL；建筑仍可预览。');return;}s.actors.set(entities)},[entities,example]);
 return <><div className="python-canvas" ref={host} aria-label="Python 代码生成的三维方块世界"/>{actorStatus&&<div className="python-actor-status" role="status">{actorStatus}</div>}</>;
}

function highlight(code:string){return code.split(/(#[^\n]*|"[^"\n]*"|'[^'\n]*'|\b(?:from|import|for|in|if|else|def|return|continue|True|False)\b|\b\d+(?:\.\d+)?\b)/g).map((s,i)=><span key={i} className={s.startsWith('#')?'code-comment':/^['"]/.test(s)?'code-string':/^(from|import|for|in|if|else|def|return|continue|True|False)$/.test(s)?'code-keyword':/^\d/.test(s)?'code-number':''}>{s}</span>)}

export default function PythonStudio(){
 const [example,setExample]=useState('shanghai'),[code,setCode]=useState(''),[blocks,setBlocks]=useState<Voxel[]>([]),[entities,setEntities]=useState<CodeActor[]>([]),[ready,setReady]=useState(false),[running,setRunning]=useState(false),[log,setLog]=useState('正在载入 Python…'),[error,setError]=useState(false),[changed,setChanged]=useState(false),[loading,setLoading]=useState(true);
 const worker=useRef<Worker|null>(null),map=useRef(new Map<string,Voxel>()),timer=useRef<ReturnType<typeof setTimeout>|null>(null),timeout=useRef<ReturnType<typeof setTimeout>|null>(null),pre=useRef<HTMLPreElement>(null),lines=useRef<HTMLDivElement>(null),original=useRef(''),isRunning=useRef(false);
 function flush(){setBlocks(Array.from(map.current.values()));timer.current=null;}
 function boot(){worker.current?.terminate();setReady(false);const w=new Worker('/python/worker.mjs',{type:'module'});worker.current=w;
 const watchdog=()=>{if(timeout.current)clearTimeout(timeout.current);timeout.current=setTimeout(()=>{if(!isRunning.current)return;worker.current?.terminate();setRunning(false);isRunning.current=false;setReady(false);setError(true);setLog('运行时间过长，已停止。请检查循环，然后重新载入 Python。');},12000);};
 w.onerror=()=>{setError(true);setLog('Python 载入失败，请点击「重新载入」重试。');setReady(false);setRunning(false);isRunning.current=false;};
 w.onmessage=({data:d})=>{if(d.type==='ready'){setReady(true);setLog('Python 已就绪。修改参数，点击运行。');setError(false);}if(d.type==='started'){setLog('Python 执行中…');watchdog();}if(d.type==='heartbeat')watchdog();if(d.type==='stdout')setLog(d.text);
 if(d.type==='patch'){if(d.delta.entities)setEntities(d.delta.entities);for(const v of d.delta.blocks as Voxel[]){const key=`${v[0]},${v[1]},${v[2]}`;if(v[3]===0)map.current.delete(key);else map.current.set(key,v);}if(!timer.current)timer.current=setTimeout(flush,160);}
 if(d.type==='result'){setEntities(d.world.entities||[]);if(timeout.current)clearTimeout(timeout.current);if(timer.current)clearTimeout(timer.current);map.current=new Map((d.world.blocks as Voxel[]).filter(v=>v[3]!==0).map(v=>[`${v[0]},${v[1]},${v[2]}`,v]));flush();setRunning(false);isRunning.current=false;setLog(`执行完成 · ${d.elapsed.toLocaleString()} ms · ${map.current.size.toLocaleString()} 个方块`);setChanged(false);}
 if(d.type==='error'||d.type==='init-error'){if(timeout.current)clearTimeout(timeout.current);setError(true);setLog(d.error);setRunning(false);isRunning.current=false;if(d.type==='init-error')setReady(false);}};
 }
 useEffect(()=>{boot();return()=>{worker.current?.terminate();if(timer.current)clearTimeout(timer.current);if(timeout.current)clearTimeout(timeout.current);};},[]);
 useEffect(()=>{let live=true;Promise.all([fetch(`/demos/${example}.py`).then(r=>{if(!r.ok)throw Error();return r.text();}),fetch(`/demos/${example}.json`).then(r=>{if(!r.ok)throw Error();return r.json();})]).then(([c,w])=>{if(!live)return;setCode(c);original.current=c;setEntities((w as {entities?:CodeActor[]}).entities||[]);map.current=new Map(((w as {blocks:Voxel[]}).blocks).filter(v=>v[3]!==0).map(v=>[`${v[0]},${v[1]},${v[2]}`,v]));flush();setChanged(false);setError(false);setLoading(false);setLog('示例结果已载入。修改参数后点击运行。');}).catch(()=>{if(live){setLoading(false);setError(true);setLog('示例载入失败，请重新打开窗口。');}});return()=>{live=false;};},[example]);
 function run(){if(!ready||running||loading||!code.trim())return;setError(false);setRunning(true);isRunning.current=true;map.current.clear();setBlocks([]);setEntities([]);worker.current?.postMessage({type:'run',code,base:[],world:{blocks:[],entities:[],player:[0,1,8]},player:[0,1,8]});}
 function stop(){worker.current?.terminate();if(timer.current)clearTimeout(timer.current);if(timeout.current)clearTimeout(timeout.current);flush();setRunning(false);isRunning.current=false;setLog('已停止。');boot();}
 return <div className="python-studio"><div className="program-menubar"><span>方块学院 / 编程演示</span><div className="example-tabs">{examples.map(([id,title])=><button key={id} className={example===id?'chosen':''} disabled={running} onClick={()=>{if(example!==id){setLoading(true);setExample(id);setBlocks([]);setEntities([]);}}}>{title}</button>)}</div></div><div className="python-split"><section className="world-pane">{loading&&<AppLoading name={examples.find(e=>e[0]===example)?.[1]} detail="正在载入建筑方块" elapsed/>}<VoxelCanvas blocks={blocks} entities={entities} example={example}/><div className="world-badge"><span className="live-pixel"/>{running?'代码正在改变世界':'MCPI WORLD'}<small>{blocks.length.toLocaleString()} blocks</small></div><div className="world-help">拖动环绕 · 滚轮缩放</div><div className="world-mascot"><span className="cat-form cat-voxel"/><span>工程师 · 脏脏包</span></div></section><section className="editor-pane"><div className="editor-file"><span>◧ {example}.py {changed?'●':''}</span><span>Python 3</span></div><div className="code-editor"><div className="line-numbers" ref={lines}>{code.split('\n').map((_,i)=><div key={i}>{i+1}</div>)}</div><div className="code-input"><pre ref={pre} aria-hidden="true">{highlight(code)}{'\n'}</pre><textarea aria-label="Python 代码编辑器" spellCheck={false} value={code} onChange={e=>{setCode(e.target.value);setChanged(true)}} onScroll={e=>{if(pre.current){pre.current.scrollTop=e.currentTarget.scrollTop;pre.current.scrollLeft=e.currentTarget.scrollLeft;}if(lines.current)lines.current.scrollTop=e.currentTarget.scrollTop;}} onKeyDown={e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();run();}if(e.key==='Tab'){e.preventDefault();const t=e.currentTarget,p=t.selectionStart,end=t.selectionEnd;setCode(code.slice(0,p)+'    '+code.slice(end));setChanged(true);requestAnimationFrame(()=>t.setSelectionRange(p+4,p+4));}}}/></div></div><div className={`python-output ${error?'error':''}`} aria-live="polite"><b>{error?'ERROR':'CONSOLE'}</b><pre>{log}</pre></div><div className="editor-actions"><button onClick={()=>{setCode(original.current);setChanged(false)}} disabled={running}>恢复示例</button>{running?<button className="gold-button" onClick={stop}>■ 停止</button>:<button className="gold-button" disabled={loading||!code||(!ready&&!error)} onClick={ready?run:boot}>{ready?'▶ 运行代码':error?'重新载入':'载入 Python 中…'}</button>}</div></section></div><div className="program-status"><span>建筑与角色 · 方块学院 Python 运行库</span><span>{!ready&&!error?<><i className="engine-loading"/> 正在启动 Python 引擎 · 可先查看建筑</>:'Ctrl + Enter 运行'}</span></div></div>;
}
