'use client';
import {useState,useRef,useEffect} from 'react';
import {Search,Folder,ChevronLeft,ChevronRight} from 'lucide-react';
import {AppId,AppInfo,catalogueApps} from '@/lib/desktop-apps';
import {searchApps} from '@/lib/app-search';
import Icon from './DesktopIcon';
import thumbnails from './catalogue-thumbnails.json';
const optimized=thumbnails as Record<string,{thumb:string;preview:string}>;
function Cover({app,large=false,eager=false}:{app:AppInfo;large?:boolean;eager?:boolean}){const [failed,setFailed]=useState(false);return <div className={`catalogue-cover cover-${app.id}`}>{app.image&&!failed?<img src={optimized[app.image]?.[large?'preview':'thumb']||app.image} alt={app.name} loading={eager?'eager':'lazy'} decoding="async" onError={()=>setFailed(true)}/>:app.id==='zp-afterspan'?<div className="afterspan-wordmark"><small>2076 / 2091</small><b>AFTERSPAN</b><small>VOL. 02</small></div>:<Icon n={app.icon}/>}<span>{app.status||'可体验'}</span></div>}
export default function WorkCatalogue({open,category}:{open:(id:AppId)=>void;category?:string}){
 const [filter,setFilter]=useState(category||'全部作品'),[availability,setAvailability]=useState('全部'),[query,setQuery]=useState(''),[previewId,setPreviewId]=useState<AppId>('zp-benchmark');
 const hover=useRef<ReturnType<typeof setTimeout>|null>(null);
 useEffect(()=>()=>{if(hover.current)clearTimeout(hover.current)},[]);
 const all=(category?catalogueApps.filter(a=>a.category===category):catalogueApps).toSorted((a,b)=>Number(b.id==='zp-benchmark')-Number(a.id==='zp-benchmark'));
 const filtered=all.filter(a=>(filter==='全部作品'||a.category===filter)&&(availability==='全部'||((a.status==='待重构'||a.status==='待补内容')?'待重构':'可体验')===availability));
 const shown=query.trim()?searchApps(query,filtered):filtered;
 const categories=['全部作品','编程与学习','设计','记忆','专注世界','3D 展厅','游戏厅','音乐与影像','文艺复习'];
 const current=shown.find(a=>a.id===previewId)||shown[0];
 function preview(id:AppId,immediate=false){if(hover.current)clearTimeout(hover.current);hover.current=setTimeout(()=>setPreviewId(id),immediate?0:90)}
 return <div className="work-catalogue"><div className="catalogue-address"><Folder size={17}/><b>{category||'作品集'}</b><span>{all.length} 项</span><label><Search size={16}/><input aria-label="搜索作品集" value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索作品…"/></label></div><div className="catalogue-body">{!category&&<nav aria-label="作品分类">{categories.map(c=><button key={c} className={c===filter?'chosen':''} onClick={()=>setFilter(c)}><Folder size={15}/>{c}<small>{c==='全部作品'?all.length:all.filter(a=>a.category===c).length}</small></button>)}</nav>}<section className="catalogue-main"><header className="catalogue-tabs"><div>{['全部','可体验','待重构'].map(s=><button key={s} className={s===availability?'chosen':''} onClick={()=>setAvailability(s)}>{s}</button>)}</div><span>{shown.length} 项 · 移到封面上预览</span></header><div className="catalogue-browser"><div className="catalogue-grid">{shown.map((a,i)=><button key={a.id} className={'catalogue-card '+(current?.id===a.id?'preview-selected':'')} onPointerEnter={()=>preview(a.id)} onPointerLeave={()=>{if(hover.current)clearTimeout(hover.current)}} onFocus={()=>preview(a.id,true)} onClick={()=>open(a.id)}><Cover app={a} eager={i<8}/><div className="catalogue-card-copy"><h3>{a.name}</h3><small>{a.category}<span>打开 ↗</span></small></div></button>)}{!shown.length&&<div className="catalogue-empty"><Search size={26}/><p>没有找到这个作品，换个词试试。</p></div>}</div>{current&&<aside className="catalogue-preview"><header><span>作品预览</span><small>{String(shown.indexOf(current)+1).padStart(2,'0')} / {String(shown.length).padStart(2,'0')}</small></header><Cover key={current.id} app={current} large eager/><div className="catalogue-preview-copy"><small>{current.category}</small><h2>{current.name}</h2><p>{current.description}</p><button className="gold-button" onClick={()=>open(current.id)}>{current.status==='待补内容'||current.status==='待重构'?'查看安排':'打开作品'} ↗</button></div><span className="catalogue-preview-hint">封面先看，喜欢再打开。</span></aside>}</div></section></div><footer className="catalogue-status"><span>CTY STUDIO · 点击打开 · Tab 切换预览</span><button onClick={()=>open('zp-desktop')}>重构进度.txt</button></footer></div>
}
export function GalleryShelf({open}:{open:(id:AppId)=>void}){const works=catalogueApps.filter(a=>a.category==='3D 展厅'),[index,setIndex]=useState(0),a=works[index];const move=(delta:number)=>setIndex(i=>(i+delta+works.length)%works.length);return <div className="gallery-shelf" tabIndex={0} onKeyDown={e=>{if(e.key==='ArrowRight'){e.preventDefault();move(1)}if(e.key==='ArrowLeft'){e.preventDefault();move(-1)}}}><div className="gallery-heading"><div><span>CTY STUDIO · WORLDS</span><h2>四个世界，随时出发</h2></div><span>{String(index+1).padStart(2,'0')} / 04</span></div><div className="gallery-exhibit"><button aria-label="上一件作品" className="gallery-step" onClick={()=>move(-1)}><ChevronLeft/></button><button className="gallery-art" onClick={()=>open(a.id)}><Cover key={a.id} app={a} large eager/><span>{(a.status==='待重构'||a.status==='待补内容')?'查看重构安排':'进入展厅'}</span></button><button aria-label="下一件作品" className="gallery-step" onClick={()=>move(1)}><ChevronRight/></button></div><div className="gallery-caption"><div><span>3D 展厅</span><h3>{a.name}</h3><p>{a.description}</p></div><button className="gold-button" onClick={()=>open(a.id)}>{(a.status==='待重构'||a.status==='待补内容')?'查看安排':'进入展厅'}</button></div><div className="gallery-select">{works.map((w,i)=><button key={w.id} onClick={()=>setIndex(i)} className={index===i?'chosen':''}><span>{String(i+1).padStart(2,'0')}</span>{w.name}</button>)}</div></div>}
