'use client';
import {useState} from 'react';
import {duelWinner,region,seaPlacement,seaPoints,seaScore,type SeaCard,type SeaBoard} from './rules';
const faces=['','A','2','3','4','5','6','7','8','9','10','J','Q','K'];
function Card({value,selected=false,onClick,disabled=false,back=false}:{value?:number;selected?:boolean;onClick?:()=>void;disabled?:boolean;back?:boolean}){return <button className={`playing-card ${selected?'selected':''} ${back?'card-back':''}`} disabled={disabled} onClick={onClick} aria-label={back?'背面牌':`选择 ${faces[value||1]}`}><b>{back?'✦':faces[value||1]}</b><span>{back?'☾':(value||0)>10?'♜':'♦'}</span><b>{back?'✦':faces[value||1]}</b></button>}
export function Jianfeng(){
 const initial=()=>Array.from({length:13},(_,i)=>i+1);
 const [hand,setHand]=useState(initial),[other,setOther]=useState(initial),[points,setPoints]=useState([0,0]),[round,setRound]=useState(1),[phase,setPhase]=useState<'select'|'reveal'|'result'|'discard'>('select'),[picked,setPicked]=useState<number|null>(null),[enemy,setEnemy]=useState<number|null>(null),[committed,setCommitted]=useState(()=>1+Math.floor(Math.random()*13)),[last,setLast]=useState(0),[enemyLast,setEnemyLast]=useState(0),[identity,setIdentity]=useState(0),[used,setUsed]=useState(false),[log,setLog]=useState<string[]>(['双方同时出牌，先得 2 分者胜。']),[discard,setDiscard]=useState<number[]>([]),[rule,setRule]=useState(false);
 const ended=points.some(n=>n>=2)||hand.length===0,identities=[['红桃 J','相差至少 5 时，阻止对手得分。'],['红桃 Q','亮出对手至多 5 张牌，限定本次选择。'],['红桃 K','确认后、揭晓前，交换双方出牌。']], [identityName,identityText]=identities[identity];
 function play(v:number){if(phase==='discard'){const smaller=hand.filter(n=>n<last);if(smaller.length&&!smaller.includes(v))return;const enemyCandidates=other.filter(n=>n<enemyLast),removed=(enemyCandidates.length?enemyCandidates:other)[0],remaining=other.filter(n=>n!==removed);setHand(h=>h.filter(n=>n!==v));setOther(remaining);setDiscard(d=>[v,removed,...d]);setCommitted(remaining[Math.floor(Math.random()*remaining.length)]);setPhase('select');return}if(phase!=='select'||ended)return;setPicked(v);setEnemy(committed);setPhase('reveal')}
 function resolve(){if(picked===null||enemy===null)return;const result=duelWinner(picked,enemy),blocked=result===1&&identity===0&&used&&Math.abs(picked-enemy)>=5;setPoints(p=>p.map((v,i)=>v+(i===result&&!blocked?1:0)));setLog(l=>[`第 ${round} 回合：${faces[picked]} 对 ${faces[enemy]} · ${blocked?'红桃 J 阻止得分':result===-1?'平局':result===0?'你 +1':'对手 +1'}`,...l]);setHand(h=>h.filter(n=>n!==(identity===2&&used?enemy:picked)));setOther(h=>h.filter(n=>n!==(identity===2&&used?picked:enemy)));setLast(picked);setEnemyLast(enemy);setDiscard(d=>[picked,enemy,...d]);setPhase('result')}
 function skill(){if(used)return;if(identity===2&&phase==='reveal'){setPicked(enemy);setEnemy(picked)}else if(identity===1&&phase==='select'){const pool=[...other].sort(()=>Math.random()-.5).slice(0,5);setCommitted(pool[Math.floor(Math.random()*pool.length)]);setLog(l=>['对手本轮只能从 '+pool.map(n=>faces[n]).join('、')+' 中出牌。',...l])}else if(identity!==0)return;setUsed(true)}
 function next(){setRound(r=>r+1);setPhase('discard');setPicked(null);setEnemy(null);setIdentity(Math.floor(Math.random()*3));setUsed(false)}
 function reset(){setHand(initial());setOther(initial());setPoints([0,0]);setRound(1);setPhase('select');setPicked(null);setEnemy(null);setCommitted(1+Math.floor(Math.random()*13));setUsed(false);setIdentity(0);setDiscard([]);setLog(['新的练习局开始。'])}
 return <div className="arcade-app jianfeng-app"><header className="arcade-toolbar"><div><small>CARD DUEL</small><h2>见缝插针</h2></div><span>练习局 · 三种红桃身份</span><button onClick={()=>setRule(!rule)}>规则</button><button onClick={reset}>新开一局</button></header>{rule&&<div className="arcade-rules">双方各持 A–K，同时出一张牌。点数相差 1–3，大牌得分；差值更大，小牌得分；A 遇 K，A 胜；同点平局。先到 2 分胜。第二回合起，先弃掉一张小于自己上一张出牌的牌；没有较小牌时可任弃一张。本地练习保留三种红桃身份，完整身份抽选与成就不在此演示内。</div>}<div className="duel-layout"><aside className="duel-scores"><section><small>深夜对手</small><strong>{points[1]}</strong><span>手牌 {other.length}</span><Card back disabled/></section><p>第 {round} 回合</p><section><small>你</small><strong>{points[0]}</strong><span>手牌 {hand.length}</span><h4>{identityName}</h4><p>{identityText}</p><button disabled={used||ended||(identity===2?phase!=='reveal':identity===1?phase!=='select':phase!=='select'&&phase!=='reveal')} onClick={skill}>{used?'本回合已使用':'使用身份'}</button></section></aside><main className="duel-table"><div className="duel-stage"><div><small>对手出牌</small>{enemy&&phase==='result'?<Card value={enemy} disabled/>:<Card back disabled/>}</div><div className="duel-message"><span>♞</span><b>{ended?(points[0]>points[1]?'你赢了！':points[0]<points[1]?'对手获胜':'平局'):phase==='discard'?'先弃一张牌':phase==='select'?'选择一张出牌':phase==='reveal'?'双方已确认':'回合结束'}</b><p>{phase==='discard'?`优先弃掉小于 ${faces[last]} 的牌`:'恰好大一点，才能赢。'}</p>{phase==='reveal'&&<button className="arcade-primary" onClick={resolve}>揭晓并结算</button>}{phase==='result'&&!ended&&<button className="arcade-primary" onClick={next}>下一回合</button>}{ended&&<button onClick={reset}>再来一局</button>}</div><div><small>你的出牌</small>{phase==='reveal'&&identity===2&&used?<Card back disabled/>:picked?<Card value={picked} disabled/>:<div className="empty-card">未选择</div>}</div></div><p className="hand-label">{phase==='discard'?'请选择弃牌':'你的手牌'} <span>{phase==='select'?'对手已暗中选定':''}</span></p><div className="duel-hand">{hand.map(n=><Card key={n} value={n} selected={picked===n&&!(phase==='reveal'&&identity===2&&used)} onClick={()=>play(n)} disabled={ended||(phase!=='select'&&phase!=='discard')||(phase==='discard'&&hand.some(n=>n<last)&&n>=last)}/>)}</div></main><aside className="duel-log"><h4>普通弃牌堆</h4><p>{discard.map(n=>faces[n]).join(' · ')||'暂无弃牌'}</p><h4>本局记录</h4>{log.slice(0,9).map((s,i)=><p key={i}>{s}</p>)}</aside></div></div>
}
let nextId=1;
const fishTypes=[{name:'螃蟹',size:1,weight:0},{name:'珍珠牡蛎',size:1,weight:1},{name:'二阶鱼',size:2,weight:2},{name:'墨鱼',size:3,weight:2},{name:'鳕鱼',size:3,weight:3},{name:'四阶鱼',size:4,weight:4},{name:'五阶鱼',size:5,weight:5}];
const fish=():SeaCard=>({...fishTypes[Math.floor(Math.random()*fishTypes.length)],id:nextId++});
const source=():SeaCard=>({id:nextId++,size:0,weight:0,name:'源',source:true});
type SeaState={board:SeaBoard;hand:SeaCard[];enemy:SeaCard[];shop:SeaCard[];points:number[];round:number;draws:number;actions:number;deck:number;selected:number|null;message:string;done:boolean;acted:boolean};
export const newSea=():SeaState=>({board:Array(23).fill(null),hand:[fish(),fish(),source()],enemy:[fish(),fish(),source()],shop:[fish(),fish(),fish()],points:[0,0],round:1,draws:1,actions:1,deck:123,selected:null,message:'准备阶段：从主牌堆或源牌堆抽 1 张。',done:false,acted:false});
export function Aquas(){
 const [s,set]=useState<SeaState>(newSea),[rules,setRules]=useState(false),[log,setLog]=useState<string[]>([]);const card=s.hand.find(c=>c.id===s.selected),sources=s.hand.filter(c=>c.source).length;
 function draw(isSource:boolean){if(!s.draws||s.done||(!isSource&&s.deck<=0))return;const c=isSource?source():fish();set(v=>({...v,hand:[...v.hand,c],draws:v.draws-1,deck:v.deck-(isSource?0:1),message:v.draws===1?'选择手牌，再点击棋盘位置。':'还可以抽 1 张。'}))}
 function place(index:number){if(!card||s.draws||s.actions===0||s.done)return;const result=seaPlacement(s.board,index,card,0);if(!result.ok){set(v=>({...v,message:result.message}));return}set(v=>({...v,board:v.board.map((old,i)=>i===index?result.stack!:old),hand:v.hand.filter(c=>c.id!==card.id),actions:v.actions-1,acted:true,selected:null,message:result.message}));setLog(l=>[result.message,...l])}
 function buy(index:number){const item=s.shop[index],cost=item.size>2?2:1;if(s.draws||s.actions<=0||sources<cost||s.done)return;const paid=new Set(s.hand.filter(c=>c.source).slice(0,cost).map(c=>c.id));set(v=>({...v,hand:[...v.hand.filter(c=>!paid.has(c.id)),item],shop:v.shop.filter((_,i)=>i!==index),actions:v.actions-1,acted:true,message:'购买完成。商店在下一轮补充。'}))}
 function end(){if(s.draws||s.done)return;if(s.hand.length>6){set(v=>({...v,message:'手牌上限 6 张。选牌后点「弃掉选中牌」再结束回合。'}));return}let remainingDeck=s.deck;const aiDraw=remainingDeck>0?(remainingDeck--,fish()):source();let board=[...s.board],enemy=[...s.enemy,aiDraw,source()],p=[s.points[0]+seaScore(board,0),s.points[1]],aiActions=p[0]-p[1]>=30?3:2;let moved=0;
  for(let a=0;a<aiActions;a++){const choices=enemy.flatMap(c=>board.map((_,i)=>({c,i,r:seaPlacement(board,i,c,1)})).filter(x=>x.r.ok&&x.r.stack).map(x=>({...x,value:region(x.i)*5+(board[x.i]?.owner===0?4:0)+(x.r.stack?.size||0)-(board[x.i]?.owner===1?8:0)}))).sort((a,b)=>b.value-a.value);if(!choices.length)break;const choice=choices[0];board[choice.i]=choice.r.stack!;enemy=enemy.filter(c=>c.id!==choice.c.id);moved++}
  p[1]+=seaScore(board,1);const shop=[...s.shop];while(shop.length<3&&remainingDeck>0){shop.push(fish());remainingDeck--}const done=board.every(Boolean)||remainingDeck===0||(!s.acted&&moved===0);const message=done?`对局结束 · ${p[0]===p[1]?'平局':p[0]>p[1]?'你获胜':'深海对手获胜'}`:`第 ${s.round+1} 轮：先抽 2 张，再行动。`;set({...s,board,enemy:enemy.slice(-6),points:p,round:s.round+1,draws:done?0:2,actions:p[1]-p[0]>=30?3:2,deck:remainingDeck,shop,acted:false,selected:null,done,message});setLog(l=>[`第 ${s.round} 轮：你 +${seaScore(s.board,0)}，对手部署 ${moved} 次，+${seaScore(board,1)}。`,...l])
 }
 return <div className="arcade-app aquas-app"><header className="arcade-toolbar"><div><small>DEEP SEA DUEL</small><h2>♆ AQUAS</h2></div><span>核心规则练习 · 第 {s.round} 轮</span><button onClick={()=>setRules(!rules)}>规则</button><button onClick={()=>{set(newSea());setLog([])}}>新对局</button></header>{rules&&<div className="arcade-rules">外圈 / 内圈 / 核心需体型 ≥ 1 / 2 / 3，每次自己回合结束积 1 / 2 / 3 分。抽 2 张，行动 2 次；先手首轮各 1。体型 4 / 5 入场需吞掉至少 1 / 2 张牌；重量上限为体型 × 2，超重整叠沉底。源可独立计 1 分，或增大自己的鱼；源不能在核心，不能吞敌方独立源。手牌最多 6。棋盘占满或牌堆耗尽结算。本地练习保留部署、吞噬、源、商店与计分，使用标准体型练习牌组，省略原作的鱼种特殊能力和工具卡。</div>}<div className="aquas-layout"><div className="sea-board"><svg viewBox="0 0 100 100" aria-hidden="true">{seaPoints.slice(1,7).map((p,i)=><path key={i} d={`M50 50 L${p.x} ${p.y}`} />)}<circle cx="50" cy="50" r="43"/><path d={seaPoints.slice(1,7).map((p,i)=>(i?'L':'M')+p.x+' '+p.y).join(' ')+'Z'}/></svg>{seaPoints.map((p,i)=>{const cell=s.board[i];return <button key={i} className={`sea-cell region-${region(i)} ${cell?'owner-'+cell.owner:''} ${card&&seaPlacement(s.board,i,card,0).ok?'legal':''}`} style={{left:p.x+'%',top:p.y+'%'}} onClick={()=>place(i)} aria-label={`${i===0?'核心':i<7?'内圈':'外圈'} ${i+1} ${cell?.name||'空位'}`}><b>{cell?(cell.size===0?'◉':'鱼'):`≥${region(i)}`}</b><small>{cell?`${cell.name} ${cell.size||''}`:`${region(i)} 分`}</small>{cell&&<i>{cell.weight} / {Math.max(1,cell.size*2)}</i>}</button>})}<span className="sea-ocean-word">AQUAS · ABYSS</span></div><aside className="sea-console"><div className="sea-scores"><div>你<strong>{s.points[0]}</strong><small>+{seaScore(s.board,0)} / 回合</small></div><div>深海对手<strong>{s.points[1]}</strong><small>+{seaScore(s.board,1)} / 回合</small></div></div><p className="sea-message" role="status">{s.message}</p><div className="sea-actions"><button disabled={!s.draws||s.done||s.deck===0} onClick={()=>draw(false)}>主牌堆 · {s.deck}</button><button disabled={!s.draws||s.done} onClick={()=>draw(true)}>抽一张源 ◉</button><span>待抽 {s.draws} · 行动 {s.actions}</span></div><h4>你的手牌 <small>{s.hand.length} / 6</small></h4><div className="sea-hand">{s.hand.map(c=><button key={c.id} className={s.selected===c.id?'selected':''} onClick={()=>set(v=>({...v,selected:c.id}))}><span>{c.source?'◉':'鱼'}</span><b>{c.name}</b><small>{c.source?'源 · 0 重量':`体型 ${c.size} · 重 ${c.weight}`}</small></button>)}</div><div className="sea-shop"><h4>你的商店 · 手持源 {sources}</h4><div>{s.shop.map((c,i)=><button key={c.id} disabled={s.draws>0||s.actions===0||sources<(c.size>2?2:1)||s.done} onClick={()=>buy(i)}>{c.name}<small>◉ {c.size>2?2:1}</small></button>)}</div></div><div className="sea-actions"><button className="arcade-primary" disabled={s.draws>0||s.done} onClick={end}>结束回合</button><button disabled={!card||s.done} onClick={()=>set(v=>({...v,hand:v.hand.filter(c=>c.id!==v.selected),selected:null,message:'已弃牌。'}))}>弃掉选中牌</button></div><div className="sea-log">{log.slice(0,4).map((line,i)=><p key={i}>{line}</p>)}</div></aside></div></div>
}
