'use client';
import {useAnimationClock} from "@/app/components/AnimationScope";
import {useEffect,useRef,useState} from 'react';
const clamp=(n:number,a:number,b:number)=>Math.max(a,Math.min(b,n));
type Enemy={x:number;y:number;hp:number;kind:number;phase:number};
export default function Hunger(){
 const animationClock=useAnimationClock(),{requestFrame,cancelFrame}=animationClock;
 const canvas=useRef<HTMLCanvasElement>(null),input=useRef({x:480,y:300,keys:new Set<string>(),bite:false,dash:false}),[run,setRun]=useState(0),[state,setState]=useState<'hub'|'play'|'upgrade'|'over'>('hub'),live=useRef(state),[hud,setHud]=useState({hp:100,xp:0,level:1,kills:0,time:0}),stats=useRef({hp:100,xp:0,level:1,kills:0,time:0,power:1,speed:1,range:1}),[chosen,setChosen]=useState(''),[journal,setJournal]=useState(false);
 useEffect(()=>{live.current=state;if(state==='play')canvas.current?.focus()},[state,run]);
 useEffect(()=>{if(state==='hub')return;const c=canvas.current,ctx=c?.getContext('2d');if(!c||!ctx)return;let raf=0,last=0,spawn=0,attack=0,hurt=0,dash=0,angle=0;const enemies:Enemy[]=[];let particles:{x:number;y:number;life:number}[]=[];
  const frame=(now:number)=>{raf=requestFrame(frame);const dt=Math.min(.04,(now-last)/1000||0);last=now;if(document.hidden||!c!.clientWidth)return;const st=stats.current,p=input.current;
   if(live.current==='play'){st.time+=dt;spawn-=dt;attack-=dt;hurt-=dt;dash-=dt;let dx=(p.keys.has('d')||p.keys.has('ArrowRight')?1:0)-(p.keys.has('a')||p.keys.has('ArrowLeft')?1:0),dy=(p.keys.has('s')||p.keys.has('ArrowDown')?1:0)-(p.keys.has('w')||p.keys.has('ArrowUp')?1:0);if(dx||dy){angle=Math.atan2(dy,dx);const speed=(p.dash&&dash<=0?650:150)*st.speed,mag=Math.hypot(dx,dy);p.x=clamp(p.x+dx/mag*dt*speed,45,915);p.y=clamp(p.y+dy/mag*dt*speed,95,555);if(p.dash&&dash<=0)dash=.55}if(spawn<=0&&enemies.length<30){spawn=Math.max(.45,1.2-st.time*.008);const a=Math.random()*Math.PI*2;enemies.push({x:clamp(p.x+Math.cos(a)*330,40,920),y:clamp(p.y+Math.sin(a)*280,90,550),hp:2+Math.floor(st.time/40),kind:Math.floor(Math.random()*3),phase:Math.random()*6})}for(let i=enemies.length-1;i>=0;i--){const e=enemies[i],dist=Math.hypot(e.x-p.x,e.y-p.y),speed=e.kind===1?64:43;e.x+=(p.x-e.x)/(dist||1)*dt*speed;e.y+=(p.y-e.y)/(dist||1)*dt*speed;e.phase+=dt*6;if(dist<27&&hurt<=0){st.hp-=9;hurt=.8}if(p.bite&&attack<=0&&dist<78*st.range){e.hp-=st.power;if(e.hp<=0){enemies.splice(i,1);st.kills++;st.xp++;for(let j=0;j<6;j++)particles.push({x:e.x+(Math.random()-.5)*35,y:e.y+(Math.random()-.5)*35,life:.6})}}}if(p.bite&&attack<=0)attack=.45;if(st.xp>=st.level*5){st.xp-=st.level*5;st.level++;setState('upgrade');live.current='upgrade'}if(st.hp<=0){st.hp=0;setState('over');live.current='over'}if(Math.floor(st.time*5)!==Math.floor((st.time-dt)*5))setHud({...st})}
   ctx!.fillStyle='#453b32';ctx!.fillRect(0,0,960,600);for(let y=75;y<600;y+=48)for(let x=0;x<960;x+=48){ctx!.fillStyle=(x/48+y/48)%2?'#7b6450':'#75604e';ctx!.fillRect(x+1,y+1,46,46)}ctx!.fillStyle='#c39b65';ctx!.fillRect(0,20,960,50);for(let x=30;x<960;x+=150){ctx!.fillStyle='#43372c';ctx!.fillRect(x,28,100,29);ctx!.fillStyle='#a78d68';for(let n=0;n<3;n++){ctx!.beginPath();ctx!.arc(x+20+n*27,42,9,0,Math.PI*2);ctx!.fill()}}ctx!.fillStyle='#f7cf79';ctx!.font='12px monospace';ctx!.fillText('TRAINING KITCHEN / BITE, DODGE, GROW',28,16);
   for(const e of enemies){ctx!.save();ctx!.translate(e.x,e.y+Math.sin(e.phase)*2);ctx!.fillStyle='#20191355';ctx!.beginPath();ctx!.ellipse(0,15,20,8,0,0,7);ctx!.fill();if(e.kind===0){ctx!.fillStyle='#b4412b';ctx!.beginPath();ctx!.arc(0,0,19,0,7);ctx!.fill();ctx!.fillStyle='#558148';ctx!.fillRect(-5,-24,11,10)}else if(e.kind===1){ctx!.fillStyle='#d6aa56';for(let j=0;j<4;j++)ctx!.fillRect(-17+j*9,-22+(j%2)*4,7,36);ctx!.fillStyle='#a34227';ctx!.fillRect(-18,0,36,20)}else{ctx!.fillStyle='#d9ab65';ctx!.beginPath();ctx!.ellipse(0,-7,23,14,0,Math.PI,0);ctx!.fill();ctx!.fillRect(-22,12,44,8);ctx!.fillStyle='#6a3525';ctx!.fillRect(-24,-3,48,15);ctx!.fillStyle='#70a14a';ctx!.fillRect(-23,6,46,5)}ctx!.fillStyle='#241e20';ctx!.fillRect(-10,-4,6,6);ctx!.fillRect(6,-4,6,6);ctx!.restore()}
   ctx!.save();ctx!.translate(p.x,p.y);ctx!.fillStyle='#1a141344';ctx!.beginPath();ctx!.ellipse(0,23,27,9,0,0,7);ctx!.fill();ctx!.fillStyle=hurt>.6?'#85545a':'#171b22';ctx!.beginPath();ctx!.ellipse(0,0,25,24+Math.sin(st.time*8)*1.5,0,0,7);ctx!.fill();ctx!.fillStyle='#eef1ce';ctx!.fillRect(-12,-7,6,8);ctx!.fillRect(7,-7,6,8);ctx!.fillStyle='#874e4a';ctx!.fillRect(-7,8,15,5);if(attack>.24){ctx!.strokeStyle='#ffda8a';ctx!.lineWidth=5;ctx!.beginPath();ctx!.arc(0,0,62*st.range,angle-.95,angle+.95);ctx!.stroke()}ctx!.restore();particles=particles.filter(v=>{v.life-=dt;ctx!.fillStyle='#f2ca7d';ctx!.fillRect(v.x,v.y-=dt*35,4,4);return v.life>0});
  };raf=requestFrame(frame);return()=>cancelFrame(raf)
 },[run,state==='hub']);
 function start(){stats.current={hp:100,xp:0,level:1,kills:0,time:0,power:1,speed:1,range:1};input.current={x:480,y:300,keys:new Set(),bite:false,dash:false};setHud({...stats.current});setRun(v=>v+1);setState('play');live.current='play';setChosen('')}
 function upgrade(n:number){const s=stats.current;if(n===0)s.power++;if(n===1)s.speed+=.2;if(n===2){s.range+=.25;s.hp=Math.min(100,s.hp+25)}setChosen(['棒棒糖 · 咬击 +1','冰淇淋 · 移速 +20%','苹果派 · 范围与生命'][n]);setState('play');live.current='play';canvas.current?.focus()}
 return <div className="arcade-app hunger-app"><header className="arcade-toolbar"><div><small>HUNGER GUY</small><h2>饿货 · 训练厨房</h2></div><span>核心玩法演示</span><button onClick={()=>setJournal(!journal)}>创作画面</button><button onClick={()=>setState('hub')}>返回食物船</button></header>{journal&&<div className="game-reference-strip"><img src="/works/arcade/hunger-guy.webp" alt="饿货原设计的厨房战斗"/><img src="/works/arcade/hunger-guy-hub.webp" alt="食物船据点原设计"/></div>}{state==='hub'?<div className="game-cover-scene" style={{backgroundImage:"url('/works/arcade/hunger-guy-hub.webp')"}}><div><small>FOOD SHIP / v0.1</small><h2>今天，厨房也会反咬一口。</h2><p>扮演饥饿小黑球，闪避食物怪物、咬击进食，升级后选一种食物强化。</p><button className="arcade-primary" onClick={start}>进入训练厨房</button><p className="fine-print">Godot 桌面作品的浏览器精华演示。完整关卡、Boss 与武器系统仍在原项目中制作。</p></div></div>:<><div className="hunger-hud"><span>生命 <b>{hud.hp}</b></span><span>Lv.{hud.level} · XP {hud.xp}/{hud.level*5}</span><span>吃掉 {hud.kills} 份</span><span>{Math.floor(hud.time)} 秒</span><small>{chosen}</small></div><div className="action-canvas"><canvas ref={canvas} width={960} height={600} tabIndex={0} onPointerDown={e=>{e.currentTarget.focus();input.current.bite=true}} onPointerUp={()=>input.current.bite=false} onPointerCancel={()=>input.current.bite=false} onPointerLeave={()=>input.current.bite=false} onKeyDown={e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown',' ','Shift','w','a','s','d','j'].includes(e.key)){e.preventDefault();input.current.keys.add(e.key);if(e.key===' '||e.key==='j')input.current.bite=true;if(e.key==='Shift')input.current.dash=true}}} onKeyUp={e=>{input.current.keys.delete(e.key);if(e.key===' '||e.key==='j')input.current.bite=false;if(e.key==='Shift')input.current.dash=false}} onBlur={()=>{input.current.keys.clear();input.current.bite=false;input.current.dash=false}} aria-label="训练厨房，WASD移动，空格咬击，Shift闪避"/>{state==='upgrade'&&<div className="game-overlay"><h2>吃饱了，选一个强化。</h2><div className="upgrade-options">{['棒棒糖｜咬击 +1','冰淇淋｜移动更快','苹果派｜范围 +25% / 恢复 25'].map((v,i)=><button key={v} onClick={()=>upgrade(i)}>{v}</button>)}</div></div>}{state==='over'&&<div className="game-overlay"><h2>厨房暂时赢了。</h2><p>生存 {Math.floor(stats.current.time)} 秒 · 吃掉 {stats.current.kills} 份食物</p><button className="arcade-primary" onClick={start}>再开一局</button></div>}</div><div className="touch-controls">{[['a','←'],['w','↑'],['s','↓'],['d','→']].map(([key,label])=><button key={key} aria-label={'移动 '+label} onPointerDown={e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);input.current.keys.add(key)}} onPointerUp={()=>input.current.keys.delete(key)} onPointerCancel={()=>input.current.keys.delete(key)}>{label}</button>)}<button onPointerDown={e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);input.current.bite=true}} onPointerUp={()=>input.current.bite=false} onPointerCancel={()=>input.current.bite=false}>咬一口</button></div></>}<footer className="arcade-footer">本地演示操作：WASD / 方向键移动 · 空格 / J / 点击咬击 · Shift 闪避</footer></div>
}
