export type Furniture={kind:string;x:number;y:number};
export type JourneyState={version:1;title:string;segments:number;duration:number;phase:'idle'|'focus'|'paused'|'break'|'done';left:number;done:number;deadline:number;coins:number;xp:number;focusSeconds:number;completedSegments:number;notes:string[];furniture:Furniture[]};
export const journeyPlaces=['风车村庄','林间小径','山谷图书馆','萤石矿洞'];
export const furnitureKinds=['绿植','书架','灯','桌子'];
export function newJourney():JourneyState{return {version:1,title:'把今天重要的一件事做好',segments:3,duration:1500,phase:'idle',left:1500,done:0,deadline:0,coins:0,xp:0,focusSeconds:0,completedSegments:0,notes:[],furniture:[{kind:'桌子',x:45,y:50},{kind:'绿植',x:72,y:36}]}}
export function advanceJourney(s:JourneyState,now:number):JourneyState{if(s.phase!=='focus')return s;const left=Math.max(0,Math.ceil((s.deadline-now)/1000));if(left>0)return left===s.left?s:{...s,left};const done=s.done+1,note=`${new Date(now).toLocaleDateString('zh-CN')} · ${s.duration===30?'体验':'专注'}委托 ${done}/${s.segments}｜${journeyPlaces[s.done%4]} · ${s.title}。获得 12 XP、8 金币。`;return {...s,left:0,done,deadline:0,phase:done>=s.segments?'done':'break',coins:s.coins+8,xp:s.xp+12,focusSeconds:s.focusSeconds+(s.duration===30?0:s.duration),completedSegments:s.completedSegments+1,notes:[note,...s.notes].slice(0,200)}}
export function startJourney(s:JourneyState,now:number):JourneyState{if(!['idle','break','paused'].includes(s.phase))return s;const left=s.phase==='paused'?Math.max(1,s.left):s.duration;return {...s,phase:'focus',left,deadline:now+left*1000}}
export function pauseJourney(s:JourneyState,now:number):JourneyState{const current=advanceJourney(s,now);return current.phase==='focus'?{...current,phase:'paused',deadline:0}:current}
export function readJourneySnapshot(value:unknown,now:number):JourneyState{const fresh=newJourney();if(!value||typeof value!=='object')return fresh;const raw=value as Record<string,unknown>;if(raw.version!==1)return fresh;const number=(key:string,fallback:number,min:number,max:number)=>typeof raw[key]==='number'&&Number.isFinite(raw[key])?Math.max(min,Math.min(max,Math.floor(raw[key] as number))):fallback;const duration=[30,900,1500].includes(raw.duration as number)?raw.duration as number:1500,segments=number('segments',3,1,5),done=number('done',0,0,segments);let phase=typeof raw.phase==='string'&&['idle','focus','paused','break','done'].includes(raw.phase)?raw.phase as JourneyState['phase']:'idle';const deadline=number('deadline',0,0,now+duration*1000);if(done>=segments&&phase!=='idle')phase='done';if(phase==='focus'&&deadline===0)phase='paused';const restored:JourneyState={version:1,title:typeof raw.title==='string'?raw.title.slice(0,60):fresh.title,segments,duration,phase,left:number('left',duration,0,duration),done,deadline,coins:number('coins',0,0,1000000),xp:number('xp',0,0,1000000),focusSeconds:number('focusSeconds',0,0,100000000),completedSegments:number('completedSegments',0,0,100000),notes:Array.isArray(raw.notes)?raw.notes.filter((v):v is string=>typeof v==='string').slice(0,200).map(v=>v.slice(0,400)):[],furniture:Array.isArray(raw.furniture)?raw.furniture.filter((v):v is Furniture=>!!v&&typeof v==='object'&&furnitureKinds.includes(v.kind)&&Number.isFinite(v.x)&&Number.isFinite(v.y)).slice(0,60).map(v=>({kind:v.kind,x:Math.max(6,Math.min(94,v.x)),y:Math.max(30,Math.min(90,v.y))})):fresh.furniture};return advanceJourney(restored,now)}
