"use client";
import {useEffect,useMemo,useRef,useState,type CSSProperties} from 'react';
import {ArrowUpRight,Volume2,VolumeX,Monitor,Minimize2,Maximize2,X,Folder,Search,ChevronLeft,ChevronRight,Disc3,Terminal as TerminalIcon} from 'lucide-react';
import * as Context from '@/components/ui/context-menu';
const DesktopDialog=dynamic(()=>import('./components/DesktopDialog'),{ssr:false});
import CatAssistantLauncher from '@/components/cat-assistant-launcher';
const HomeGallery=dynamic(()=>import('./components/Galleries').then(m=>m.HomeGallery),{ssr:false,loading:()=> <AppLoading name="3D 房屋设计"/>});
const PhotoAlbum=dynamic(()=>import('./components/Galleries').then(m=>m.PhotoAlbum),{ssr:false,loading:()=> <AppLoading name="Q版相册"/>});
const StickerAlbum=dynamic(()=>import('./components/Galleries').then(m=>m.StickerAlbum),{ssr:false,loading:()=> <AppLoading name="脏脏包表情"/>});
const MusicPlayer=dynamic(()=>import('./components/MusicPlayer'),{ssr:false,loading:()=> <AppLoading name="唱片机"/>});
import {MusicProvider,useMusicControls} from './components/MusicContext';
const Terminal=dynamic(()=>import('./components/Terminal'),{ssr:false,loading:()=> <AppLoading name="终端"/>});
import dynamic from 'next/dynamic';
import AppLoading,{LoadedFrame} from './components/AppLoading';
import {dissolveWindow,cancelWindowDissolve} from './components/window-particles';
const PythonStudio=dynamic(()=>import('./components/PythonStudio'),{ssr:false,loading:()=> <AppLoading name="Minecraft.py" detail="正在载入方块引擎"/>});
import {apps,desktopApps,getApp,AppId,AppInfo} from '@/lib/desktop-apps';
import Icon from './components/DesktopIcon';
const WorkCatalogue=dynamic(()=>import('./components/WorkCatalogue'),{ssr:false,loading:()=> <AppLoading name="作品集"/>});
const GalleryShelf=dynamic(()=>import('./components/WorkCatalogue').then(m=>m.GalleryShelf),{ssr:false,loading:()=> <AppLoading name="3D 展厅"/>});
const LocalWork=dynamic(()=>import('./components/LocalWork'),{ssr:false,loading:()=> <AppLoading name="正在打开作品" detail="载入演示程序"/>});
import DesktopAtmosphere from './components/DesktopAtmosphere';
import {createCompanionSound} from '@/lib/companion-sound';
import MoonCorner from './components/MoonCorner';
const MoonSpace=dynamic(()=>import('./components/MoonSpace'),{ssr:false});
import SceneBackdrop from './components/SceneBackdrop';
import {AnimationScope} from './components/AnimationScope';
import {coveringWindow,windowCanAnimate} from '@/lib/window-visibility';
import {appEntries,resolveApp} from '@/lib/app-search';
import MobileHome,{MobileBar,MobileDock} from './components/MobileHome';
import StartMenu from './components/StartMenu';
import {wallpapers,moonPhases,emptyTraffic,type WallpaperId} from '@/lib/desktop-scenery';
const QuickSearch=dynamic(()=>import('./components/QuickSearch'),{ssr:false});
const MobileActions=dynamic(()=>import('./components/MobileActions'),{ssr:false});
import {BootSequence,Calendar,DesktopStars} from './components/DesktopExtras';
type WindowState={id:AppId;x:number;y:number;w:number;h:number;min:boolean;max:boolean;z:number;motion?:'closing'|'minimizing'};
function OriginalApp({app}:{app:AppInfo}){return <div className="original-app"><LoadedFrame title={app.name} src={app.url}/><div className="program-status"><span>{app.description}</span><span>沿用原项目的登录与存档</span></div></div>}
function TextFile({guide=false}:{guide?:boolean}){return <article className="notepad"><div className="notepad-menu">文件　 编辑　 查看</div>{guide?<div className="notepad-paper"><h1>使用说明.txt</h1><p>01 / 点击桌面图标打开作品。</p><p>02 / 拖动标题栏移动窗口；右下角可以调整大小。</p><p>03 / 最小化后，点击底部任务栏找回来。</p><p>04 / Minecraft 里修改 Python，再点“运行代码”。</p><p>05 / 庭间里的照片来自你的原设计，顶部切换八套方案，底部缩略图切换空间。</p><p>06 / 电脑右键或手机长按桌面/图标，可排序、整理、重命名和查看属性；拖动图标可移动。</p><p>07 / 终端输入 help 查看命令。删除只会触发猫咪星球提示。</p><p>08 / 唱片机最小化后变成随身听，导入本机音频即可播放。</p><p>09 / Ctrl 或 ⌘ K 搜索全部作品；Ctrl + ` 打开终端。</p><p>10 / 在作品集悬停或用 Tab 选择封面，右侧会显示大预览。</p><p>11 / 拖动地面小猫，把它放在图标或窗沿。它会连续跳上应用，每次最高三层图标行距。右键小猫可以聊天、放歌、搬图标和整理桌面；它会先走近图标，用套索收进包里，再搬到另一枚图标的位置交换。桌面右下角的扬声器可开关跳跃、猫叫和魔法音效。遇到外滩或海港的车辆时，会交替用斜盾、火花传送门和跳跃让车通过。海港里右键小猫选择“出海钓鱼”，或把它拖到小船上，可以立即启航。</p><p>12 / 唱片机底部音轨可以点击、拖动，也可以用方向键微调；单曲循环和随机播放都在播放器里。</p><p>13 / 右键桌面 → 修改壁纸：霍格沃茨之夜、月下云海、雨夜外滩、灯火海港，默认每 10 分钟自动轮换；外滩门头可点击，月相会影响场景照明和海港的水面月光。</p><p>14 / 月相每 3 分钟自动切换，月亮周围的八个按钮也可以手动切换；鼠标移上月球会变亮，双击进入隐藏的月之空间。手机双点月球进入、点下方文字切换月相。</p><p>15 / CTY–OS 菜单按桌面、分类、作品逐层展开。鼠标悬停或方向键向右展开，向左返回。</p><p>16 / 第五批已补齐甜境漫游的详细介绍、24 份定量配方与 63 家店铺；长旅支持本机存档与恢复。</p><p>17 / 3D 展厅优先展示精细版马特洪峰；法罗群岛和三寸人间也使用原版场景，隅间可以在站内布置五间卧室。</p><hr/><h2>放到自己的电脑上</h2><p>在 Microsoft Edge 中打开本网站，使用菜单中的“应用 / 将此站点安装为应用”，就可以创建桌面图标，并在独立窗口运行。</p><p>这是可安装的网页应用。AI 与其他在线项目仍需要网络和原有登录。</p></div>:<div className="notepad-paper"><h1>你好，这里是 CTY STUDIO。</h1><p>我用 AI 做网站、游戏和学习工具，也用它设计未来的家，留下家人的照片。</p><p>这台电脑收着我做过的一些作品。你可以写一段 Python，看方块世界长出一座建筑；也可以打开庭间，去看看我为家做的设计。</p><p>脏脏包负责带路。在不同的作品里，它会换上不同的模样。</p><hr/><p>这里还会慢慢增加新的文件。</p><p className="signed">CTY STUDIO & 脏脏包<br/>2026</p></div>}</article>}
const assistantOrigin='https://ai-cat.jackchen911006.chatgpt.site';
function AssistantFrame({open,close,onLearning,entries}:{entries:ReturnType<typeof appEntries>;open:(id:AppId)=>void;close:()=>void;onLearning:(href:string)=>void}){const frame=useRef<HTMLIFrameElement>(null),[ready,setReady]=useState(false),[uncovered,setUncovered]=useState(false),[slow,setSlow]=useState(false),callbacks=useRef({open,close,onLearning,entries});callbacks.current={open,close,onLearning,entries};useEffect(()=>{if(ready)frame.current?.contentWindow?.postMessage({type:"dirtybag-desktop-catalog",entries},assistantOrigin)},[ready,entries]);useEffect(()=>{const timer=setTimeout(()=>setSlow(true),12000);function message(e:MessageEvent){if(e.origin!==assistantOrigin||e.source!==frame.current?.contentWindow)return;const d=e.data;if(!d||typeof d!=='object')return;if(d.type==='dirtybag-assistant-ready'){setReady(true);frame.current?.contentWindow?.postMessage({type:'dirtybag-desktop-catalog',entries:callbacks.current.entries},assistantOrigin);}if(d.type==='dirtybag-open-app'&&apps.some(a=>a.id===d.id)){callbacks.current.open(d.id);callbacks.current.close()}if(d.type==='dirtybag-assistant-close')callbacks.current.close();if(d.type==='dirtybag-open-learning'&&typeof d.href==='string'&&/^\/(?:$|(?:learn|ontology|projects|products|tools|coding|agents|models|resources|guides|roadmap|community|glossary|industry|work|business|library)(?:[?#]|$))/.test(d.href)){callbacks.current.onLearning(d.href);callbacks.current.close()}}window.addEventListener('message',message);return()=>{clearTimeout(timer);window.removeEventListener('message',message)}},[]);return <div className="desktop-assistant-frame">{!ready&&!uncovered&&<div className="assistant-loading-overlay"><AppLoading name="AI 小脏" detail={slow?'正在等待助手就绪，可先完成原站登录':'正在连接问答助手'} elapsed/><div className="assistant-load-note" role="status"><span>{slow?'如果助手未显示，请先打开原助手完成登录，再刷新此窗口。':'正在连接 AI 小脏…'}</span><a href={assistantOrigin+'/desktop-assistant'} target="_blank" rel="noreferrer">打开原助手 <ArrowUpRight size={13}/></a>{slow&&<button onClick={()=>setUncovered(true)}>查看当前页面</button>}</div></div>}<iframe ref={frame} title="AI小脏完整问答助手" src={assistantOrigin+'/desktop-assistant'} allow="clipboard-write; webgpu"/></div>}
type Position={x:number;y:number};
type DesktopPrefs={names:Partial<Record<AppId,string>>;positions:Partial<Record<AppId,Position>>;order:AppId[]};
const defaults:DesktopPrefs={names:{},positions:{},order:desktopApps.map(a=>a.id)};
export default function Desktop(){return <MusicProvider><DesktopSurface/></MusicProvider>}
function DesktopSurface(){
 const music=useMusicControls(),closeTimers=useRef(new Map<AppId,ReturnType<typeof setTimeout>>());
 useEffect(()=>()=>{closeTimers.current.forEach(clearTimeout);document.querySelectorAll<HTMLElement>('[data-window-id]').forEach(cancelWindowDissolve)},[]);
 const [windows,setWindows]=useState<WindowState[]>([]),[selected,setSelected]=useState<AppId|null>(null),[start,setStart]=useState(false),[clock,setClock]=useState(''),[sound,setSound]=useState(true),[welcome,setWelcome]=useState(true);
 const [moonOpen,setMoonOpen]=useState(false);
 const [searchShown,setSearchShown]=useState(false),[calendarShown,setCalendarShown]=useState(false);
 const shortcuts=useRef({search:()=>{},terminal:()=>{}});
 const [prefs,setPrefs]=useState<DesktopPrefs>(defaults),[restored,setRestored]=useState(false),[viewport,setViewport]=useState({w:1364,h:936}),[context,setContext]=useState<AppId|null>(null),[modal,setModal]=useState<'rename'|'properties'|'protected'|null>(null),[rename,setRename]=useState(''),[renameError,setRenameError]=useState(''),[notice,setNotice]=useState(''),[learningPath,setLearningPath]=useState('');
 const [wallpaper,setWallpaper]=useState<WallpaperId>('castle'),[displayedWallpaper,setDisplayedWallpaper]=useState<WallpaperId>('castle'),[autoWallpaper,setAutoWallpaper]=useState(true),[moonPhase,setMoonPhase]=useState(0),[sceneryReady,setSceneryReady]=useState(false);
 const floor=useRef(700),traffic=useRef({...emptyTraffic});
 const mobile=viewport.w<760;
 const assistantEntries=useMemo(()=>appEntries(id=>prefs.names[id]||getApp(id).name),[prefs.names]);
 const [touchMenu,setTouchMenu]=useState(false),[swapTarget,setSwapTarget]=useState<AppId|null>(null);
 const hold=useRef<{timer:ReturnType<typeof setTimeout>;x:number;y:number;pointer:number}|null>(null),blockedTap=useRef(0),holdFired=useRef(false);
 function cancelHold(){if(hold.current)clearTimeout(hold.current.timer);hold.current=null}
 function finishHold(){if(holdFired.current){blockedTap.current=Date.now()+700;holdFired.current=false}cancelHold()}
 useEffect(()=>{const update=()=>document.documentElement.style.setProperty('--visible-height',`${window.visualViewport?.height||window.innerHeight}px`);update();window.visualViewport?.addEventListener('resize',update);return()=>{cancelHold();window.visualViewport?.removeEventListener('resize',update)}},[]);
 useEffect(()=>{const foot=document.querySelector('.taskbar');if(!foot)return;const measure=()=>{floor.current=foot.getBoundingClientRect().top};measure();const observer=new ResizeObserver(measure);observer.observe(foot);return()=>observer.disconnect()},[mobile]);
 useEffect(()=>{const release=()=>finishHold();document.addEventListener('pointerup',release,true);document.addEventListener('pointercancel',release,true);return()=>{document.removeEventListener('pointerup',release,true);document.removeEventListener('pointercancel',release,true)}},[]);
 function mobileMenu(id:AppId|null){cancelHold();setContext(id);setSwapTarget(null);setTouchMenu(true);if(id)setSelected(id)}
 function startHold(e:React.PointerEvent){if(!mobile||e.pointerType==='mouse')return;if(e.isPrimary){blockedTap.current=0;holdFired.current=false}if(!e.isPrimary){cancelHold();return}const el=e.target as HTMLElement;if(!el.closest('[data-mobile-home]')||el.closest('.tiny-companion'))return;const icon=el.closest('[data-app]');if(!icon&&el.closest('button,input,a'))return;cancelHold();const id=icon?.getAttribute('data-app') as AppId|null;hold.current={x:e.clientX,y:e.clientY,pointer:e.pointerId,timer:setTimeout(()=>{holdFired.current=true;blockedTap.current=Date.now()+850;mobileMenu(id);navigator.vibrate?.(18)},550)}}
 function touchAction(action:string){if(action==='open'&&context)open(context);else if(action==='rename'&&context){setRename(name(context));setRenameError('');setModal('rename')}else if(action==='swap'&&context){setSwapTarget(context);setTouchMenu(true)}else if(action==='properties'||action==='protected')setModal(action);else if(action==='name'||action==='type')sort(action);else if(action==='arrange')arrange();else if(action==='terminal')open('terminal')}
 function showHome(){setWindows(ws=>ws.map(w=>({...w,min:true})));setStart(false)}

 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('cty-desktop-scenery-v22')||'null');if(saved){if(wallpapers.some(w=>w.id===saved.wallpaper))setWallpaper(saved.wallpaper);setAutoWallpaper(saved.auto===true);if(Number.isInteger(saved.phase)&&saved.phase>=0&&saved.phase<8)setMoonPhase(saved.phase)}}catch{}setSceneryReady(true);const measure=()=>{floor.current=document.querySelector('.taskbar')?.getBoundingClientRect().top??window.innerHeight-48};measure();const observer=new ResizeObserver(measure);const desktop=document.querySelector('.retro-desktop');if(desktop)observer.observe(desktop);window.addEventListener('resize',measure);return()=>{observer.disconnect();window.removeEventListener('resize',measure)}},[]);
 useEffect(()=>{if(sceneryReady)try{localStorage.setItem('cty-desktop-scenery-v22',JSON.stringify({wallpaper,auto:autoWallpaper,phase:moonPhase}))}catch{}},[wallpaper,autoWallpaper,moonPhase,sceneryReady]);
 // Three visible minutes per phase; choosing one manually starts a fresh interval.
 useEffect(()=>{
  if(!sceneryReady)return;let timer:ReturnType<typeof setTimeout>|undefined,remaining=180000,started=0;
  const pause=()=>{if(timer!==undefined){clearTimeout(timer);timer=undefined;remaining=Math.max(0,remaining-(performance.now()-started))}};
  const sync=()=>{if(document.hidden){pause();return}if(timer!==undefined)return;started=performance.now();timer=setTimeout(()=>{timer=undefined;setMoonPhase(phase=>(phase+1)%moonPhases.length)},remaining)};
  sync();document.addEventListener('visibilitychange',sync);return()=>{pause();document.removeEventListener('visibilitychange',sync)};
 },[sceneryReady,moonPhase]);
 useEffect(()=>{if(!autoWallpaper)return;let elapsed=0;const timer=setInterval(()=>{if(document.hidden)return;elapsed+=1000;if(elapsed>=600000){elapsed=0;setWallpaper(id=>wallpapers[(wallpapers.findIndex(w=>w.id===id)+1)%wallpapers.length].id)}},1000);return()=>clearInterval(timer)},[autoWallpaper,wallpaper]);
 const top=useRef(10),drag=useRef<{id:AppId;x:number;y:number;px:number;py:number}|null>(null),iconDrag=useRef<{id:AppId;x:number;y:number;px:number;py:number;moved:boolean}|null>(null),suppressClick=useRef(false),audio=useRef<ReturnType<typeof createCompanionSound>|null>(null);
 const name=(id:AppId)=>prefs.names[id]||getApp(id).name;
 useEffect(()=>{const tick=()=>setClock(new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false}));tick();const timer=setInterval(tick,10000);const resize=()=>setViewport({w:window.innerWidth,h:window.innerHeight});resize();window.addEventListener('resize',resize);try{const current=localStorage.getItem('dirtybag-desktop-v23'),p=JSON.parse(current||localStorage.getItem('dirtybag-desktop-v3')||'null');if(p){const safe:DesktopPrefs={names:{},positions:{},order:[]};for(const a of apps){if(typeof p.names?.[a.id]==='string'&&p.names[a.id].trim())safe.names[a.id]=p.names[a.id].slice(0,24);const pos=p.positions?.[a.id];if(current&&Number.isFinite(pos?.x)&&Number.isFinite(pos?.y))safe.positions[a.id]={x:pos.x,y:pos.y}}const ids=Array.isArray(p.order)?p.order.filter((id:AppId)=>desktopApps.some(a=>a.id===id)):[];safe.order=[...new Set<AppId>([...ids,...desktopApps.map(a=>a.id)])];setPrefs(safe)}}catch{}setRestored(true);return()=>{clearInterval(timer);window.removeEventListener('resize',resize);void audio.current?.close()}},[]);
 useEffect(()=>{if(restored)try{localStorage.setItem('dirtybag-desktop-v23',JSON.stringify(prefs))}catch{}},[prefs,restored]);
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),3600);return()=>clearTimeout(t)},[notice]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){setStart(false);setSelected(null);setCalendarShown(false)}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();shortcuts.current.search()}if(e.ctrlKey&&e.key==='`'){e.preventDefault();shortcuts.current.terminal()}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[]);
 const visible=windows.filter(w=>!w.min),active=visible.reduce<WindowState|null>((a,w)=>!a||w.z>a.z?w:a,null);
 const cover=coveringWindow(windows),sceneryPaused=moonOpen||!!cover;
 const isWindowVisible=(w:WindowState)=>windowCanAnimate(w,{moonOpen,mobile,activeId:active?.id,coverZ:cover?.z});
 const columns=viewport.w<760?2:viewport.h<700?4:3,rows=Math.ceil(desktopApps.length/columns),spacing=Math.floor(Math.max(viewport.w<760?61:64,Math.min(107,(viewport.h-110)/rows)));
 const iconMaxX=viewport.w<760?107:viewport.w-102,iconMaxY=viewport.w<760?Math.max(viewport.h-145,35+(rows-1)*spacing):viewport.h-145;
 function position(id:AppId,state=prefs):Position{const i=state.order.indexOf(id),p=state.positions[id]||{x:viewport.w<760?8:25,y:viewport.w<760?35:28};return state.positions[id]?{x:Math.max(0,Math.min(iconMaxX,p.x)),y:Math.max(0,Math.min(iconMaxY,p.y))}:{x:p.x+(i%columns)*(viewport.w<760?88:116),y:p.y+Math.floor(i/columns)*spacing}}
 useEffect(()=>{const bus=createCompanionSound();audio.current=bus;try{const on=localStorage.getItem('cty-desktop-sound')!=='off';setSound(on);bus.setEnabled(on)}catch{}const unlock=()=>bus.unlock();document.addEventListener('pointerdown',unlock,{capture:true});document.addEventListener('keydown',unlock,{capture:true});return()=>{document.removeEventListener('pointerdown',unlock,true);document.removeEventListener('keydown',unlock,true);bus.close();audio.current=null}},[]);
 useEffect(()=>{audio.current?.setDucking(music.playing||windows.some(w=>!w.min))},[music.playing,windows]);
 function toggleSound(){const next=!sound;setSound(next);audio.current?.setEnabled(next);if(next){const bus=audio.current;if(bus)void bus.unlock().then(()=>bus.play('tap'))}try{localStorage.setItem('cty-desktop-sound',next?'on':'off')}catch{}}
 function ping(){audio.current?.play('tap')}

 function open(id:AppId){if(id==='zp-music-rooms')id='zp-rooms';const closing=closeTimers.current.get(id);if(closing){clearTimeout(closing);closeTimers.current.delete(id)}const element=document.querySelector<HTMLElement>(`[data-window-id="${id}"]`);if(element)cancelWindowDissolve(element);setSearchShown(false);setCalendarShown(false);setStart(false);setWelcome(false);setSelected(id);ping();setWindows(ws=>{if(ws.some(w=>w.id===id))return ws.map(w=>w.id===id?{...w,min:false,motion:undefined,z:++top.current}:w);const vw=window.innerWidth,vh=window.innerHeight,compact=id==='about'||id==='guide',collection=['works','zp-focus','zp-arcade','zp-art-review'].includes(id),w=Math.min(vw-32,compact?490:id==='cat'?730:id==='terminal'?780:id==='music'?1160:collection?1380:1180),h=Math.min(vh-(collection?72:90),compact?605:id==='terminal'?510:collection?900:780);return [...ws,{id,x:Math.max(16,Math.min(vw-w-16,(vw-w)/2+(ws.length%3)*18)),y:Math.max(20,Math.min(vh-h-48,(vh-h-46)/2+(ws.length%3)*14)),w,h,min:false,max:vw<760,z:++top.current}]})}
 function focus(id:AppId){setWindows(ws=>ws.map(w=>w.id===id?{...w,z:++top.current}:w))}
 function minimize(id:AppId){if(id==='music'){setWindows(ws=>ws.map(w=>w.id===id?{...w,min:true}:w));return}setWindows(ws=>ws.map(w=>w.id===id?{...w,motion:'minimizing'}:w));setTimeout(()=>setWindows(ws=>ws.map(w=>w.id===id&&w.motion==='minimizing'?{...w,min:true,motion:undefined}:w)),170)}
 function close(id:AppId){const el=document.querySelector<HTMLElement>(`[data-window-id="${id}"]`);if(closeTimers.current.has(id)||el?.classList.contains('window-closing'))return;const lifetime=el?dissolveWindow(el):0;if(id==='music'||id==='zp-rooms'||id==='zp-original-music'||id.startsWith('zp-room-'))music.pause();setWindows(ws=>ws.map(w=>w.id===id?{...w,motion:'closing'}:w));closeTimers.current.set(id,setTimeout(()=>{closeTimers.current.delete(id);setWindows(ws=>ws.filter(w=>w.id!==id||w.motion!=='closing'))},lifetime))}
 function toggleMax(id:AppId){setWindows(ws=>ws.map(w=>w.id===id?{...w,max:!w.max,min:false,z:++top.current}:w))}
 function moveWindow(e:React.PointerEvent){if(!drag.current)return;const d=drag.current;setWindows(ws=>ws.map(w=>w.id===d.id?{...w,x:Math.max(0,Math.min(window.innerWidth-180,d.x+e.clientX-d.px)),y:Math.max(0,Math.min(window.innerHeight-110,d.y+e.clientY-d.py))}:w))}
 function alignedIcon(x:number,y:number){return {x:Math.max(25,Math.min(25+Math.floor((iconMaxX-25)/116)*116,25+Math.round((x-25)/116)*116)),y:Math.max(28,Math.min(28+Math.floor((iconMaxY-28)/spacing)*spacing,28+Math.round((y-28)/spacing)*spacing))};}
 function settleIcon(id:AppId,x:number,y:number,origin:Position){const target=alignedIcon(x,y);window.dispatchEvent(new Event('cty-icon-layout-change'));setPrefs(p=>{const occupied=p.order.find(other=>other!==id&&Math.abs(position(other,p).x-target.x)<16&&Math.abs(position(other,p).y-target.y)<16);return {...p,positions:{...p.positions,...(occupied?{[occupied]:alignedIcon(origin.x,origin.y)}:{}),[id]:target}}});}
 function moveIcon(id:AppId,x:number,y:number,free=false){if(!free){settleIcon(id,x,y,position(id));return;}window.dispatchEvent(new Event('cty-icon-layout-change'));setPrefs(p=>({...p,positions:{...p.positions,[id]:{x:Math.max(0,Math.min(iconMaxX,x)),y:Math.max(0,Math.min(iconMaxY,y))}}}))}
 function sort(by:'name'|'type'){window.dispatchEvent(new Event('cty-icon-layout-change'));setPrefs(p=>({...p,positions:{},order:[...p.order].sort((a,b)=>(by==='type'?getApp(a).category.localeCompare(getApp(b).category,'zh-CN'):0)||name(a).localeCompare(name(b),'zh-CN'))}));setNotice(by==='name'?'已按名称排列':'已按类型排列')}
 function arrange(){window.dispatchEvent(new Event('cty-icon-layout-change'));setPrefs(p=>({...p,positions:{}}));setNotice('桌面已整理')}
 function swapIcons(first:AppId,second:AppId,carried=false){if(first===second)return;const before=new Map([first,second].map(id=>[id,document.querySelector<HTMLElement>(`.movable-icons [data-app="${id}"]`)?.getBoundingClientRect()]));setPrefs(p=>mobile?{...p,order:p.order.map(id=>id===first?second:id===second?first:id)}:{...p,positions:{...p.positions,[first]:position(second,p),[second]:position(first,p)}});requestAnimationFrame(()=>{for(const id of [first,second]){const el=document.querySelector<HTMLElement>(`.movable-icons [data-app="${id}"]`),old=before.get(id);el?.classList.remove('cat-carry-origin','cat-carry-target');if(el&&old&&!matchMedia('(prefers-reduced-motion: reduce)').matches){const current=el.getBoundingClientRect();if(carried&&id===first){el.animate([{opacity:.3},{opacity:1}],{duration:160});continue;}el.animate([{transform:`translate(${old.left-current.left}px,${old.top-current.top}px)`,opacity:.35},{transform:'translate(0,0)',opacity:1}],{duration:480,easing:'cubic-bezier(.25,.7,.3,1)'})}}})}
 function renameApp(id:AppId,value:string){const v=value.trim();if(!v||v.length>24)return '名称需要 1–24 个字符。';if(apps.some(a=>a.id!==id&&name(a.id).toLowerCase()===v.toLowerCase()))return '这个名称已经在桌面上了。';setPrefs(p=>({...p,names:{...p.names,[id]:v}}));return ''}
 function property(id:AppId|null){return id?`${name(id)}\n原始名称：${getApp(id).name}\n类型：${getApp(id).category}\n${getApp(id).description}\n位置：猫咪星球 / 电脑桌面\n保护：不可删除`:`CTY–OS 10.0\n用户：CTY STUDIO\n应用：${apps.length} 个\n桌面偏好保存在当前浏览器\n猫咪星球资产保护：开启`}
 function resolve(value:string){const v=value.toLowerCase();return apps.find(a=>a.id===v||a.name.toLowerCase()===v||name(a.id).toLowerCase()===v)?.id}
 function execute(command:string):string{const args=(command.match(/"[^"]*"|'[^']*'|\S+/g)||[]).map(s=>s.replace(/^["']|["']$/g,''));const cmd=(args.shift()||'').toLowerCase();if(['rm','del','delete','remove'].includes(cmd)){setModal('protected');return '禁止删除猫咪星球资产'}if(cmd==='help')return 'help                     查看帮助\nls                       列出应用与 ID\nopen <ID或名称>           打开应用\nclose / minimize <ID>     关闭 / 最小化窗口\nrestore <ID>              恢复窗口\ndesktop                  显示桌面\nsort name|type            按名称 / 类型排序\narrange                  整齐排列图标\nrename <ID> "新名称"      重命名图标\nmove <ID> <x> <y>         移动图标\nproperties [ID]          查看属性\ndate / whoami / clear    时间 / 用户 / 清屏\n\n示例：open minecraft · open music · rename photos "温暖的家"';if(cmd==='ls'||cmd==='apps')return apps.map(a=>a.id.padEnd(12)+' '+name(a.id)).join('\n');if(cmd==='date')return new Date().toLocaleString('zh-CN');if(cmd==='whoami')return 'CTY STUDIO / 猫咪星球居民';if(cmd==='desktop'){setWindows(ws=>ws.map(w=>({...w,min:true})));return '已显示桌面。'}if(cmd==='sort'){if(!['name','type'].includes(args[0]))return '用法：sort name 或 sort type';sort(args[0] as 'name'|'type');return '排序完成。'}if(cmd==='arrange'){arrange();return '桌面整理完成。'}if(cmd==='properties'&&!args.length)return property(null);let id=resolve(args[0]||'');if(cmd==='open'||cmd==='restore'){const match=resolveApp('打开 '+args.join(' '),name);if(match?.kind==='open')id=match.destination.id as AppId;else if(match?.kind==='choose')return '找到多个相近入口，请指定 ID：\n'+match.options.map(a=>a.id+' · '+a.title).join('\n');}if(['open','close','minimize','restore','rename','move','properties'].includes(cmd)){if(!id)return '未找到应用。输入 ls 查看可用名称与 ID。';if(cmd==='open'||cmd==='restore'){open(id);return `已打开 ${name(id)}`}if(cmd==='close'){close(id);return `已关闭 ${name(id)}`}if(cmd==='minimize'){minimize(id);return `已最小化 ${name(id)}`}if(cmd==='properties')return property(id);if(cmd==='rename'){const result=renameApp(id,args.slice(1).join(' '));return result||'已重命名，原作品内容不变。'}if(args.length!==3||!Number.isFinite(Number(args[1]))||!Number.isFinite(Number(args[2])))return '用法：move <ID> <x> <y>';moveIcon(id,Number(args[1]),Number(args[2]));return '图标已移动。'}return `未知命令：${cmd}。输入 help 查看帮助。`}
 function contents(id:AppId,w:WindowState){switch(id){case 'minecraft':return <PythonStudio/>;case 'home':return <HomeGallery/>;case 'cat':return <AssistantFrame entries={assistantEntries} open={open} close={()=>minimize('cat')} onLearning={href=>{setLearningPath(href);open('ai')}}/>;case 'works':return <WorkCatalogue open={open}/>;case 'zp-gallery':return <GalleryShelf open={open}/>;case 'zp-art-review':return <WorkCatalogue open={open} category="文艺复习"/>;case 'zp-focus':return <WorkCatalogue open={open} category="专注世界"/>;case 'zp-arcade':return <WorkCatalogue open={open} category="游戏厅"/>;case 'photos':return <PhotoAlbum/>;case 'stickers':return <StickerAlbum/>;case 'about':return <TextFile/>;case 'guide':return <TextFile guide/>;case 'terminal':return <Terminal execute={execute}/>;case 'music':return <MusicPlayer mini={w.min} onToggle={()=>w.min?open('music'):minimize('music')}/>;default:if(getApp(id).owner==='CTY STUDIO')return <LocalWork app={getApp(id)} open={open} active={isWindowVisible(w)}/>;return <OriginalApp key={id==='ai'?learningPath:id} app={id==='ai'?{...getApp(id),url:getApp(id).url+(learningPath||'')}:getApp(id)}/>}}
 shortcuts.current={search:()=>{setStart(false);setSearchShown(s=>!s)},terminal:()=>open('terminal')};
 const desktopIcons=<nav className="desktop-icons movable-icons" style={{'--icon-slot':`${Math.min(58,Math.max(38,spacing-37))}px`} as CSSProperties} aria-label="桌面作品">{prefs.order.map(id=>{const a=getApp(id),p=position(id);return <button key={id} data-app={id} className={selected===id?'selected':''} style={{left:p.x,top:p.y}} title={`${a.description} · 右键操作 / 拖动移动`} onClick={()=>{if(suppressClick.current){suppressClick.current=false;return}open(id)}} onPointerDown={e=>{if(e.button!==0||viewport.w<760)return;iconDrag.current={id,x:p.x,y:p.y,px:e.clientX,py:e.clientY,moved:false};setSelected(id);e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{const d=iconDrag.current;if(!d||d.id!==id)return;if(Math.hypot(e.clientX-d.px,e.clientY-d.py)>5)d.moved=true;if(d.moved)moveIcon(id,d.x+e.clientX-d.px,d.y+e.clientY-d.py,true)}} onPointerUp={e=>{const d=iconDrag.current;suppressClick.current=d?.moved||false;if(d?.moved)settleIcon(id,d.x+e.clientX-d.px,d.y+e.clientY-d.py,{x:d.x,y:d.y});iconDrag.current=null}} onPointerCancel={()=>{const d=iconDrag.current;if(d?.moved)moveIcon(d.id,d.x,d.y);iconDrag.current=null}}><Icon n={a.icon} normalized/><span className="desktop-icon-label">{name(id)}</span></button>})}</nav>;
 return <><Context.ContextMenu><Context.ContextMenuTrigger asChild disabled={mobile}><main className="retro-desktop" data-mobile={mobile} data-scenery-paused={sceneryPaused} data-app-open={mobile&&!!active} onPointerDownCapture={startHold} onPointerMoveCapture={e=>{const h=hold.current;if(h&&Math.hypot(e.clientX-h.x,e.clientY-h.y)>12)cancelHold()}} onPointerUpCapture={finishHold} onPointerCancelCapture={finishHold} onScrollCapture={cancelHold} onClickCapture={e=>{if(mobile&&(holdFired.current||Date.now()<blockedTap.current)){e.preventDefault();e.stopPropagation();holdFired.current=false}}} data-wallpaper={displayedWallpaper} onContextMenu={e=>{if(mobile){e.preventDefault();const el=e.target as HTMLElement;if(el.closest('[data-mobile-home]'))mobileMenu(el.closest('[data-app]')?.getAttribute('data-app') as AppId|null);return}const id=(e.target as HTMLElement).closest('[data-app]')?.getAttribute('data-app') as AppId|null;setContext(id);if(id)setSelected(id)}} onPointerDown={e=>{if(e.target===e.currentTarget){setSelected(null);setStart(false)}}}>
 <AnimationScope active={!moonOpen&&(!mobile||!active)}><SceneBackdrop animate={!sceneryPaused} wallpaper={wallpaper} floor={floor} traffic={traffic} onOpen={open} onDisplayed={setDisplayedWallpaper} onError={()=>setNotice('这张壁纸暂时没载入，已保留当前场景。可以再切换一次。')} light={moonPhases[moonPhase].light}/>{!mobile&&<MoonCorner phase={moonPhase} onChange={setMoonPhase} width={viewport.w} height={viewport.h-48} onEnter={()=>setMoonOpen(true)}/>}<DesktopAtmosphere skyActive={!sceneryPaused} onSound={cue=>audio.current?.play(cue)} light={moonPhases[moonPhase].light} wallpaper={displayedWallpaper} floor={floor} traffic={traffic} windows={windows} onAsk={()=>open('cat')} onMusic={()=>{open('music');if(!music.playing)music.toggle()}} onWorks={()=>open('works')} onSwapIcons={swapIcons} onArrange={arrange}/><DesktopStars/></AnimationScope>
 {mobile?<><MobileBar clock={clock} onMenu={()=>setStart(v=>!v)} onSearch={()=>setSearchShown(true)} sound={sound} onSound={toggleSound}/><MobileHome onMoonEnter={()=>setMoonOpen(true)} clock={clock} phase={moonPhase} onPhase={setMoonPhase} open={open} onActions={()=>mobileMenu(null)} running={windows.map(w=>w.id)} name={name}>{desktopIcons}</MobileHome></>:desktopIcons}

 <div className="desktop-cat-anchor cat-duty-dock" onContextMenu={e=>e.stopPropagation()}><CatAssistantLauncher open={visible.some(w=>w.id==='cat')} onOpen={()=>open('cat')}/></div>
 {welcome&&<div className="welcome-note"><button className="welcome-close" aria-label="关闭欢迎提示" onClick={()=>setWelcome(false)}>×</button><Icon n={0} small/><div><b>喵，欢迎来到 CTY AI STUDIO。</b><p>我在右下角陪着你。<br/>问 AI，也可以问这台电脑。</p><button onClick={()=>open('cat')}>问一问脏脏包</button></div></div>}
 {windows.map(w=>{const app=getApp(w.id),miniMusic=w.id==='music'&&w.min;return <section key={w.id} data-window-id={w.id} inert={mobile&&(w.min||active?.id!==w.id)?true:undefined} role="dialog" aria-modal="false" aria-label={`${name(w.id)}窗口`} className={`retro-window ${w.max&&!miniMusic?'maximized':''} ${active?.id===w.id?'focused':''} window-${w.id} ${miniMusic?'walkman-window':''} ${w.motion?'window-'+w.motion:''}`} style={{left:w.x,top:w.y,width:w.w,height:w.h,zIndex:miniMusic?5:w.z,display:w.min&&!miniMusic?'none':undefined}} onContextMenu={e=>e.stopPropagation()} onPointerDown={()=>{if(active?.id!==w.id&&!miniMusic)focus(w.id)}}><header className="window-titlebar" onDoubleClick={()=>!mobile&&toggleMax(w.id)} onPointerDown={e=>{if(mobile||w.max||miniMusic||(e.target as HTMLElement).closest('button'))return;drag.current={id:w.id,x:w.x,y:w.y,px:e.clientX,py:e.clientY};e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={moveWindow} onPointerUp={()=>drag.current=null} onPointerCancel={()=>drag.current=null}><button className="mobile-window-back" aria-label="返回桌面" onClick={showHome}><ChevronLeft size={20}/></button><Icon n={app.icon} small/><h2>{miniMusic?'脏脏包随身听':name(w.id)}</h2><span className="titlebar-lines"/><div className="window-buttons">{!miniMusic&&<button aria-label={`最小化${name(w.id)}`} onClick={()=>minimize(w.id)}>_</button>}<button className="window-max-toggle" aria-label={`${miniMusic?'展开':w.max?'还原':'最大化'}${name(w.id)}`} onClick={()=>miniMusic?open(w.id):toggleMax(w.id)}>{w.max&&!miniMusic?<Minimize2 size={13}/>:<Maximize2 size={13}/>}</button><button aria-label={`关闭${name(w.id)}`} onClick={()=>close(w.id)}><X size={16}/></button></div></header>{app.url&&app.owner!=='CTY STUDIO'&&<div className="window-source"><span>{w.id==='minecraft'?'Python → Minecraft':w.id==='home'?'庭间 · 8 套原设计':w.id==='cat'?'AI-cat 原版助手 · 桌面知识':'窗口未显示内容时，可进入完整原项目。'}</span><a href={app.url} target="_blank" rel="noreferrer">进入完整原项目 <ArrowUpRight size={13}/></a></div>}<AnimationScope active={isWindowVisible(w)}><div className="window-content" data-paused={!isWindowVisible(w)}>{contents(w.id,w)}</div></AnimationScope></section>})}
 {notice&&<div className="desktop-toast" role="status">{notice}</div>}
 {start&&<StartMenu order={prefs.order} displayName={name} open={open} onClose={()=>setStart(false)}/>}
 {calendarShown&&<Calendar onClose={()=>setCalendarShown(false)}/>}
 {mobile?<MobileDock open={open} home={showHome} active={active?.id}/>:(<footer className="taskbar"><button data-start-toggle className={`start-button ${start?'pressed':''}`} onClick={()=>setStart(v=>!v)} aria-expanded={start}><Icon n={0} small/><b>CTY—OS</b></button><button className="task-search" aria-label="搜索作品（Ctrl K）" title="搜索作品 · Ctrl / ⌘ K" onClick={()=>setSearchShown(true)}><Search size={17}/></button><div className="task-divider"/><div className="task-apps">{windows.map(w=><button key={w.id} className={active?.id===w.id?'active':''} onClick={()=>active?.id===w.id?minimize(w.id):open(w.id)}><Icon n={getApp(w.id).icon} small/><span>{name(w.id)}</span></button>)}</div><div className="system-tray"><button title={sound?'关闭桌面音效':'开启桌面音效'} aria-label={sound?'关闭桌面音效':'开启桌面音效'} onClick={toggleSound}>{sound?<Volume2 size={17}/>:<VolumeX size={17}/>}</button><span className="tray-language">中</span><button data-calendar-toggle className="tray-clock" aria-label="打开日历" aria-expanded={calendarShown} onClick={()=>setCalendarShown(v=>!v)}><time>{clock||'--:--'}</time></button><button aria-label="显示桌面" title="显示桌面" onClick={()=>{setWindows(ws=>ws.map(w=>({...w,min:true})));setStart(false)}}><Monitor size={15}/></button></div></footer>)}
 </main></Context.ContextMenuTrigger><Context.ContextMenuContent className="desktop-context-menu" collisionPadding={8}><Context.ContextMenuSub><Context.ContextMenuSubTrigger>修改壁纸 · {wallpapers.find(w=>w.id===wallpaper)?.name}</Context.ContextMenuSubTrigger><Context.ContextMenuSubContent className="desktop-context-menu"><Context.ContextMenuRadioGroup value={wallpaper} onValueChange={id=>setWallpaper(id as WallpaperId)}>{wallpapers.map(w=><Context.ContextMenuRadioItem key={w.id} value={w.id}>{w.name}</Context.ContextMenuRadioItem>)}</Context.ContextMenuRadioGroup><Context.ContextMenuSeparator/><Context.ContextMenuCheckboxItem checked={autoWallpaper} onCheckedChange={checked=>setAutoWallpaper(checked===true)}>自动轮换 · 每 10 分钟</Context.ContextMenuCheckboxItem></Context.ContextMenuSubContent></Context.ContextMenuSub><Context.ContextMenuSeparator/>{context&&<><Context.ContextMenuLabel>{name(context)}</Context.ContextMenuLabel><Context.ContextMenuItem onSelect={()=>open(context)}>打开</Context.ContextMenuItem><Context.ContextMenuItem onSelect={()=>{setRename(name(context));setRenameError('');setModal('rename')}}>重命名</Context.ContextMenuItem><Context.ContextMenuSub><Context.ContextMenuSubTrigger>移动位置</Context.ContextMenuSubTrigger><Context.ContextMenuSubContent className="desktop-context-menu"><Context.ContextMenuItem onSelect={()=>moveIcon(context,viewport.w*.42,80)}>移到桌面中央</Context.ContextMenuItem><Context.ContextMenuItem onSelect={()=>moveIcon(context,viewport.w-135,viewport.h*.6)}>移到右侧</Context.ContextMenuItem><Context.ContextMenuItem onSelect={()=>{window.dispatchEvent(new Event('cty-icon-layout-change'));setPrefs(p=>{const positions={...p.positions};delete positions[context];return {...p,positions}})}}>放回排列位置</Context.ContextMenuItem></Context.ContextMenuSubContent></Context.ContextMenuSub><Context.ContextMenuSeparator/></>}<Context.ContextMenuSub><Context.ContextMenuSubTrigger>排序方式</Context.ContextMenuSubTrigger><Context.ContextMenuSubContent className="desktop-context-menu"><Context.ContextMenuItem onSelect={()=>sort('name')}>名称</Context.ContextMenuItem><Context.ContextMenuItem onSelect={()=>sort('type')}>类型</Context.ContextMenuItem></Context.ContextMenuSubContent></Context.ContextMenuSub><Context.ContextMenuItem onSelect={arrange}>整理桌面</Context.ContextMenuItem>{!context&&<Context.ContextMenuItem onSelect={()=>open('terminal')}>在终端中打开</Context.ContextMenuItem>}<Context.ContextMenuSeparator/><Context.ContextMenuItem onSelect={()=>setModal('properties')}>属性</Context.ContextMenuItem>{context&&<Context.ContextMenuItem onSelect={()=>setModal('protected')}>删除</Context.ContextMenuItem>}</Context.ContextMenuContent></Context.ContextMenu>
 {modal&&<DesktopDialog modal={modal} setModal={setModal} context={context} rename={rename} setRename={setRename} renameError={renameError} setRenameError={setRenameError} renameApp={renameApp} setNotice={setNotice} property={property}/>}
 {touchMenu&&<MobileActions shown={touchMenu} onChange={setTouchMenu} title={context?name(context):'桌面操作'} isApp={!!context} onAction={touchAction} wallpaper={wallpaper} setWallpaper={setWallpaper} auto={autoWallpaper} setAuto={setAutoWallpaper} moveTarget={swapTarget} appChoices={prefs.order.map(id=>({id,name:name(id)}))} onSwap={id=>{if(swapTarget)swapIcons(swapTarget,id);setTouchMenu(false);setSwapTarget(null);setNotice('图标位置已交换')}}/>}
 {moonOpen&&<MoonSpace open onChange={setMoonOpen} phase={moonPhase} onPhase={setMoonPhase}/>}{searchShown&&<QuickSearch shown onChange={setSearchShown} open={open} displayName={name}/>}<BootSequence/>
 </>;
}
