import * as THREE from 'three';
import {createKakashi} from './kakashi';
import {disposeLeafModel} from './leaf-npc-models';
import type {Progress} from './types';
const aliases:Record<string,string>={Spine:'spine',Spine002:'chest',Pelvis:'pelvis',Head:'head',ArmL:'shoulder-left',ArmR:'shoulder-right',ForarmL:'elbow-left',ForarmR:'elbow-right',PointerL003:'hand-left',PointerR003:'hand-right',LegL:'hip-left',LegR:'hip-right',CalfL:'knee-left',CalfR:'knee-right',HeelL:'foot-left',HeelR:'foot-right'};
export function rigKakashi(model:THREE.Object3D,driver=createKakashi()){
 const bones=new Map<string,THREE.Bone>();model.traverse(o=>{if(o instanceof THREE.Bone)bones.set(o.name.replace('kakashi-',''),o);});for(const [n,a] of Object.entries(aliases)){const b=bones.get(n);if(b)b.name='teacher-'+a;}
 const rest=new Map([...bones.values()].map(b=>[b,b.quaternion.clone()]));const base=model.position.clone(),v=new THREE.Vector3(),w=new THREE.Vector3();
 function orient(n:string,q:THREE.Quaternion){const b=bones.get(n);if(!b)return;model.updateMatrixWorld(true);b.quaternion.copy(b.parent!.getWorldQuaternion(new THREE.Quaternion()).invert()).multiply(model.getWorldQuaternion(new THREE.Quaternion())).multiply(q);}
 function aim(n:string,child:string,a:string,b:string,bias=0){const joint=bones.get(n),end=bones.get(child),da=driver.root.getObjectByName(a),db=driver.root.getObjectByName(b);if(!joint||!end||!da||!db)return;model.updateMatrixWorld(true);const from=end.getWorldPosition(v).sub(joint.getWorldPosition(w)).normalize(),to=db.getWorldPosition(new THREE.Vector3()).sub(da.getWorldPosition(new THREE.Vector3())).normalize();to.x+=bias;to.normalize().applyQuaternion(model.getWorldQuaternion(new THREE.Quaternion()));const parent=joint.parent!.getWorldQuaternion(new THREE.Quaternion());joint.quaternion.premultiply(parent.clone().invert().multiply(new THREE.Quaternion().setFromUnitVectors(from,to)).multiply(parent));}
 return {bones,animate(...args:Parameters<typeof driver.animate>){driver.animate(...args);driver.root.updateMatrixWorld(true);rest.forEach((q,b)=>b.quaternion.copy(q));model.position.copy(base);model.position.y+=driver.root.children[0].position.y;orient('Spine',driver.root.getObjectByName('equipment')!.parent!.getWorldQuaternion(new THREE.Quaternion()));orient('Head',driver.root.getObjectByName('head')!.getWorldQuaternion(new THREE.Quaternion()));for(const [s,side] of [['L','left'],['R','right']]){aim('Leg'+s,'Calf'+s,'hip-'+side,'knee-'+side);aim('Calf'+s,'Heel'+s,'knee-'+side,'ankle-'+side);orient('Heel'+s,driver.root.getObjectByName('ankle-'+side)!.getWorldQuaternion(new THREE.Quaternion()));aim('Arm'+s,'Forarm'+s,'shoulder-'+side,'elbow-'+side,s==='L'?.2:-.2);aim('Forarm'+s,'Pointer'+s+'003','elbow-'+side,'hand-'+side,s==='L'?.08:-.08);}model.updateMatrixWorld(true);}};
}
export function createSuppliedKakashi(realistic=false){
 const root=new THREE.Group();root.name='kakashi';root.userData.avatar='kakashi';const driver=createKakashi(realistic);root.add(driver.root);let skin:THREE.Object3D|undefined,rig:ReturnType<typeof rigKakashi>|undefined,disposed=false;const abort=new AbortController(),outfit=new THREE.Group(),hand=new THREE.Group();let equipment:Progress['equipment']={};
 function setEquipment(e:Progress['equipment']){equipment=e;driver.setEquipment(e);outfit.clear();hand.clear();for(const o of driver.root.getObjectByName('equipment')?.children||[])outfit.add(o.clone(true));for(const o of driver.root.getObjectByName('equipped-hand')?.children||[])hand.add(o.clone(true));}
 const ready=(async()=>{const r=await fetch('/works/minecraft/models/kakashi/kakashi.json.gz?v=56',{signal:AbortSignal.any([abort.signal,AbortSignal.timeout(30000)])});if(!r.ok)throw Error('卡卡西模型下载失败');let b=await r.arrayBuffer();if(new Uint8Array(b)[0]===31)b=await new Response(new Blob([b]).stream().pipeThrough(new DecompressionStream('gzip'))).arrayBuffer();if(disposed)return false;const candidate=new THREE.ObjectLoader().parse(JSON.parse(new TextDecoder().decode(b)));try{const textures=new Map<string,Promise<THREE.Texture>>(),pending:Promise<void>[]=[];candidate.traverse(o=>{if(o instanceof THREE.Mesh)for(const material of Array.isArray(o.material)?o.material:[o.material]){const m=material as THREE.MeshStandardMaterial,f=m.userData.texture;if(f){if(!textures.has(f))textures.set(f,new THREE.TextureLoader().loadAsync('/works/minecraft/models/kakashi/'+f).then(t=>{t.colorSpace=THREE.SRGBColorSpace;t.flipY=true;return t;}));pending.push(textures.get(f)!.then(t=>{m.map=t;m.needsUpdate=true;}));}}});const result=await Promise.allSettled(pending);if(disposed||result.some(r=>r.status==='rejected')){disposeLeafModel(candidate);return false;}rig=rigKakashi(candidate,driver);skin=candidate;root.remove(driver.root);root.add(skin);rig.bones.get('Spine002')!.add(outfit);outfit.position.set(0,-.65,0);rig.bones.get('PointerR003')!.add(hand);setEquipment(equipment);root.userData.ready=true;return true;}catch(e){disposeLeafModel(candidate);throw e;}})().catch(e=>{root.userData.loadError=String(e);return false;});
 return {root,ready,height:2.25,setEquipment,castOrigin:()=>{root.updateWorldMatrix(true,true);return rig?.bones.get('PointerR003')?.getWorldPosition(new THREE.Vector3())||driver.castOrigin();},animate:(...args:Parameters<typeof driver.animate>)=>{if(rig)rig.animate(...args);else driver.animate(...args);},dispose(){disposed=true;abort.abort();if(skin)disposeLeafModel(skin);driver.dispose();root.clear();}};
}
